package com.MaSoVa.inventory.entity;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Purchase Order Entity
 *
 * Manages purchase orders to suppliers for inventory replenishment
 */
@Document(collection = "purchase_orders")
public class PurchaseOrder {

    @Id
    private String id;

    @Indexed(unique = true)
    private String orderNumber; // PO-YYYYMMDD-XXXX

    @Indexed
    private String storeId;

    @Indexed
    private String supplierId;

    private String supplierName; // Denormalized for quick access

    private List<PurchaseOrderItem> items = new ArrayList<>();

    // Dates
    private LocalDate orderDate;
    private LocalDate expectedDeliveryDate;
    private LocalDate actualDeliveryDate;

    // Status
    @Indexed
    private String status; // DRAFT, PENDING_APPROVAL, APPROVED, SENT, RECEIVED, PARTIALLY_RECEIVED, CANCELLED

    // Financial
    private BigDecimal subtotal; // Sum of all items
    private BigDecimal taxAmount; // GST or other taxes
    private BigDecimal shippingCost;
    private BigDecimal discountAmount;
    private BigDecimal totalAmount; // Final amount to pay

    private String paymentStatus; // PENDING, PARTIALLY_PAID, PAID

    // Approval workflow
    private String requestedBy; // User ID who created the PO
    private String approvedBy; // Manager who approved
    private LocalDateTime approvedAt;
    private String rejectionReason;

    // Receiving
    private String receivedBy; // User ID who received the order
    private LocalDateTime receivedAt;
    private String receivingNotes;

    // Auto-generated flag
    private Boolean autoGenerated; // True if generated automatically from low stock

    private String notes;

    @CreatedDate
    private LocalDateTime createdAt;

    @LastModifiedDate
    private LocalDateTime updatedAt;

    // Constructors
    public PurchaseOrder() {
        this.status = "DRAFT";
        this.paymentStatus = "PENDING";
        this.autoGenerated = false;
        this.items = new ArrayList<>();
        this.orderDate = LocalDate.now();
        this.subtotal = BigDecimal.ZERO;
        this.taxAmount = BigDecimal.ZERO;
        this.shippingCost = BigDecimal.ZERO;
        this.discountAmount = BigDecimal.ZERO;
        this.totalAmount = BigDecimal.ZERO;
    }

    // Business logic methods

    /**
     * Calculate total amount from items
     */
    public void calculateTotals() {
        this.subtotal = items.stream()
                .map(item -> item.getUnitPrice().multiply(BigDecimal.valueOf(item.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        // Calculate tax (assuming 5% GST for simplicity)
        this.taxAmount = this.subtotal.multiply(BigDecimal.valueOf(0.05));

        // Calculate total
        this.totalAmount = this.subtotal
                .add(this.taxAmount)
                .add(this.shippingCost != null ? this.shippingCost : BigDecimal.ZERO)
                .subtract(this.discountAmount != null ? this.discountAmount : BigDecimal.ZERO);
    }

    /**
     * Check if order is overdue
     */
    public Boolean isOverdue() {
        if (expectedDeliveryDate == null || actualDeliveryDate != null) {
            return false;
        }
        return LocalDate.now().isAfter(expectedDeliveryDate) &&
               !status.equals("RECEIVED") &&
               !status.equals("CANCELLED");
    }

    /**
     * Check if order is fully received
     */
    public Boolean isFullyReceived() {
        if (items.isEmpty()) {
            return false;
        }
        return items.stream().allMatch(item ->
            item.getReceivedQuantity() != null &&
            item.getReceivedQuantity().equals(item.getQuantity())
        );
    }

    /**
     * Check if order is partially received
     */
    public Boolean isPartiallyReceived() {
        return items.stream().anyMatch(item ->
            item.getReceivedQuantity() != null &&
            item.getReceivedQuantity() > 0 &&
            item.getReceivedQuantity() < item.getQuantity()
        );
    }

    // Inner class for Purchase Order Items
    public static class PurchaseOrderItem {
        private String inventoryItemId;
        private String itemName;
        private String itemCode;
        private Double quantity;
        private String unit;
        private BigDecimal unitPrice;
        private BigDecimal totalPrice;
        private Double receivedQuantity; // Actual quantity received
        private String notes;

        public PurchaseOrderItem() {
            this.receivedQuantity = 0.0;
        }

        public void calculateTotalPrice() {
            if (quantity != null && unitPrice != null) {
                this.totalPrice = unitPrice.multiply(BigDecimal.valueOf(quantity));
            }
        }

        // Getters and Setters
        public String getInventoryItemId() {
            return inventoryItemId;
        }

        public void setInventoryItemId(String inventoryItemId) {
            this.inventoryItemId = inventoryItemId;
        }

        public String getItemName() {
            return itemName;
        }

        public void setItemName(String itemName) {
            this.itemName = itemName;
        }

        public String getItemCode() {
            return itemCode;
        }

        public void setItemCode(String itemCode) {
            this.itemCode = itemCode;
        }

        public Double getQuantity() {
            return quantity;
        }

        public void setQuantity(Double quantity) {
            this.quantity = quantity;
        }

        public String getUnit() {
            return unit;
        }

        public void setUnit(String unit) {
            this.unit = unit;
        }

        public BigDecimal getUnitPrice() {
            return unitPrice;
        }

        public void setUnitPrice(BigDecimal unitPrice) {
            this.unitPrice = unitPrice;
        }

        public BigDecimal getTotalPrice() {
            return totalPrice;
        }

        public void setTotalPrice(BigDecimal totalPrice) {
            this.totalPrice = totalPrice;
        }

        public Double getReceivedQuantity() {
            return receivedQuantity;
        }

        public void setReceivedQuantity(Double receivedQuantity) {
            this.receivedQuantity = receivedQuantity;
        }

        public String getNotes() {
            return notes;
        }

        public void setNotes(String notes) {
            this.notes = notes;
        }
    }

    // Getters and Setters

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getStoreId() {
        return storeId;
    }

    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    public String getSupplierId() {
        return supplierId;
    }

    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    public List<PurchaseOrderItem> getItems() {
        return items;
    }

    public void setItems(List<PurchaseOrderItem> items) {
        this.items = items;
    }

    public LocalDate getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(LocalDate orderDate) {
        this.orderDate = orderDate;
    }

    public LocalDate getExpectedDeliveryDate() {
        return expectedDeliveryDate;
    }

    public void setExpectedDeliveryDate(LocalDate expectedDeliveryDate) {
        this.expectedDeliveryDate = expectedDeliveryDate;
    }

    public LocalDate getActualDeliveryDate() {
        return actualDeliveryDate;
    }

    public void setActualDeliveryDate(LocalDate actualDeliveryDate) {
        this.actualDeliveryDate = actualDeliveryDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public BigDecimal getSubtotal() {
        return subtotal;
    }

    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    public BigDecimal getTaxAmount() {
        return taxAmount;
    }

    public void setTaxAmount(BigDecimal taxAmount) {
        this.taxAmount = taxAmount;
    }

    public BigDecimal getShippingCost() {
        return shippingCost;
    }

    public void setShippingCost(BigDecimal shippingCost) {
        this.shippingCost = shippingCost;
    }

    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    public String getRequestedBy() {
        return requestedBy;
    }

    public void setRequestedBy(String requestedBy) {
        this.requestedBy = requestedBy;
    }

    public String getApprovedBy() {
        return approvedBy;
    }

    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }

    public LocalDateTime getApprovedAt() {
        return approvedAt;
    }

    public void setApprovedAt(LocalDateTime approvedAt) {
        this.approvedAt = approvedAt;
    }

    public String getRejectionReason() {
        return rejectionReason;
    }

    public void setRejectionReason(String rejectionReason) {
        this.rejectionReason = rejectionReason;
    }

    public String getReceivedBy() {
        return receivedBy;
    }

    public void setReceivedBy(String receivedBy) {
        this.receivedBy = receivedBy;
    }

    public LocalDateTime getReceivedAt() {
        return receivedAt;
    }

    public void setReceivedAt(LocalDateTime receivedAt) {
        this.receivedAt = receivedAt;
    }

    public String getReceivingNotes() {
        return receivingNotes;
    }

    public void setReceivingNotes(String receivingNotes) {
        this.receivingNotes = receivingNotes;
    }

    public Boolean getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
