package com.MaSoVa.shared.enums;

public enum ConsentType {
    TERMS_AND_CONDITIONS,
    PRIVACY_POLICY,
    COOKIE_POLICY,
    MARKETING_COMMUNICATIONS,
    DATA_PROCESSING,
    THIRD_PARTY_SHARING,
    ANALYTICS_TRACKING,
    PERSONALIZATION,
    LOCATION_TRACKING,
    NOTIFICATIONS,
    PROFILING
}
