package com.MaSoVa.shared.enums;

public enum GdprActionType {
    CONSENT_GRANTED,
    CONSENT_REVOKED,
    CONSENT_UPDATED,
    DATA_ACCESSED,
    DATA_EXPORTED,
    DATA_RECTIFIED,
    DATA_DELETED,
    DATA_ANONYMIZED,
    PROCESSING_RESTRICTED,
    PROCESSING_OBJECTED,
    REQUEST_SUBMITTED,
    REQUEST_PROCESSED,
    POLICY_ACCEPTED,
    POLICY_DECLINED,
    BREACH_DETECTED,
    BREACH_NOTIFIED,
    DPA_SIGNED,
    RETENTION_POLICY_APPLIED,
    DATA_TRANSFERRED
}
