package com.MaSoVa.logistics.inventory.repository;

import com.MaSoVa.logistics.inventory.entity.PurchaseOrder;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.mongodb.repository.Query;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

/**
 * Repository interface for PurchaseOrder entity
 */
@Repository
public interface PurchaseOrderRepository extends MongoRepository<PurchaseOrder, String> {

    /**
     * Find purchase order by unique order number
     */
    Optional<PurchaseOrder> findByOrderNumber(String orderNumber);

    /**
     * Find all purchase orders by store
     */
    List<PurchaseOrder> findByStoreId(String storeId);

    /**
     * Find purchase orders by store and status
     */
    List<PurchaseOrder> findByStoreIdAndStatus(String storeId, String status);

    /**
     * Find purchase orders by supplier
     */
    List<PurchaseOrder> findBySupplierId(String supplierId);

    /**
     * Find purchase orders by supplier and status
     */
    List<PurchaseOrder> findBySupplierIdAndStatus(String supplierId, String status);

    /**
     * Find auto-generated purchase orders
     */
    List<PurchaseOrder> findByStoreIdAndAutoGenerated(String storeId, Boolean autoGenerated);

    /**
     * Find purchase orders pending approval
     */
    List<PurchaseOrder> findByStoreIdAndStatusIn(String storeId, List<String> statuses);

    /**
     * Find overdue purchase orders
     */
    @Query("{ 'storeId': ?0, 'expectedDeliveryDate': { $lt: ?1 }, 'status': { $in: ['SENT', 'APPROVED'] } }")
    List<PurchaseOrder> findOverdueOrders(String storeId, LocalDate currentDate);

    /**
     * Find purchase orders by date range
     */
    @Query("{ 'storeId': ?0, 'orderDate': { $gte: ?1, $lte: ?2 } }")
    List<PurchaseOrder> findByDateRange(String storeId, LocalDate startDate, LocalDate endDate);

    /**
     * Find purchase orders requested by user
     */
    List<PurchaseOrder> findByRequestedBy(String userId);

    /**
     * Find recent purchase orders
     */
    @Query("{ 'storeId': ?0 }")
    List<PurchaseOrder> findRecentOrders(String storeId);
}
