#!/bin/bash
# Copy pact files generated by frontend consumer tests to backend services for provider verification
# Run after: cd frontend && npm run test:pact
FRONTEND_PACTS="frontend/pacts"
SERVICES=("commerce-service" "core-service" "logistics-service" "payment-service")

if [ ! -d "$FRONTEND_PACTS" ]; then
  echo "ERROR: $FRONTEND_PACTS does not exist. Run 'npm run test:pact' in frontend first."
  exit 1
fi

for svc in "${SERVICES[@]}"; do
  mkdir -p "$svc/src/test/resources/pacts"
  count=$(ls "$FRONTEND_PACTS"/*.json 2>/dev/null | wc -l)
  if [ "$count" -gt 0 ]; then
    cp "$FRONTEND_PACTS"/*.json "$svc/src/test/resources/pacts/"
    echo "Copied $count pact file(s) to $svc"
  else
    echo "No pact files found in $FRONTEND_PACTS"
  fi
done
