// Generated by delombok at Wed Nov 26 14:14:06 IST 2025
package com.MaSoVa.analytics.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

public class ChurnPredictionResponse {
    private int totalCustomersAnalyzed;
    private int highRiskCustomers;
    private int mediumRiskCustomers;
    private int lowRiskCustomers;
    private BigDecimal predictedChurnRate; // Percentage
    private List<ChurnRiskCustomer> atRiskCustomers;
    private List<ChurnFactor> churnFactors;


    public static class ChurnRiskCustomer {
        private String customerId;
        private String customerName;
        private String email;
        private String riskLevel; // "HIGH", "MEDIUM", "LOW"
        private BigDecimal churnProbability; // 0-100
        private int daysSinceLastOrder;
        private BigDecimal lifetimeValue;
        private int totalOrders;
        private LocalDateTime lastOrderDate;
        private List<String> riskFactors;


        @java.lang.SuppressWarnings("all")
        public static class ChurnRiskCustomerBuilder {
            @java.lang.SuppressWarnings("all")
            private String customerId;
            @java.lang.SuppressWarnings("all")
            private String customerName;
            @java.lang.SuppressWarnings("all")
            private String email;
            @java.lang.SuppressWarnings("all")
            private String riskLevel;
            @java.lang.SuppressWarnings("all")
            private BigDecimal churnProbability;
            @java.lang.SuppressWarnings("all")
            private int daysSinceLastOrder;
            @java.lang.SuppressWarnings("all")
            private BigDecimal lifetimeValue;
            @java.lang.SuppressWarnings("all")
            private int totalOrders;
            @java.lang.SuppressWarnings("all")
            private LocalDateTime lastOrderDate;
            @java.lang.SuppressWarnings("all")
            private List<String> riskFactors;

            @java.lang.SuppressWarnings("all")
            ChurnRiskCustomerBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder customerId(final String customerId) {
                this.customerId = customerId;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder customerName(final String customerName) {
                this.customerName = customerName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder email(final String email) {
                this.email = email;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder riskLevel(final String riskLevel) {
                this.riskLevel = riskLevel;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder churnProbability(final BigDecimal churnProbability) {
                this.churnProbability = churnProbability;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder daysSinceLastOrder(final int daysSinceLastOrder) {
                this.daysSinceLastOrder = daysSinceLastOrder;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder lifetimeValue(final BigDecimal lifetimeValue) {
                this.lifetimeValue = lifetimeValue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder totalOrders(final int totalOrders) {
                this.totalOrders = totalOrders;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder lastOrderDate(final LocalDateTime lastOrderDate) {
                this.lastOrderDate = lastOrderDate;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder riskFactors(final List<String> riskFactors) {
                this.riskFactors = riskFactors;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnRiskCustomer build() {
                return new ChurnPredictionResponse.ChurnRiskCustomer(this.customerId, this.customerName, this.email, this.riskLevel, this.churnProbability, this.daysSinceLastOrder, this.lifetimeValue, this.totalOrders, this.lastOrderDate, this.riskFactors);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder(customerId=" + this.customerId + ", customerName=" + this.customerName + ", email=" + this.email + ", riskLevel=" + this.riskLevel + ", churnProbability=" + this.churnProbability + ", daysSinceLastOrder=" + this.daysSinceLastOrder + ", lifetimeValue=" + this.lifetimeValue + ", totalOrders=" + this.totalOrders + ", lastOrderDate=" + this.lastOrderDate + ", riskFactors=" + this.riskFactors + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder builder() {
            return new ChurnPredictionResponse.ChurnRiskCustomer.ChurnRiskCustomerBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getCustomerId() {
            return this.customerId;
        }

        @java.lang.SuppressWarnings("all")
        public String getCustomerName() {
            return this.customerName;
        }

        @java.lang.SuppressWarnings("all")
        public String getEmail() {
            return this.email;
        }

        @java.lang.SuppressWarnings("all")
        public String getRiskLevel() {
            return this.riskLevel;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getChurnProbability() {
            return this.churnProbability;
        }

        @java.lang.SuppressWarnings("all")
        public int getDaysSinceLastOrder() {
            return this.daysSinceLastOrder;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getLifetimeValue() {
            return this.lifetimeValue;
        }

        @java.lang.SuppressWarnings("all")
        public int getTotalOrders() {
            return this.totalOrders;
        }

        @java.lang.SuppressWarnings("all")
        public LocalDateTime getLastOrderDate() {
            return this.lastOrderDate;
        }

        @java.lang.SuppressWarnings("all")
        public List<String> getRiskFactors() {
            return this.riskFactors;
        }

        @java.lang.SuppressWarnings("all")
        public void setCustomerId(final String customerId) {
            this.customerId = customerId;
        }

        @java.lang.SuppressWarnings("all")
        public void setCustomerName(final String customerName) {
            this.customerName = customerName;
        }

        @java.lang.SuppressWarnings("all")
        public void setEmail(final String email) {
            this.email = email;
        }

        @java.lang.SuppressWarnings("all")
        public void setRiskLevel(final String riskLevel) {
            this.riskLevel = riskLevel;
        }

        @java.lang.SuppressWarnings("all")
        public void setChurnProbability(final BigDecimal churnProbability) {
            this.churnProbability = churnProbability;
        }

        @java.lang.SuppressWarnings("all")
        public void setDaysSinceLastOrder(final int daysSinceLastOrder) {
            this.daysSinceLastOrder = daysSinceLastOrder;
        }

        @java.lang.SuppressWarnings("all")
        public void setLifetimeValue(final BigDecimal lifetimeValue) {
            this.lifetimeValue = lifetimeValue;
        }

        @java.lang.SuppressWarnings("all")
        public void setTotalOrders(final int totalOrders) {
            this.totalOrders = totalOrders;
        }

        @java.lang.SuppressWarnings("all")
        public void setLastOrderDate(final LocalDateTime lastOrderDate) {
            this.lastOrderDate = lastOrderDate;
        }

        @java.lang.SuppressWarnings("all")
        public void setRiskFactors(final List<String> riskFactors) {
            this.riskFactors = riskFactors;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ChurnPredictionResponse.ChurnRiskCustomer)) return false;
            final ChurnPredictionResponse.ChurnRiskCustomer other = (ChurnPredictionResponse.ChurnRiskCustomer) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getDaysSinceLastOrder() != other.getDaysSinceLastOrder()) return false;
            if (this.getTotalOrders() != other.getTotalOrders()) return false;
            final java.lang.Object this$customerId = this.getCustomerId();
            final java.lang.Object other$customerId = other.getCustomerId();
            if (this$customerId == null ? other$customerId != null : !this$customerId.equals(other$customerId)) return false;
            final java.lang.Object this$customerName = this.getCustomerName();
            final java.lang.Object other$customerName = other.getCustomerName();
            if (this$customerName == null ? other$customerName != null : !this$customerName.equals(other$customerName)) return false;
            final java.lang.Object this$email = this.getEmail();
            final java.lang.Object other$email = other.getEmail();
            if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
            final java.lang.Object this$riskLevel = this.getRiskLevel();
            final java.lang.Object other$riskLevel = other.getRiskLevel();
            if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
            final java.lang.Object this$churnProbability = this.getChurnProbability();
            final java.lang.Object other$churnProbability = other.getChurnProbability();
            if (this$churnProbability == null ? other$churnProbability != null : !this$churnProbability.equals(other$churnProbability)) return false;
            final java.lang.Object this$lifetimeValue = this.getLifetimeValue();
            final java.lang.Object other$lifetimeValue = other.getLifetimeValue();
            if (this$lifetimeValue == null ? other$lifetimeValue != null : !this$lifetimeValue.equals(other$lifetimeValue)) return false;
            final java.lang.Object this$lastOrderDate = this.getLastOrderDate();
            final java.lang.Object other$lastOrderDate = other.getLastOrderDate();
            if (this$lastOrderDate == null ? other$lastOrderDate != null : !this$lastOrderDate.equals(other$lastOrderDate)) return false;
            final java.lang.Object this$riskFactors = this.getRiskFactors();
            final java.lang.Object other$riskFactors = other.getRiskFactors();
            if (this$riskFactors == null ? other$riskFactors != null : !this$riskFactors.equals(other$riskFactors)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ChurnPredictionResponse.ChurnRiskCustomer;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getDaysSinceLastOrder();
            result = result * PRIME + this.getTotalOrders();
            final java.lang.Object $customerId = this.getCustomerId();
            result = result * PRIME + ($customerId == null ? 43 : $customerId.hashCode());
            final java.lang.Object $customerName = this.getCustomerName();
            result = result * PRIME + ($customerName == null ? 43 : $customerName.hashCode());
            final java.lang.Object $email = this.getEmail();
            result = result * PRIME + ($email == null ? 43 : $email.hashCode());
            final java.lang.Object $riskLevel = this.getRiskLevel();
            result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
            final java.lang.Object $churnProbability = this.getChurnProbability();
            result = result * PRIME + ($churnProbability == null ? 43 : $churnProbability.hashCode());
            final java.lang.Object $lifetimeValue = this.getLifetimeValue();
            result = result * PRIME + ($lifetimeValue == null ? 43 : $lifetimeValue.hashCode());
            final java.lang.Object $lastOrderDate = this.getLastOrderDate();
            result = result * PRIME + ($lastOrderDate == null ? 43 : $lastOrderDate.hashCode());
            final java.lang.Object $riskFactors = this.getRiskFactors();
            result = result * PRIME + ($riskFactors == null ? 43 : $riskFactors.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ChurnPredictionResponse.ChurnRiskCustomer(customerId=" + this.getCustomerId() + ", customerName=" + this.getCustomerName() + ", email=" + this.getEmail() + ", riskLevel=" + this.getRiskLevel() + ", churnProbability=" + this.getChurnProbability() + ", daysSinceLastOrder=" + this.getDaysSinceLastOrder() + ", lifetimeValue=" + this.getLifetimeValue() + ", totalOrders=" + this.getTotalOrders() + ", lastOrderDate=" + this.getLastOrderDate() + ", riskFactors=" + this.getRiskFactors() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public ChurnRiskCustomer() {
        }

        @java.lang.SuppressWarnings("all")
        public ChurnRiskCustomer(final String customerId, final String customerName, final String email, final String riskLevel, final BigDecimal churnProbability, final int daysSinceLastOrder, final BigDecimal lifetimeValue, final int totalOrders, final LocalDateTime lastOrderDate, final List<String> riskFactors) {
            this.customerId = customerId;
            this.customerName = customerName;
            this.email = email;
            this.riskLevel = riskLevel;
            this.churnProbability = churnProbability;
            this.daysSinceLastOrder = daysSinceLastOrder;
            this.lifetimeValue = lifetimeValue;
            this.totalOrders = totalOrders;
            this.lastOrderDate = lastOrderDate;
            this.riskFactors = riskFactors;
        }
    }


    public static class ChurnFactor {
        private String factorName;
        private String description;
        private BigDecimal impactScore; // 0-100
        private int customersAffected;


        @java.lang.SuppressWarnings("all")
        public static class ChurnFactorBuilder {
            @java.lang.SuppressWarnings("all")
            private String factorName;
            @java.lang.SuppressWarnings("all")
            private String description;
            @java.lang.SuppressWarnings("all")
            private BigDecimal impactScore;
            @java.lang.SuppressWarnings("all")
            private int customersAffected;

            @java.lang.SuppressWarnings("all")
            ChurnFactorBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnFactor.ChurnFactorBuilder factorName(final String factorName) {
                this.factorName = factorName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnFactor.ChurnFactorBuilder description(final String description) {
                this.description = description;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnFactor.ChurnFactorBuilder impactScore(final BigDecimal impactScore) {
                this.impactScore = impactScore;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnFactor.ChurnFactorBuilder customersAffected(final int customersAffected) {
                this.customersAffected = customersAffected;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public ChurnPredictionResponse.ChurnFactor build() {
                return new ChurnPredictionResponse.ChurnFactor(this.factorName, this.description, this.impactScore, this.customersAffected);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "ChurnPredictionResponse.ChurnFactor.ChurnFactorBuilder(factorName=" + this.factorName + ", description=" + this.description + ", impactScore=" + this.impactScore + ", customersAffected=" + this.customersAffected + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static ChurnPredictionResponse.ChurnFactor.ChurnFactorBuilder builder() {
            return new ChurnPredictionResponse.ChurnFactor.ChurnFactorBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getFactorName() {
            return this.factorName;
        }

        @java.lang.SuppressWarnings("all")
        public String getDescription() {
            return this.description;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getImpactScore() {
            return this.impactScore;
        }

        @java.lang.SuppressWarnings("all")
        public int getCustomersAffected() {
            return this.customersAffected;
        }

        @java.lang.SuppressWarnings("all")
        public void setFactorName(final String factorName) {
            this.factorName = factorName;
        }

        @java.lang.SuppressWarnings("all")
        public void setDescription(final String description) {
            this.description = description;
        }

        @java.lang.SuppressWarnings("all")
        public void setImpactScore(final BigDecimal impactScore) {
            this.impactScore = impactScore;
        }

        @java.lang.SuppressWarnings("all")
        public void setCustomersAffected(final int customersAffected) {
            this.customersAffected = customersAffected;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ChurnPredictionResponse.ChurnFactor)) return false;
            final ChurnPredictionResponse.ChurnFactor other = (ChurnPredictionResponse.ChurnFactor) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getCustomersAffected() != other.getCustomersAffected()) return false;
            final java.lang.Object this$factorName = this.getFactorName();
            final java.lang.Object other$factorName = other.getFactorName();
            if (this$factorName == null ? other$factorName != null : !this$factorName.equals(other$factorName)) return false;
            final java.lang.Object this$description = this.getDescription();
            final java.lang.Object other$description = other.getDescription();
            if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
            final java.lang.Object this$impactScore = this.getImpactScore();
            final java.lang.Object other$impactScore = other.getImpactScore();
            if (this$impactScore == null ? other$impactScore != null : !this$impactScore.equals(other$impactScore)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ChurnPredictionResponse.ChurnFactor;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getCustomersAffected();
            final java.lang.Object $factorName = this.getFactorName();
            result = result * PRIME + ($factorName == null ? 43 : $factorName.hashCode());
            final java.lang.Object $description = this.getDescription();
            result = result * PRIME + ($description == null ? 43 : $description.hashCode());
            final java.lang.Object $impactScore = this.getImpactScore();
            result = result * PRIME + ($impactScore == null ? 43 : $impactScore.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ChurnPredictionResponse.ChurnFactor(factorName=" + this.getFactorName() + ", description=" + this.getDescription() + ", impactScore=" + this.getImpactScore() + ", customersAffected=" + this.getCustomersAffected() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public ChurnFactor() {
        }

        @java.lang.SuppressWarnings("all")
        public ChurnFactor(final String factorName, final String description, final BigDecimal impactScore, final int customersAffected) {
            this.factorName = factorName;
            this.description = description;
            this.impactScore = impactScore;
            this.customersAffected = customersAffected;
        }
    }


    @java.lang.SuppressWarnings("all")
    public static class ChurnPredictionResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private int totalCustomersAnalyzed;
        @java.lang.SuppressWarnings("all")
        private int highRiskCustomers;
        @java.lang.SuppressWarnings("all")
        private int mediumRiskCustomers;
        @java.lang.SuppressWarnings("all")
        private int lowRiskCustomers;
        @java.lang.SuppressWarnings("all")
        private BigDecimal predictedChurnRate;
        @java.lang.SuppressWarnings("all")
        private List<ChurnRiskCustomer> atRiskCustomers;
        @java.lang.SuppressWarnings("all")
        private List<ChurnFactor> churnFactors;

        @java.lang.SuppressWarnings("all")
        ChurnPredictionResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ChurnPredictionResponse.ChurnPredictionResponseBuilder totalCustomersAnalyzed(final int totalCustomersAnalyzed) {
            this.totalCustomersAnalyzed = totalCustomersAnalyzed;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ChurnPredictionResponse.ChurnPredictionResponseBuilder highRiskCustomers(final int highRiskCustomers) {
            this.highRiskCustomers = highRiskCustomers;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ChurnPredictionResponse.ChurnPredictionResponseBuilder mediumRiskCustomers(final int mediumRiskCustomers) {
            this.mediumRiskCustomers = mediumRiskCustomers;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ChurnPredictionResponse.ChurnPredictionResponseBuilder lowRiskCustomers(final int lowRiskCustomers) {
            this.lowRiskCustomers = lowRiskCustomers;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ChurnPredictionResponse.ChurnPredictionResponseBuilder predictedChurnRate(final BigDecimal predictedChurnRate) {
            this.predictedChurnRate = predictedChurnRate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ChurnPredictionResponse.ChurnPredictionResponseBuilder atRiskCustomers(final List<ChurnRiskCustomer> atRiskCustomers) {
            this.atRiskCustomers = atRiskCustomers;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ChurnPredictionResponse.ChurnPredictionResponseBuilder churnFactors(final List<ChurnFactor> churnFactors) {
            this.churnFactors = churnFactors;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public ChurnPredictionResponse build() {
            return new ChurnPredictionResponse(this.totalCustomersAnalyzed, this.highRiskCustomers, this.mediumRiskCustomers, this.lowRiskCustomers, this.predictedChurnRate, this.atRiskCustomers, this.churnFactors);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ChurnPredictionResponse.ChurnPredictionResponseBuilder(totalCustomersAnalyzed=" + this.totalCustomersAnalyzed + ", highRiskCustomers=" + this.highRiskCustomers + ", mediumRiskCustomers=" + this.mediumRiskCustomers + ", lowRiskCustomers=" + this.lowRiskCustomers + ", predictedChurnRate=" + this.predictedChurnRate + ", atRiskCustomers=" + this.atRiskCustomers + ", churnFactors=" + this.churnFactors + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static ChurnPredictionResponse.ChurnPredictionResponseBuilder builder() {
        return new ChurnPredictionResponse.ChurnPredictionResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public int getTotalCustomersAnalyzed() {
        return this.totalCustomersAnalyzed;
    }

    @java.lang.SuppressWarnings("all")
    public int getHighRiskCustomers() {
        return this.highRiskCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public int getMediumRiskCustomers() {
        return this.mediumRiskCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public int getLowRiskCustomers() {
        return this.lowRiskCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getPredictedChurnRate() {
        return this.predictedChurnRate;
    }

    @java.lang.SuppressWarnings("all")
    public List<ChurnRiskCustomer> getAtRiskCustomers() {
        return this.atRiskCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public List<ChurnFactor> getChurnFactors() {
        return this.churnFactors;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalCustomersAnalyzed(final int totalCustomersAnalyzed) {
        this.totalCustomersAnalyzed = totalCustomersAnalyzed;
    }

    @java.lang.SuppressWarnings("all")
    public void setHighRiskCustomers(final int highRiskCustomers) {
        this.highRiskCustomers = highRiskCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public void setMediumRiskCustomers(final int mediumRiskCustomers) {
        this.mediumRiskCustomers = mediumRiskCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public void setLowRiskCustomers(final int lowRiskCustomers) {
        this.lowRiskCustomers = lowRiskCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public void setPredictedChurnRate(final BigDecimal predictedChurnRate) {
        this.predictedChurnRate = predictedChurnRate;
    }

    @java.lang.SuppressWarnings("all")
    public void setAtRiskCustomers(final List<ChurnRiskCustomer> atRiskCustomers) {
        this.atRiskCustomers = atRiskCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public void setChurnFactors(final List<ChurnFactor> churnFactors) {
        this.churnFactors = churnFactors;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ChurnPredictionResponse)) return false;
        final ChurnPredictionResponse other = (ChurnPredictionResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalCustomersAnalyzed() != other.getTotalCustomersAnalyzed()) return false;
        if (this.getHighRiskCustomers() != other.getHighRiskCustomers()) return false;
        if (this.getMediumRiskCustomers() != other.getMediumRiskCustomers()) return false;
        if (this.getLowRiskCustomers() != other.getLowRiskCustomers()) return false;
        final java.lang.Object this$predictedChurnRate = this.getPredictedChurnRate();
        final java.lang.Object other$predictedChurnRate = other.getPredictedChurnRate();
        if (this$predictedChurnRate == null ? other$predictedChurnRate != null : !this$predictedChurnRate.equals(other$predictedChurnRate)) return false;
        final java.lang.Object this$atRiskCustomers = this.getAtRiskCustomers();
        final java.lang.Object other$atRiskCustomers = other.getAtRiskCustomers();
        if (this$atRiskCustomers == null ? other$atRiskCustomers != null : !this$atRiskCustomers.equals(other$atRiskCustomers)) return false;
        final java.lang.Object this$churnFactors = this.getChurnFactors();
        final java.lang.Object other$churnFactors = other.getChurnFactors();
        if (this$churnFactors == null ? other$churnFactors != null : !this$churnFactors.equals(other$churnFactors)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ChurnPredictionResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getTotalCustomersAnalyzed();
        result = result * PRIME + this.getHighRiskCustomers();
        result = result * PRIME + this.getMediumRiskCustomers();
        result = result * PRIME + this.getLowRiskCustomers();
        final java.lang.Object $predictedChurnRate = this.getPredictedChurnRate();
        result = result * PRIME + ($predictedChurnRate == null ? 43 : $predictedChurnRate.hashCode());
        final java.lang.Object $atRiskCustomers = this.getAtRiskCustomers();
        result = result * PRIME + ($atRiskCustomers == null ? 43 : $atRiskCustomers.hashCode());
        final java.lang.Object $churnFactors = this.getChurnFactors();
        result = result * PRIME + ($churnFactors == null ? 43 : $churnFactors.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ChurnPredictionResponse(totalCustomersAnalyzed=" + this.getTotalCustomersAnalyzed() + ", highRiskCustomers=" + this.getHighRiskCustomers() + ", mediumRiskCustomers=" + this.getMediumRiskCustomers() + ", lowRiskCustomers=" + this.getLowRiskCustomers() + ", predictedChurnRate=" + this.getPredictedChurnRate() + ", atRiskCustomers=" + this.getAtRiskCustomers() + ", churnFactors=" + this.getChurnFactors() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public ChurnPredictionResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public ChurnPredictionResponse(final int totalCustomersAnalyzed, final int highRiskCustomers, final int mediumRiskCustomers, final int lowRiskCustomers, final BigDecimal predictedChurnRate, final List<ChurnRiskCustomer> atRiskCustomers, final List<ChurnFactor> churnFactors) {
        this.totalCustomersAnalyzed = totalCustomersAnalyzed;
        this.highRiskCustomers = highRiskCustomers;
        this.mediumRiskCustomers = mediumRiskCustomers;
        this.lowRiskCustomers = lowRiskCustomers;
        this.predictedChurnRate = predictedChurnRate;
        this.atRiskCustomers = atRiskCustomers;
        this.churnFactors = churnFactors;
    }
}
