// Generated by delombok at Wed Nov 26 14:14:06 IST 2025
package com.MaSoVa.analytics.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

public class CostAnalysisResponse {
    private String period; // "TODAY", "WEEK", "MONTH"
    private BigDecimal totalRevenue; // INR
    private BigDecimal totalCosts; // INR
    private BigDecimal totalProfit; // INR
    private BigDecimal profitMargin; // Percentage
    private CostBreakdown costBreakdown;
    private List<IngredientCost> ingredientCosts;
    private List<WasteCost> wasteCosts;
    private List<OrderCostAnalysis> topCostOrders;
    private List<SupplierComparison> supplierComparisons;


    public static class CostBreakdown {
        private BigDecimal ingredientCosts; // INR
        private BigDecimal wasteCosts; // INR
        private BigDecimal laborCosts; // INR
        private BigDecimal overheadCosts; // INR
        private BigDecimal deliveryCosts; // INR
        private BigDecimal otherCosts; // INR


        @java.lang.SuppressWarnings("all")
        public static class CostBreakdownBuilder {
            @java.lang.SuppressWarnings("all")
            private BigDecimal ingredientCosts;
            @java.lang.SuppressWarnings("all")
            private BigDecimal wasteCosts;
            @java.lang.SuppressWarnings("all")
            private BigDecimal laborCosts;
            @java.lang.SuppressWarnings("all")
            private BigDecimal overheadCosts;
            @java.lang.SuppressWarnings("all")
            private BigDecimal deliveryCosts;
            @java.lang.SuppressWarnings("all")
            private BigDecimal otherCosts;

            @java.lang.SuppressWarnings("all")
            CostBreakdownBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.CostBreakdown.CostBreakdownBuilder ingredientCosts(final BigDecimal ingredientCosts) {
                this.ingredientCosts = ingredientCosts;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.CostBreakdown.CostBreakdownBuilder wasteCosts(final BigDecimal wasteCosts) {
                this.wasteCosts = wasteCosts;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.CostBreakdown.CostBreakdownBuilder laborCosts(final BigDecimal laborCosts) {
                this.laborCosts = laborCosts;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.CostBreakdown.CostBreakdownBuilder overheadCosts(final BigDecimal overheadCosts) {
                this.overheadCosts = overheadCosts;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.CostBreakdown.CostBreakdownBuilder deliveryCosts(final BigDecimal deliveryCosts) {
                this.deliveryCosts = deliveryCosts;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.CostBreakdown.CostBreakdownBuilder otherCosts(final BigDecimal otherCosts) {
                this.otherCosts = otherCosts;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.CostBreakdown build() {
                return new CostAnalysisResponse.CostBreakdown(this.ingredientCosts, this.wasteCosts, this.laborCosts, this.overheadCosts, this.deliveryCosts, this.otherCosts);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "CostAnalysisResponse.CostBreakdown.CostBreakdownBuilder(ingredientCosts=" + this.ingredientCosts + ", wasteCosts=" + this.wasteCosts + ", laborCosts=" + this.laborCosts + ", overheadCosts=" + this.overheadCosts + ", deliveryCosts=" + this.deliveryCosts + ", otherCosts=" + this.otherCosts + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static CostAnalysisResponse.CostBreakdown.CostBreakdownBuilder builder() {
            return new CostAnalysisResponse.CostBreakdown.CostBreakdownBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getIngredientCosts() {
            return this.ingredientCosts;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getWasteCosts() {
            return this.wasteCosts;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getLaborCosts() {
            return this.laborCosts;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getOverheadCosts() {
            return this.overheadCosts;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getDeliveryCosts() {
            return this.deliveryCosts;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getOtherCosts() {
            return this.otherCosts;
        }

        @java.lang.SuppressWarnings("all")
        public void setIngredientCosts(final BigDecimal ingredientCosts) {
            this.ingredientCosts = ingredientCosts;
        }

        @java.lang.SuppressWarnings("all")
        public void setWasteCosts(final BigDecimal wasteCosts) {
            this.wasteCosts = wasteCosts;
        }

        @java.lang.SuppressWarnings("all")
        public void setLaborCosts(final BigDecimal laborCosts) {
            this.laborCosts = laborCosts;
        }

        @java.lang.SuppressWarnings("all")
        public void setOverheadCosts(final BigDecimal overheadCosts) {
            this.overheadCosts = overheadCosts;
        }

        @java.lang.SuppressWarnings("all")
        public void setDeliveryCosts(final BigDecimal deliveryCosts) {
            this.deliveryCosts = deliveryCosts;
        }

        @java.lang.SuppressWarnings("all")
        public void setOtherCosts(final BigDecimal otherCosts) {
            this.otherCosts = otherCosts;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof CostAnalysisResponse.CostBreakdown)) return false;
            final CostAnalysisResponse.CostBreakdown other = (CostAnalysisResponse.CostBreakdown) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$ingredientCosts = this.getIngredientCosts();
            final java.lang.Object other$ingredientCosts = other.getIngredientCosts();
            if (this$ingredientCosts == null ? other$ingredientCosts != null : !this$ingredientCosts.equals(other$ingredientCosts)) return false;
            final java.lang.Object this$wasteCosts = this.getWasteCosts();
            final java.lang.Object other$wasteCosts = other.getWasteCosts();
            if (this$wasteCosts == null ? other$wasteCosts != null : !this$wasteCosts.equals(other$wasteCosts)) return false;
            final java.lang.Object this$laborCosts = this.getLaborCosts();
            final java.lang.Object other$laborCosts = other.getLaborCosts();
            if (this$laborCosts == null ? other$laborCosts != null : !this$laborCosts.equals(other$laborCosts)) return false;
            final java.lang.Object this$overheadCosts = this.getOverheadCosts();
            final java.lang.Object other$overheadCosts = other.getOverheadCosts();
            if (this$overheadCosts == null ? other$overheadCosts != null : !this$overheadCosts.equals(other$overheadCosts)) return false;
            final java.lang.Object this$deliveryCosts = this.getDeliveryCosts();
            final java.lang.Object other$deliveryCosts = other.getDeliveryCosts();
            if (this$deliveryCosts == null ? other$deliveryCosts != null : !this$deliveryCosts.equals(other$deliveryCosts)) return false;
            final java.lang.Object this$otherCosts = this.getOtherCosts();
            final java.lang.Object other$otherCosts = other.getOtherCosts();
            if (this$otherCosts == null ? other$otherCosts != null : !this$otherCosts.equals(other$otherCosts)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof CostAnalysisResponse.CostBreakdown;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $ingredientCosts = this.getIngredientCosts();
            result = result * PRIME + ($ingredientCosts == null ? 43 : $ingredientCosts.hashCode());
            final java.lang.Object $wasteCosts = this.getWasteCosts();
            result = result * PRIME + ($wasteCosts == null ? 43 : $wasteCosts.hashCode());
            final java.lang.Object $laborCosts = this.getLaborCosts();
            result = result * PRIME + ($laborCosts == null ? 43 : $laborCosts.hashCode());
            final java.lang.Object $overheadCosts = this.getOverheadCosts();
            result = result * PRIME + ($overheadCosts == null ? 43 : $overheadCosts.hashCode());
            final java.lang.Object $deliveryCosts = this.getDeliveryCosts();
            result = result * PRIME + ($deliveryCosts == null ? 43 : $deliveryCosts.hashCode());
            final java.lang.Object $otherCosts = this.getOtherCosts();
            result = result * PRIME + ($otherCosts == null ? 43 : $otherCosts.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "CostAnalysisResponse.CostBreakdown(ingredientCosts=" + this.getIngredientCosts() + ", wasteCosts=" + this.getWasteCosts() + ", laborCosts=" + this.getLaborCosts() + ", overheadCosts=" + this.getOverheadCosts() + ", deliveryCosts=" + this.getDeliveryCosts() + ", otherCosts=" + this.getOtherCosts() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public CostBreakdown() {
        }

        @java.lang.SuppressWarnings("all")
        public CostBreakdown(final BigDecimal ingredientCosts, final BigDecimal wasteCosts, final BigDecimal laborCosts, final BigDecimal overheadCosts, final BigDecimal deliveryCosts, final BigDecimal otherCosts) {
            this.ingredientCosts = ingredientCosts;
            this.wasteCosts = wasteCosts;
            this.laborCosts = laborCosts;
            this.overheadCosts = overheadCosts;
            this.deliveryCosts = deliveryCosts;
            this.otherCosts = otherCosts;
        }
    }


    public static class IngredientCost {
        private String ingredientId;
        private String ingredientName;
        private BigDecimal quantityUsed;
        private String unit;
        private BigDecimal costPerUnit; // INR
        private BigDecimal totalCost; // INR
        private BigDecimal percentOfTotalCost;
        private String trend; // "UP", "DOWN", "STABLE"


        @java.lang.SuppressWarnings("all")
        public static class IngredientCostBuilder {
            @java.lang.SuppressWarnings("all")
            private String ingredientId;
            @java.lang.SuppressWarnings("all")
            private String ingredientName;
            @java.lang.SuppressWarnings("all")
            private BigDecimal quantityUsed;
            @java.lang.SuppressWarnings("all")
            private String unit;
            @java.lang.SuppressWarnings("all")
            private BigDecimal costPerUnit;
            @java.lang.SuppressWarnings("all")
            private BigDecimal totalCost;
            @java.lang.SuppressWarnings("all")
            private BigDecimal percentOfTotalCost;
            @java.lang.SuppressWarnings("all")
            private String trend;

            @java.lang.SuppressWarnings("all")
            IngredientCostBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.IngredientCost.IngredientCostBuilder ingredientId(final String ingredientId) {
                this.ingredientId = ingredientId;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.IngredientCost.IngredientCostBuilder ingredientName(final String ingredientName) {
                this.ingredientName = ingredientName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.IngredientCost.IngredientCostBuilder quantityUsed(final BigDecimal quantityUsed) {
                this.quantityUsed = quantityUsed;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.IngredientCost.IngredientCostBuilder unit(final String unit) {
                this.unit = unit;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.IngredientCost.IngredientCostBuilder costPerUnit(final BigDecimal costPerUnit) {
                this.costPerUnit = costPerUnit;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.IngredientCost.IngredientCostBuilder totalCost(final BigDecimal totalCost) {
                this.totalCost = totalCost;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.IngredientCost.IngredientCostBuilder percentOfTotalCost(final BigDecimal percentOfTotalCost) {
                this.percentOfTotalCost = percentOfTotalCost;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.IngredientCost.IngredientCostBuilder trend(final String trend) {
                this.trend = trend;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.IngredientCost build() {
                return new CostAnalysisResponse.IngredientCost(this.ingredientId, this.ingredientName, this.quantityUsed, this.unit, this.costPerUnit, this.totalCost, this.percentOfTotalCost, this.trend);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "CostAnalysisResponse.IngredientCost.IngredientCostBuilder(ingredientId=" + this.ingredientId + ", ingredientName=" + this.ingredientName + ", quantityUsed=" + this.quantityUsed + ", unit=" + this.unit + ", costPerUnit=" + this.costPerUnit + ", totalCost=" + this.totalCost + ", percentOfTotalCost=" + this.percentOfTotalCost + ", trend=" + this.trend + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static CostAnalysisResponse.IngredientCost.IngredientCostBuilder builder() {
            return new CostAnalysisResponse.IngredientCost.IngredientCostBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getIngredientId() {
            return this.ingredientId;
        }

        @java.lang.SuppressWarnings("all")
        public String getIngredientName() {
            return this.ingredientName;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getQuantityUsed() {
            return this.quantityUsed;
        }

        @java.lang.SuppressWarnings("all")
        public String getUnit() {
            return this.unit;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getCostPerUnit() {
            return this.costPerUnit;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getTotalCost() {
            return this.totalCost;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getPercentOfTotalCost() {
            return this.percentOfTotalCost;
        }

        @java.lang.SuppressWarnings("all")
        public String getTrend() {
            return this.trend;
        }

        @java.lang.SuppressWarnings("all")
        public void setIngredientId(final String ingredientId) {
            this.ingredientId = ingredientId;
        }

        @java.lang.SuppressWarnings("all")
        public void setIngredientName(final String ingredientName) {
            this.ingredientName = ingredientName;
        }

        @java.lang.SuppressWarnings("all")
        public void setQuantityUsed(final BigDecimal quantityUsed) {
            this.quantityUsed = quantityUsed;
        }

        @java.lang.SuppressWarnings("all")
        public void setUnit(final String unit) {
            this.unit = unit;
        }

        @java.lang.SuppressWarnings("all")
        public void setCostPerUnit(final BigDecimal costPerUnit) {
            this.costPerUnit = costPerUnit;
        }

        @java.lang.SuppressWarnings("all")
        public void setTotalCost(final BigDecimal totalCost) {
            this.totalCost = totalCost;
        }

        @java.lang.SuppressWarnings("all")
        public void setPercentOfTotalCost(final BigDecimal percentOfTotalCost) {
            this.percentOfTotalCost = percentOfTotalCost;
        }

        @java.lang.SuppressWarnings("all")
        public void setTrend(final String trend) {
            this.trend = trend;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof CostAnalysisResponse.IngredientCost)) return false;
            final CostAnalysisResponse.IngredientCost other = (CostAnalysisResponse.IngredientCost) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$ingredientId = this.getIngredientId();
            final java.lang.Object other$ingredientId = other.getIngredientId();
            if (this$ingredientId == null ? other$ingredientId != null : !this$ingredientId.equals(other$ingredientId)) return false;
            final java.lang.Object this$ingredientName = this.getIngredientName();
            final java.lang.Object other$ingredientName = other.getIngredientName();
            if (this$ingredientName == null ? other$ingredientName != null : !this$ingredientName.equals(other$ingredientName)) return false;
            final java.lang.Object this$quantityUsed = this.getQuantityUsed();
            final java.lang.Object other$quantityUsed = other.getQuantityUsed();
            if (this$quantityUsed == null ? other$quantityUsed != null : !this$quantityUsed.equals(other$quantityUsed)) return false;
            final java.lang.Object this$unit = this.getUnit();
            final java.lang.Object other$unit = other.getUnit();
            if (this$unit == null ? other$unit != null : !this$unit.equals(other$unit)) return false;
            final java.lang.Object this$costPerUnit = this.getCostPerUnit();
            final java.lang.Object other$costPerUnit = other.getCostPerUnit();
            if (this$costPerUnit == null ? other$costPerUnit != null : !this$costPerUnit.equals(other$costPerUnit)) return false;
            final java.lang.Object this$totalCost = this.getTotalCost();
            final java.lang.Object other$totalCost = other.getTotalCost();
            if (this$totalCost == null ? other$totalCost != null : !this$totalCost.equals(other$totalCost)) return false;
            final java.lang.Object this$percentOfTotalCost = this.getPercentOfTotalCost();
            final java.lang.Object other$percentOfTotalCost = other.getPercentOfTotalCost();
            if (this$percentOfTotalCost == null ? other$percentOfTotalCost != null : !this$percentOfTotalCost.equals(other$percentOfTotalCost)) return false;
            final java.lang.Object this$trend = this.getTrend();
            final java.lang.Object other$trend = other.getTrend();
            if (this$trend == null ? other$trend != null : !this$trend.equals(other$trend)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof CostAnalysisResponse.IngredientCost;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $ingredientId = this.getIngredientId();
            result = result * PRIME + ($ingredientId == null ? 43 : $ingredientId.hashCode());
            final java.lang.Object $ingredientName = this.getIngredientName();
            result = result * PRIME + ($ingredientName == null ? 43 : $ingredientName.hashCode());
            final java.lang.Object $quantityUsed = this.getQuantityUsed();
            result = result * PRIME + ($quantityUsed == null ? 43 : $quantityUsed.hashCode());
            final java.lang.Object $unit = this.getUnit();
            result = result * PRIME + ($unit == null ? 43 : $unit.hashCode());
            final java.lang.Object $costPerUnit = this.getCostPerUnit();
            result = result * PRIME + ($costPerUnit == null ? 43 : $costPerUnit.hashCode());
            final java.lang.Object $totalCost = this.getTotalCost();
            result = result * PRIME + ($totalCost == null ? 43 : $totalCost.hashCode());
            final java.lang.Object $percentOfTotalCost = this.getPercentOfTotalCost();
            result = result * PRIME + ($percentOfTotalCost == null ? 43 : $percentOfTotalCost.hashCode());
            final java.lang.Object $trend = this.getTrend();
            result = result * PRIME + ($trend == null ? 43 : $trend.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "CostAnalysisResponse.IngredientCost(ingredientId=" + this.getIngredientId() + ", ingredientName=" + this.getIngredientName() + ", quantityUsed=" + this.getQuantityUsed() + ", unit=" + this.getUnit() + ", costPerUnit=" + this.getCostPerUnit() + ", totalCost=" + this.getTotalCost() + ", percentOfTotalCost=" + this.getPercentOfTotalCost() + ", trend=" + this.getTrend() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public IngredientCost() {
        }

        @java.lang.SuppressWarnings("all")
        public IngredientCost(final String ingredientId, final String ingredientName, final BigDecimal quantityUsed, final String unit, final BigDecimal costPerUnit, final BigDecimal totalCost, final BigDecimal percentOfTotalCost, final String trend) {
            this.ingredientId = ingredientId;
            this.ingredientName = ingredientName;
            this.quantityUsed = quantityUsed;
            this.unit = unit;
            this.costPerUnit = costPerUnit;
            this.totalCost = totalCost;
            this.percentOfTotalCost = percentOfTotalCost;
            this.trend = trend;
        }
    }


    public static class WasteCost {
        private String itemName;
        private BigDecimal quantityWasted;
        private String unit;
        private BigDecimal estimatedCost; // INR
        private String reason; // "Expired", "Spoiled", "Over-prepared", "Quality Issue"
        private LocalDate date;


        @java.lang.SuppressWarnings("all")
        public static class WasteCostBuilder {
            @java.lang.SuppressWarnings("all")
            private String itemName;
            @java.lang.SuppressWarnings("all")
            private BigDecimal quantityWasted;
            @java.lang.SuppressWarnings("all")
            private String unit;
            @java.lang.SuppressWarnings("all")
            private BigDecimal estimatedCost;
            @java.lang.SuppressWarnings("all")
            private String reason;
            @java.lang.SuppressWarnings("all")
            private LocalDate date;

            @java.lang.SuppressWarnings("all")
            WasteCostBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.WasteCost.WasteCostBuilder itemName(final String itemName) {
                this.itemName = itemName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.WasteCost.WasteCostBuilder quantityWasted(final BigDecimal quantityWasted) {
                this.quantityWasted = quantityWasted;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.WasteCost.WasteCostBuilder unit(final String unit) {
                this.unit = unit;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.WasteCost.WasteCostBuilder estimatedCost(final BigDecimal estimatedCost) {
                this.estimatedCost = estimatedCost;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.WasteCost.WasteCostBuilder reason(final String reason) {
                this.reason = reason;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.WasteCost.WasteCostBuilder date(final LocalDate date) {
                this.date = date;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.WasteCost build() {
                return new CostAnalysisResponse.WasteCost(this.itemName, this.quantityWasted, this.unit, this.estimatedCost, this.reason, this.date);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "CostAnalysisResponse.WasteCost.WasteCostBuilder(itemName=" + this.itemName + ", quantityWasted=" + this.quantityWasted + ", unit=" + this.unit + ", estimatedCost=" + this.estimatedCost + ", reason=" + this.reason + ", date=" + this.date + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static CostAnalysisResponse.WasteCost.WasteCostBuilder builder() {
            return new CostAnalysisResponse.WasteCost.WasteCostBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getItemName() {
            return this.itemName;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getQuantityWasted() {
            return this.quantityWasted;
        }

        @java.lang.SuppressWarnings("all")
        public String getUnit() {
            return this.unit;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getEstimatedCost() {
            return this.estimatedCost;
        }

        @java.lang.SuppressWarnings("all")
        public String getReason() {
            return this.reason;
        }

        @java.lang.SuppressWarnings("all")
        public LocalDate getDate() {
            return this.date;
        }

        @java.lang.SuppressWarnings("all")
        public void setItemName(final String itemName) {
            this.itemName = itemName;
        }

        @java.lang.SuppressWarnings("all")
        public void setQuantityWasted(final BigDecimal quantityWasted) {
            this.quantityWasted = quantityWasted;
        }

        @java.lang.SuppressWarnings("all")
        public void setUnit(final String unit) {
            this.unit = unit;
        }

        @java.lang.SuppressWarnings("all")
        public void setEstimatedCost(final BigDecimal estimatedCost) {
            this.estimatedCost = estimatedCost;
        }

        @java.lang.SuppressWarnings("all")
        public void setReason(final String reason) {
            this.reason = reason;
        }

        @java.lang.SuppressWarnings("all")
        public void setDate(final LocalDate date) {
            this.date = date;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof CostAnalysisResponse.WasteCost)) return false;
            final CostAnalysisResponse.WasteCost other = (CostAnalysisResponse.WasteCost) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$itemName = this.getItemName();
            final java.lang.Object other$itemName = other.getItemName();
            if (this$itemName == null ? other$itemName != null : !this$itemName.equals(other$itemName)) return false;
            final java.lang.Object this$quantityWasted = this.getQuantityWasted();
            final java.lang.Object other$quantityWasted = other.getQuantityWasted();
            if (this$quantityWasted == null ? other$quantityWasted != null : !this$quantityWasted.equals(other$quantityWasted)) return false;
            final java.lang.Object this$unit = this.getUnit();
            final java.lang.Object other$unit = other.getUnit();
            if (this$unit == null ? other$unit != null : !this$unit.equals(other$unit)) return false;
            final java.lang.Object this$estimatedCost = this.getEstimatedCost();
            final java.lang.Object other$estimatedCost = other.getEstimatedCost();
            if (this$estimatedCost == null ? other$estimatedCost != null : !this$estimatedCost.equals(other$estimatedCost)) return false;
            final java.lang.Object this$reason = this.getReason();
            final java.lang.Object other$reason = other.getReason();
            if (this$reason == null ? other$reason != null : !this$reason.equals(other$reason)) return false;
            final java.lang.Object this$date = this.getDate();
            final java.lang.Object other$date = other.getDate();
            if (this$date == null ? other$date != null : !this$date.equals(other$date)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof CostAnalysisResponse.WasteCost;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $itemName = this.getItemName();
            result = result * PRIME + ($itemName == null ? 43 : $itemName.hashCode());
            final java.lang.Object $quantityWasted = this.getQuantityWasted();
            result = result * PRIME + ($quantityWasted == null ? 43 : $quantityWasted.hashCode());
            final java.lang.Object $unit = this.getUnit();
            result = result * PRIME + ($unit == null ? 43 : $unit.hashCode());
            final java.lang.Object $estimatedCost = this.getEstimatedCost();
            result = result * PRIME + ($estimatedCost == null ? 43 : $estimatedCost.hashCode());
            final java.lang.Object $reason = this.getReason();
            result = result * PRIME + ($reason == null ? 43 : $reason.hashCode());
            final java.lang.Object $date = this.getDate();
            result = result * PRIME + ($date == null ? 43 : $date.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "CostAnalysisResponse.WasteCost(itemName=" + this.getItemName() + ", quantityWasted=" + this.getQuantityWasted() + ", unit=" + this.getUnit() + ", estimatedCost=" + this.getEstimatedCost() + ", reason=" + this.getReason() + ", date=" + this.getDate() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public WasteCost() {
        }

        @java.lang.SuppressWarnings("all")
        public WasteCost(final String itemName, final BigDecimal quantityWasted, final String unit, final BigDecimal estimatedCost, final String reason, final LocalDate date) {
            this.itemName = itemName;
            this.quantityWasted = quantityWasted;
            this.unit = unit;
            this.estimatedCost = estimatedCost;
            this.reason = reason;
            this.date = date;
        }
    }


    public static class OrderCostAnalysis {
        private String orderId;
        private BigDecimal revenue; // INR
        private BigDecimal cost; // INR
        private BigDecimal profit; // INR
        private BigDecimal profitMargin; // Percentage
        private int itemCount;


        @java.lang.SuppressWarnings("all")
        public static class OrderCostAnalysisBuilder {
            @java.lang.SuppressWarnings("all")
            private String orderId;
            @java.lang.SuppressWarnings("all")
            private BigDecimal revenue;
            @java.lang.SuppressWarnings("all")
            private BigDecimal cost;
            @java.lang.SuppressWarnings("all")
            private BigDecimal profit;
            @java.lang.SuppressWarnings("all")
            private BigDecimal profitMargin;
            @java.lang.SuppressWarnings("all")
            private int itemCount;

            @java.lang.SuppressWarnings("all")
            OrderCostAnalysisBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.OrderCostAnalysis.OrderCostAnalysisBuilder orderId(final String orderId) {
                this.orderId = orderId;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.OrderCostAnalysis.OrderCostAnalysisBuilder revenue(final BigDecimal revenue) {
                this.revenue = revenue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.OrderCostAnalysis.OrderCostAnalysisBuilder cost(final BigDecimal cost) {
                this.cost = cost;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.OrderCostAnalysis.OrderCostAnalysisBuilder profit(final BigDecimal profit) {
                this.profit = profit;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.OrderCostAnalysis.OrderCostAnalysisBuilder profitMargin(final BigDecimal profitMargin) {
                this.profitMargin = profitMargin;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.OrderCostAnalysis.OrderCostAnalysisBuilder itemCount(final int itemCount) {
                this.itemCount = itemCount;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.OrderCostAnalysis build() {
                return new CostAnalysisResponse.OrderCostAnalysis(this.orderId, this.revenue, this.cost, this.profit, this.profitMargin, this.itemCount);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "CostAnalysisResponse.OrderCostAnalysis.OrderCostAnalysisBuilder(orderId=" + this.orderId + ", revenue=" + this.revenue + ", cost=" + this.cost + ", profit=" + this.profit + ", profitMargin=" + this.profitMargin + ", itemCount=" + this.itemCount + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static CostAnalysisResponse.OrderCostAnalysis.OrderCostAnalysisBuilder builder() {
            return new CostAnalysisResponse.OrderCostAnalysis.OrderCostAnalysisBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getOrderId() {
            return this.orderId;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getRevenue() {
            return this.revenue;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getCost() {
            return this.cost;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getProfit() {
            return this.profit;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getProfitMargin() {
            return this.profitMargin;
        }

        @java.lang.SuppressWarnings("all")
        public int getItemCount() {
            return this.itemCount;
        }

        @java.lang.SuppressWarnings("all")
        public void setOrderId(final String orderId) {
            this.orderId = orderId;
        }

        @java.lang.SuppressWarnings("all")
        public void setRevenue(final BigDecimal revenue) {
            this.revenue = revenue;
        }

        @java.lang.SuppressWarnings("all")
        public void setCost(final BigDecimal cost) {
            this.cost = cost;
        }

        @java.lang.SuppressWarnings("all")
        public void setProfit(final BigDecimal profit) {
            this.profit = profit;
        }

        @java.lang.SuppressWarnings("all")
        public void setProfitMargin(final BigDecimal profitMargin) {
            this.profitMargin = profitMargin;
        }

        @java.lang.SuppressWarnings("all")
        public void setItemCount(final int itemCount) {
            this.itemCount = itemCount;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof CostAnalysisResponse.OrderCostAnalysis)) return false;
            final CostAnalysisResponse.OrderCostAnalysis other = (CostAnalysisResponse.OrderCostAnalysis) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getItemCount() != other.getItemCount()) return false;
            final java.lang.Object this$orderId = this.getOrderId();
            final java.lang.Object other$orderId = other.getOrderId();
            if (this$orderId == null ? other$orderId != null : !this$orderId.equals(other$orderId)) return false;
            final java.lang.Object this$revenue = this.getRevenue();
            final java.lang.Object other$revenue = other.getRevenue();
            if (this$revenue == null ? other$revenue != null : !this$revenue.equals(other$revenue)) return false;
            final java.lang.Object this$cost = this.getCost();
            final java.lang.Object other$cost = other.getCost();
            if (this$cost == null ? other$cost != null : !this$cost.equals(other$cost)) return false;
            final java.lang.Object this$profit = this.getProfit();
            final java.lang.Object other$profit = other.getProfit();
            if (this$profit == null ? other$profit != null : !this$profit.equals(other$profit)) return false;
            final java.lang.Object this$profitMargin = this.getProfitMargin();
            final java.lang.Object other$profitMargin = other.getProfitMargin();
            if (this$profitMargin == null ? other$profitMargin != null : !this$profitMargin.equals(other$profitMargin)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof CostAnalysisResponse.OrderCostAnalysis;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getItemCount();
            final java.lang.Object $orderId = this.getOrderId();
            result = result * PRIME + ($orderId == null ? 43 : $orderId.hashCode());
            final java.lang.Object $revenue = this.getRevenue();
            result = result * PRIME + ($revenue == null ? 43 : $revenue.hashCode());
            final java.lang.Object $cost = this.getCost();
            result = result * PRIME + ($cost == null ? 43 : $cost.hashCode());
            final java.lang.Object $profit = this.getProfit();
            result = result * PRIME + ($profit == null ? 43 : $profit.hashCode());
            final java.lang.Object $profitMargin = this.getProfitMargin();
            result = result * PRIME + ($profitMargin == null ? 43 : $profitMargin.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "CostAnalysisResponse.OrderCostAnalysis(orderId=" + this.getOrderId() + ", revenue=" + this.getRevenue() + ", cost=" + this.getCost() + ", profit=" + this.getProfit() + ", profitMargin=" + this.getProfitMargin() + ", itemCount=" + this.getItemCount() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public OrderCostAnalysis() {
        }

        @java.lang.SuppressWarnings("all")
        public OrderCostAnalysis(final String orderId, final BigDecimal revenue, final BigDecimal cost, final BigDecimal profit, final BigDecimal profitMargin, final int itemCount) {
            this.orderId = orderId;
            this.revenue = revenue;
            this.cost = cost;
            this.profit = profit;
            this.profitMargin = profitMargin;
            this.itemCount = itemCount;
        }
    }


    public static class SupplierComparison {
        private String ingredientName;
        private List<SupplierPrice> suppliers;
        private String recommendedSupplier;
        private BigDecimal potentialSavings; // INR per month


        @java.lang.SuppressWarnings("all")
        public static class SupplierComparisonBuilder {
            @java.lang.SuppressWarnings("all")
            private String ingredientName;
            @java.lang.SuppressWarnings("all")
            private List<SupplierPrice> suppliers;
            @java.lang.SuppressWarnings("all")
            private String recommendedSupplier;
            @java.lang.SuppressWarnings("all")
            private BigDecimal potentialSavings;

            @java.lang.SuppressWarnings("all")
            SupplierComparisonBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierComparison.SupplierComparisonBuilder ingredientName(final String ingredientName) {
                this.ingredientName = ingredientName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierComparison.SupplierComparisonBuilder suppliers(final List<SupplierPrice> suppliers) {
                this.suppliers = suppliers;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierComparison.SupplierComparisonBuilder recommendedSupplier(final String recommendedSupplier) {
                this.recommendedSupplier = recommendedSupplier;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierComparison.SupplierComparisonBuilder potentialSavings(final BigDecimal potentialSavings) {
                this.potentialSavings = potentialSavings;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierComparison build() {
                return new CostAnalysisResponse.SupplierComparison(this.ingredientName, this.suppliers, this.recommendedSupplier, this.potentialSavings);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "CostAnalysisResponse.SupplierComparison.SupplierComparisonBuilder(ingredientName=" + this.ingredientName + ", suppliers=" + this.suppliers + ", recommendedSupplier=" + this.recommendedSupplier + ", potentialSavings=" + this.potentialSavings + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static CostAnalysisResponse.SupplierComparison.SupplierComparisonBuilder builder() {
            return new CostAnalysisResponse.SupplierComparison.SupplierComparisonBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getIngredientName() {
            return this.ingredientName;
        }

        @java.lang.SuppressWarnings("all")
        public List<SupplierPrice> getSuppliers() {
            return this.suppliers;
        }

        @java.lang.SuppressWarnings("all")
        public String getRecommendedSupplier() {
            return this.recommendedSupplier;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getPotentialSavings() {
            return this.potentialSavings;
        }

        @java.lang.SuppressWarnings("all")
        public void setIngredientName(final String ingredientName) {
            this.ingredientName = ingredientName;
        }

        @java.lang.SuppressWarnings("all")
        public void setSuppliers(final List<SupplierPrice> suppliers) {
            this.suppliers = suppliers;
        }

        @java.lang.SuppressWarnings("all")
        public void setRecommendedSupplier(final String recommendedSupplier) {
            this.recommendedSupplier = recommendedSupplier;
        }

        @java.lang.SuppressWarnings("all")
        public void setPotentialSavings(final BigDecimal potentialSavings) {
            this.potentialSavings = potentialSavings;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof CostAnalysisResponse.SupplierComparison)) return false;
            final CostAnalysisResponse.SupplierComparison other = (CostAnalysisResponse.SupplierComparison) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$ingredientName = this.getIngredientName();
            final java.lang.Object other$ingredientName = other.getIngredientName();
            if (this$ingredientName == null ? other$ingredientName != null : !this$ingredientName.equals(other$ingredientName)) return false;
            final java.lang.Object this$suppliers = this.getSuppliers();
            final java.lang.Object other$suppliers = other.getSuppliers();
            if (this$suppliers == null ? other$suppliers != null : !this$suppliers.equals(other$suppliers)) return false;
            final java.lang.Object this$recommendedSupplier = this.getRecommendedSupplier();
            final java.lang.Object other$recommendedSupplier = other.getRecommendedSupplier();
            if (this$recommendedSupplier == null ? other$recommendedSupplier != null : !this$recommendedSupplier.equals(other$recommendedSupplier)) return false;
            final java.lang.Object this$potentialSavings = this.getPotentialSavings();
            final java.lang.Object other$potentialSavings = other.getPotentialSavings();
            if (this$potentialSavings == null ? other$potentialSavings != null : !this$potentialSavings.equals(other$potentialSavings)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof CostAnalysisResponse.SupplierComparison;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $ingredientName = this.getIngredientName();
            result = result * PRIME + ($ingredientName == null ? 43 : $ingredientName.hashCode());
            final java.lang.Object $suppliers = this.getSuppliers();
            result = result * PRIME + ($suppliers == null ? 43 : $suppliers.hashCode());
            final java.lang.Object $recommendedSupplier = this.getRecommendedSupplier();
            result = result * PRIME + ($recommendedSupplier == null ? 43 : $recommendedSupplier.hashCode());
            final java.lang.Object $potentialSavings = this.getPotentialSavings();
            result = result * PRIME + ($potentialSavings == null ? 43 : $potentialSavings.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "CostAnalysisResponse.SupplierComparison(ingredientName=" + this.getIngredientName() + ", suppliers=" + this.getSuppliers() + ", recommendedSupplier=" + this.getRecommendedSupplier() + ", potentialSavings=" + this.getPotentialSavings() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public SupplierComparison() {
        }

        @java.lang.SuppressWarnings("all")
        public SupplierComparison(final String ingredientName, final List<SupplierPrice> suppliers, final String recommendedSupplier, final BigDecimal potentialSavings) {
            this.ingredientName = ingredientName;
            this.suppliers = suppliers;
            this.recommendedSupplier = recommendedSupplier;
            this.potentialSavings = potentialSavings;
        }
    }


    public static class SupplierPrice {
        private String supplierId;
        private String supplierName;
        private BigDecimal pricePerUnit; // INR
        private String unit;
        private String quality; // "Premium", "Standard", "Budget"
        private int deliveryDays;


        @java.lang.SuppressWarnings("all")
        public static class SupplierPriceBuilder {
            @java.lang.SuppressWarnings("all")
            private String supplierId;
            @java.lang.SuppressWarnings("all")
            private String supplierName;
            @java.lang.SuppressWarnings("all")
            private BigDecimal pricePerUnit;
            @java.lang.SuppressWarnings("all")
            private String unit;
            @java.lang.SuppressWarnings("all")
            private String quality;
            @java.lang.SuppressWarnings("all")
            private int deliveryDays;

            @java.lang.SuppressWarnings("all")
            SupplierPriceBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierPrice.SupplierPriceBuilder supplierId(final String supplierId) {
                this.supplierId = supplierId;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierPrice.SupplierPriceBuilder supplierName(final String supplierName) {
                this.supplierName = supplierName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierPrice.SupplierPriceBuilder pricePerUnit(final BigDecimal pricePerUnit) {
                this.pricePerUnit = pricePerUnit;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierPrice.SupplierPriceBuilder unit(final String unit) {
                this.unit = unit;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierPrice.SupplierPriceBuilder quality(final String quality) {
                this.quality = quality;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierPrice.SupplierPriceBuilder deliveryDays(final int deliveryDays) {
                this.deliveryDays = deliveryDays;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public CostAnalysisResponse.SupplierPrice build() {
                return new CostAnalysisResponse.SupplierPrice(this.supplierId, this.supplierName, this.pricePerUnit, this.unit, this.quality, this.deliveryDays);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "CostAnalysisResponse.SupplierPrice.SupplierPriceBuilder(supplierId=" + this.supplierId + ", supplierName=" + this.supplierName + ", pricePerUnit=" + this.pricePerUnit + ", unit=" + this.unit + ", quality=" + this.quality + ", deliveryDays=" + this.deliveryDays + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static CostAnalysisResponse.SupplierPrice.SupplierPriceBuilder builder() {
            return new CostAnalysisResponse.SupplierPrice.SupplierPriceBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getSupplierId() {
            return this.supplierId;
        }

        @java.lang.SuppressWarnings("all")
        public String getSupplierName() {
            return this.supplierName;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getPricePerUnit() {
            return this.pricePerUnit;
        }

        @java.lang.SuppressWarnings("all")
        public String getUnit() {
            return this.unit;
        }

        @java.lang.SuppressWarnings("all")
        public String getQuality() {
            return this.quality;
        }

        @java.lang.SuppressWarnings("all")
        public int getDeliveryDays() {
            return this.deliveryDays;
        }

        @java.lang.SuppressWarnings("all")
        public void setSupplierId(final String supplierId) {
            this.supplierId = supplierId;
        }

        @java.lang.SuppressWarnings("all")
        public void setSupplierName(final String supplierName) {
            this.supplierName = supplierName;
        }

        @java.lang.SuppressWarnings("all")
        public void setPricePerUnit(final BigDecimal pricePerUnit) {
            this.pricePerUnit = pricePerUnit;
        }

        @java.lang.SuppressWarnings("all")
        public void setUnit(final String unit) {
            this.unit = unit;
        }

        @java.lang.SuppressWarnings("all")
        public void setQuality(final String quality) {
            this.quality = quality;
        }

        @java.lang.SuppressWarnings("all")
        public void setDeliveryDays(final int deliveryDays) {
            this.deliveryDays = deliveryDays;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof CostAnalysisResponse.SupplierPrice)) return false;
            final CostAnalysisResponse.SupplierPrice other = (CostAnalysisResponse.SupplierPrice) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getDeliveryDays() != other.getDeliveryDays()) return false;
            final java.lang.Object this$supplierId = this.getSupplierId();
            final java.lang.Object other$supplierId = other.getSupplierId();
            if (this$supplierId == null ? other$supplierId != null : !this$supplierId.equals(other$supplierId)) return false;
            final java.lang.Object this$supplierName = this.getSupplierName();
            final java.lang.Object other$supplierName = other.getSupplierName();
            if (this$supplierName == null ? other$supplierName != null : !this$supplierName.equals(other$supplierName)) return false;
            final java.lang.Object this$pricePerUnit = this.getPricePerUnit();
            final java.lang.Object other$pricePerUnit = other.getPricePerUnit();
            if (this$pricePerUnit == null ? other$pricePerUnit != null : !this$pricePerUnit.equals(other$pricePerUnit)) return false;
            final java.lang.Object this$unit = this.getUnit();
            final java.lang.Object other$unit = other.getUnit();
            if (this$unit == null ? other$unit != null : !this$unit.equals(other$unit)) return false;
            final java.lang.Object this$quality = this.getQuality();
            final java.lang.Object other$quality = other.getQuality();
            if (this$quality == null ? other$quality != null : !this$quality.equals(other$quality)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof CostAnalysisResponse.SupplierPrice;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getDeliveryDays();
            final java.lang.Object $supplierId = this.getSupplierId();
            result = result * PRIME + ($supplierId == null ? 43 : $supplierId.hashCode());
            final java.lang.Object $supplierName = this.getSupplierName();
            result = result * PRIME + ($supplierName == null ? 43 : $supplierName.hashCode());
            final java.lang.Object $pricePerUnit = this.getPricePerUnit();
            result = result * PRIME + ($pricePerUnit == null ? 43 : $pricePerUnit.hashCode());
            final java.lang.Object $unit = this.getUnit();
            result = result * PRIME + ($unit == null ? 43 : $unit.hashCode());
            final java.lang.Object $quality = this.getQuality();
            result = result * PRIME + ($quality == null ? 43 : $quality.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "CostAnalysisResponse.SupplierPrice(supplierId=" + this.getSupplierId() + ", supplierName=" + this.getSupplierName() + ", pricePerUnit=" + this.getPricePerUnit() + ", unit=" + this.getUnit() + ", quality=" + this.getQuality() + ", deliveryDays=" + this.getDeliveryDays() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public SupplierPrice() {
        }

        @java.lang.SuppressWarnings("all")
        public SupplierPrice(final String supplierId, final String supplierName, final BigDecimal pricePerUnit, final String unit, final String quality, final int deliveryDays) {
            this.supplierId = supplierId;
            this.supplierName = supplierName;
            this.pricePerUnit = pricePerUnit;
            this.unit = unit;
            this.quality = quality;
            this.deliveryDays = deliveryDays;
        }
    }


    @java.lang.SuppressWarnings("all")
    public static class CostAnalysisResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private String period;
        @java.lang.SuppressWarnings("all")
        private BigDecimal totalRevenue;
        @java.lang.SuppressWarnings("all")
        private BigDecimal totalCosts;
        @java.lang.SuppressWarnings("all")
        private BigDecimal totalProfit;
        @java.lang.SuppressWarnings("all")
        private BigDecimal profitMargin;
        @java.lang.SuppressWarnings("all")
        private CostBreakdown costBreakdown;
        @java.lang.SuppressWarnings("all")
        private List<IngredientCost> ingredientCosts;
        @java.lang.SuppressWarnings("all")
        private List<WasteCost> wasteCosts;
        @java.lang.SuppressWarnings("all")
        private List<OrderCostAnalysis> topCostOrders;
        @java.lang.SuppressWarnings("all")
        private List<SupplierComparison> supplierComparisons;

        @java.lang.SuppressWarnings("all")
        CostAnalysisResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CostAnalysisResponse.CostAnalysisResponseBuilder period(final String period) {
            this.period = period;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CostAnalysisResponse.CostAnalysisResponseBuilder totalRevenue(final BigDecimal totalRevenue) {
            this.totalRevenue = totalRevenue;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CostAnalysisResponse.CostAnalysisResponseBuilder totalCosts(final BigDecimal totalCosts) {
            this.totalCosts = totalCosts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CostAnalysisResponse.CostAnalysisResponseBuilder totalProfit(final BigDecimal totalProfit) {
            this.totalProfit = totalProfit;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CostAnalysisResponse.CostAnalysisResponseBuilder profitMargin(final BigDecimal profitMargin) {
            this.profitMargin = profitMargin;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CostAnalysisResponse.CostAnalysisResponseBuilder costBreakdown(final CostBreakdown costBreakdown) {
            this.costBreakdown = costBreakdown;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CostAnalysisResponse.CostAnalysisResponseBuilder ingredientCosts(final List<IngredientCost> ingredientCosts) {
            this.ingredientCosts = ingredientCosts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CostAnalysisResponse.CostAnalysisResponseBuilder wasteCosts(final List<WasteCost> wasteCosts) {
            this.wasteCosts = wasteCosts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CostAnalysisResponse.CostAnalysisResponseBuilder topCostOrders(final List<OrderCostAnalysis> topCostOrders) {
            this.topCostOrders = topCostOrders;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CostAnalysisResponse.CostAnalysisResponseBuilder supplierComparisons(final List<SupplierComparison> supplierComparisons) {
            this.supplierComparisons = supplierComparisons;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public CostAnalysisResponse build() {
            return new CostAnalysisResponse(this.period, this.totalRevenue, this.totalCosts, this.totalProfit, this.profitMargin, this.costBreakdown, this.ingredientCosts, this.wasteCosts, this.topCostOrders, this.supplierComparisons);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "CostAnalysisResponse.CostAnalysisResponseBuilder(period=" + this.period + ", totalRevenue=" + this.totalRevenue + ", totalCosts=" + this.totalCosts + ", totalProfit=" + this.totalProfit + ", profitMargin=" + this.profitMargin + ", costBreakdown=" + this.costBreakdown + ", ingredientCosts=" + this.ingredientCosts + ", wasteCosts=" + this.wasteCosts + ", topCostOrders=" + this.topCostOrders + ", supplierComparisons=" + this.supplierComparisons + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static CostAnalysisResponse.CostAnalysisResponseBuilder builder() {
        return new CostAnalysisResponse.CostAnalysisResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getPeriod() {
        return this.period;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getTotalRevenue() {
        return this.totalRevenue;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getTotalCosts() {
        return this.totalCosts;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getTotalProfit() {
        return this.totalProfit;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getProfitMargin() {
        return this.profitMargin;
    }

    @java.lang.SuppressWarnings("all")
    public CostBreakdown getCostBreakdown() {
        return this.costBreakdown;
    }

    @java.lang.SuppressWarnings("all")
    public List<IngredientCost> getIngredientCosts() {
        return this.ingredientCosts;
    }

    @java.lang.SuppressWarnings("all")
    public List<WasteCost> getWasteCosts() {
        return this.wasteCosts;
    }

    @java.lang.SuppressWarnings("all")
    public List<OrderCostAnalysis> getTopCostOrders() {
        return this.topCostOrders;
    }

    @java.lang.SuppressWarnings("all")
    public List<SupplierComparison> getSupplierComparisons() {
        return this.supplierComparisons;
    }

    @java.lang.SuppressWarnings("all")
    public void setPeriod(final String period) {
        this.period = period;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalRevenue(final BigDecimal totalRevenue) {
        this.totalRevenue = totalRevenue;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalCosts(final BigDecimal totalCosts) {
        this.totalCosts = totalCosts;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalProfit(final BigDecimal totalProfit) {
        this.totalProfit = totalProfit;
    }

    @java.lang.SuppressWarnings("all")
    public void setProfitMargin(final BigDecimal profitMargin) {
        this.profitMargin = profitMargin;
    }

    @java.lang.SuppressWarnings("all")
    public void setCostBreakdown(final CostBreakdown costBreakdown) {
        this.costBreakdown = costBreakdown;
    }

    @java.lang.SuppressWarnings("all")
    public void setIngredientCosts(final List<IngredientCost> ingredientCosts) {
        this.ingredientCosts = ingredientCosts;
    }

    @java.lang.SuppressWarnings("all")
    public void setWasteCosts(final List<WasteCost> wasteCosts) {
        this.wasteCosts = wasteCosts;
    }

    @java.lang.SuppressWarnings("all")
    public void setTopCostOrders(final List<OrderCostAnalysis> topCostOrders) {
        this.topCostOrders = topCostOrders;
    }

    @java.lang.SuppressWarnings("all")
    public void setSupplierComparisons(final List<SupplierComparison> supplierComparisons) {
        this.supplierComparisons = supplierComparisons;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CostAnalysisResponse)) return false;
        final CostAnalysisResponse other = (CostAnalysisResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$period = this.getPeriod();
        final java.lang.Object other$period = other.getPeriod();
        if (this$period == null ? other$period != null : !this$period.equals(other$period)) return false;
        final java.lang.Object this$totalRevenue = this.getTotalRevenue();
        final java.lang.Object other$totalRevenue = other.getTotalRevenue();
        if (this$totalRevenue == null ? other$totalRevenue != null : !this$totalRevenue.equals(other$totalRevenue)) return false;
        final java.lang.Object this$totalCosts = this.getTotalCosts();
        final java.lang.Object other$totalCosts = other.getTotalCosts();
        if (this$totalCosts == null ? other$totalCosts != null : !this$totalCosts.equals(other$totalCosts)) return false;
        final java.lang.Object this$totalProfit = this.getTotalProfit();
        final java.lang.Object other$totalProfit = other.getTotalProfit();
        if (this$totalProfit == null ? other$totalProfit != null : !this$totalProfit.equals(other$totalProfit)) return false;
        final java.lang.Object this$profitMargin = this.getProfitMargin();
        final java.lang.Object other$profitMargin = other.getProfitMargin();
        if (this$profitMargin == null ? other$profitMargin != null : !this$profitMargin.equals(other$profitMargin)) return false;
        final java.lang.Object this$costBreakdown = this.getCostBreakdown();
        final java.lang.Object other$costBreakdown = other.getCostBreakdown();
        if (this$costBreakdown == null ? other$costBreakdown != null : !this$costBreakdown.equals(other$costBreakdown)) return false;
        final java.lang.Object this$ingredientCosts = this.getIngredientCosts();
        final java.lang.Object other$ingredientCosts = other.getIngredientCosts();
        if (this$ingredientCosts == null ? other$ingredientCosts != null : !this$ingredientCosts.equals(other$ingredientCosts)) return false;
        final java.lang.Object this$wasteCosts = this.getWasteCosts();
        final java.lang.Object other$wasteCosts = other.getWasteCosts();
        if (this$wasteCosts == null ? other$wasteCosts != null : !this$wasteCosts.equals(other$wasteCosts)) return false;
        final java.lang.Object this$topCostOrders = this.getTopCostOrders();
        final java.lang.Object other$topCostOrders = other.getTopCostOrders();
        if (this$topCostOrders == null ? other$topCostOrders != null : !this$topCostOrders.equals(other$topCostOrders)) return false;
        final java.lang.Object this$supplierComparisons = this.getSupplierComparisons();
        final java.lang.Object other$supplierComparisons = other.getSupplierComparisons();
        if (this$supplierComparisons == null ? other$supplierComparisons != null : !this$supplierComparisons.equals(other$supplierComparisons)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CostAnalysisResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $period = this.getPeriod();
        result = result * PRIME + ($period == null ? 43 : $period.hashCode());
        final java.lang.Object $totalRevenue = this.getTotalRevenue();
        result = result * PRIME + ($totalRevenue == null ? 43 : $totalRevenue.hashCode());
        final java.lang.Object $totalCosts = this.getTotalCosts();
        result = result * PRIME + ($totalCosts == null ? 43 : $totalCosts.hashCode());
        final java.lang.Object $totalProfit = this.getTotalProfit();
        result = result * PRIME + ($totalProfit == null ? 43 : $totalProfit.hashCode());
        final java.lang.Object $profitMargin = this.getProfitMargin();
        result = result * PRIME + ($profitMargin == null ? 43 : $profitMargin.hashCode());
        final java.lang.Object $costBreakdown = this.getCostBreakdown();
        result = result * PRIME + ($costBreakdown == null ? 43 : $costBreakdown.hashCode());
        final java.lang.Object $ingredientCosts = this.getIngredientCosts();
        result = result * PRIME + ($ingredientCosts == null ? 43 : $ingredientCosts.hashCode());
        final java.lang.Object $wasteCosts = this.getWasteCosts();
        result = result * PRIME + ($wasteCosts == null ? 43 : $wasteCosts.hashCode());
        final java.lang.Object $topCostOrders = this.getTopCostOrders();
        result = result * PRIME + ($topCostOrders == null ? 43 : $topCostOrders.hashCode());
        final java.lang.Object $supplierComparisons = this.getSupplierComparisons();
        result = result * PRIME + ($supplierComparisons == null ? 43 : $supplierComparisons.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "CostAnalysisResponse(period=" + this.getPeriod() + ", totalRevenue=" + this.getTotalRevenue() + ", totalCosts=" + this.getTotalCosts() + ", totalProfit=" + this.getTotalProfit() + ", profitMargin=" + this.getProfitMargin() + ", costBreakdown=" + this.getCostBreakdown() + ", ingredientCosts=" + this.getIngredientCosts() + ", wasteCosts=" + this.getWasteCosts() + ", topCostOrders=" + this.getTopCostOrders() + ", supplierComparisons=" + this.getSupplierComparisons() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public CostAnalysisResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public CostAnalysisResponse(final String period, final BigDecimal totalRevenue, final BigDecimal totalCosts, final BigDecimal totalProfit, final BigDecimal profitMargin, final CostBreakdown costBreakdown, final List<IngredientCost> ingredientCosts, final List<WasteCost> wasteCosts, final List<OrderCostAnalysis> topCostOrders, final List<SupplierComparison> supplierComparisons) {
        this.period = period;
        this.totalRevenue = totalRevenue;
        this.totalCosts = totalCosts;
        this.totalProfit = totalProfit;
        this.profitMargin = profitMargin;
        this.costBreakdown = costBreakdown;
        this.ingredientCosts = ingredientCosts;
        this.wasteCosts = wasteCosts;
        this.topCostOrders = topCostOrders;
        this.supplierComparisons = supplierComparisons;
    }
}
