// Generated by delombok at Wed Nov 26 14:14:06 IST 2025
package com.MaSoVa.analytics.dto;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public class CustomerBehaviorResponse {
    private int totalCustomers;
    private int activeCustomers; // Ordered in last 30 days
    private int newCustomers; // Registered in last 30 days
    private BigDecimal averageLifetimeValue;
    private BigDecimal averageOrderFrequency; // Orders per month
    private List<CustomerSegment> segments;
    private List<BehaviorPattern> patterns;


    public static class CustomerSegment {
        private String segmentName; // "VIP", "Regular", "Occasional", "At Risk", "New"
        private int customerCount;
        private BigDecimal percentOfTotal;
        private BigDecimal averageOrderValue;
        private BigDecimal totalRevenue;
        private int averageOrdersPerMonth;


        @java.lang.SuppressWarnings("all")
        public static class CustomerSegmentBuilder {
            @java.lang.SuppressWarnings("all")
            private String segmentName;
            @java.lang.SuppressWarnings("all")
            private int customerCount;
            @java.lang.SuppressWarnings("all")
            private BigDecimal percentOfTotal;
            @java.lang.SuppressWarnings("all")
            private BigDecimal averageOrderValue;
            @java.lang.SuppressWarnings("all")
            private BigDecimal totalRevenue;
            @java.lang.SuppressWarnings("all")
            private int averageOrdersPerMonth;

            @java.lang.SuppressWarnings("all")
            CustomerSegmentBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.CustomerSegment.CustomerSegmentBuilder segmentName(final String segmentName) {
                this.segmentName = segmentName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.CustomerSegment.CustomerSegmentBuilder customerCount(final int customerCount) {
                this.customerCount = customerCount;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.CustomerSegment.CustomerSegmentBuilder percentOfTotal(final BigDecimal percentOfTotal) {
                this.percentOfTotal = percentOfTotal;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.CustomerSegment.CustomerSegmentBuilder averageOrderValue(final BigDecimal averageOrderValue) {
                this.averageOrderValue = averageOrderValue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.CustomerSegment.CustomerSegmentBuilder totalRevenue(final BigDecimal totalRevenue) {
                this.totalRevenue = totalRevenue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.CustomerSegment.CustomerSegmentBuilder averageOrdersPerMonth(final int averageOrdersPerMonth) {
                this.averageOrdersPerMonth = averageOrdersPerMonth;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.CustomerSegment build() {
                return new CustomerBehaviorResponse.CustomerSegment(this.segmentName, this.customerCount, this.percentOfTotal, this.averageOrderValue, this.totalRevenue, this.averageOrdersPerMonth);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "CustomerBehaviorResponse.CustomerSegment.CustomerSegmentBuilder(segmentName=" + this.segmentName + ", customerCount=" + this.customerCount + ", percentOfTotal=" + this.percentOfTotal + ", averageOrderValue=" + this.averageOrderValue + ", totalRevenue=" + this.totalRevenue + ", averageOrdersPerMonth=" + this.averageOrdersPerMonth + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static CustomerBehaviorResponse.CustomerSegment.CustomerSegmentBuilder builder() {
            return new CustomerBehaviorResponse.CustomerSegment.CustomerSegmentBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getSegmentName() {
            return this.segmentName;
        }

        @java.lang.SuppressWarnings("all")
        public int getCustomerCount() {
            return this.customerCount;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getPercentOfTotal() {
            return this.percentOfTotal;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getAverageOrderValue() {
            return this.averageOrderValue;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getTotalRevenue() {
            return this.totalRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public int getAverageOrdersPerMonth() {
            return this.averageOrdersPerMonth;
        }

        @java.lang.SuppressWarnings("all")
        public void setSegmentName(final String segmentName) {
            this.segmentName = segmentName;
        }

        @java.lang.SuppressWarnings("all")
        public void setCustomerCount(final int customerCount) {
            this.customerCount = customerCount;
        }

        @java.lang.SuppressWarnings("all")
        public void setPercentOfTotal(final BigDecimal percentOfTotal) {
            this.percentOfTotal = percentOfTotal;
        }

        @java.lang.SuppressWarnings("all")
        public void setAverageOrderValue(final BigDecimal averageOrderValue) {
            this.averageOrderValue = averageOrderValue;
        }

        @java.lang.SuppressWarnings("all")
        public void setTotalRevenue(final BigDecimal totalRevenue) {
            this.totalRevenue = totalRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public void setAverageOrdersPerMonth(final int averageOrdersPerMonth) {
            this.averageOrdersPerMonth = averageOrdersPerMonth;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof CustomerBehaviorResponse.CustomerSegment)) return false;
            final CustomerBehaviorResponse.CustomerSegment other = (CustomerBehaviorResponse.CustomerSegment) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getCustomerCount() != other.getCustomerCount()) return false;
            if (this.getAverageOrdersPerMonth() != other.getAverageOrdersPerMonth()) return false;
            final java.lang.Object this$segmentName = this.getSegmentName();
            final java.lang.Object other$segmentName = other.getSegmentName();
            if (this$segmentName == null ? other$segmentName != null : !this$segmentName.equals(other$segmentName)) return false;
            final java.lang.Object this$percentOfTotal = this.getPercentOfTotal();
            final java.lang.Object other$percentOfTotal = other.getPercentOfTotal();
            if (this$percentOfTotal == null ? other$percentOfTotal != null : !this$percentOfTotal.equals(other$percentOfTotal)) return false;
            final java.lang.Object this$averageOrderValue = this.getAverageOrderValue();
            final java.lang.Object other$averageOrderValue = other.getAverageOrderValue();
            if (this$averageOrderValue == null ? other$averageOrderValue != null : !this$averageOrderValue.equals(other$averageOrderValue)) return false;
            final java.lang.Object this$totalRevenue = this.getTotalRevenue();
            final java.lang.Object other$totalRevenue = other.getTotalRevenue();
            if (this$totalRevenue == null ? other$totalRevenue != null : !this$totalRevenue.equals(other$totalRevenue)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof CustomerBehaviorResponse.CustomerSegment;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getCustomerCount();
            result = result * PRIME + this.getAverageOrdersPerMonth();
            final java.lang.Object $segmentName = this.getSegmentName();
            result = result * PRIME + ($segmentName == null ? 43 : $segmentName.hashCode());
            final java.lang.Object $percentOfTotal = this.getPercentOfTotal();
            result = result * PRIME + ($percentOfTotal == null ? 43 : $percentOfTotal.hashCode());
            final java.lang.Object $averageOrderValue = this.getAverageOrderValue();
            result = result * PRIME + ($averageOrderValue == null ? 43 : $averageOrderValue.hashCode());
            final java.lang.Object $totalRevenue = this.getTotalRevenue();
            result = result * PRIME + ($totalRevenue == null ? 43 : $totalRevenue.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "CustomerBehaviorResponse.CustomerSegment(segmentName=" + this.getSegmentName() + ", customerCount=" + this.getCustomerCount() + ", percentOfTotal=" + this.getPercentOfTotal() + ", averageOrderValue=" + this.getAverageOrderValue() + ", totalRevenue=" + this.getTotalRevenue() + ", averageOrdersPerMonth=" + this.getAverageOrdersPerMonth() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public CustomerSegment() {
        }

        @java.lang.SuppressWarnings("all")
        public CustomerSegment(final String segmentName, final int customerCount, final BigDecimal percentOfTotal, final BigDecimal averageOrderValue, final BigDecimal totalRevenue, final int averageOrdersPerMonth) {
            this.segmentName = segmentName;
            this.customerCount = customerCount;
            this.percentOfTotal = percentOfTotal;
            this.averageOrderValue = averageOrderValue;
            this.totalRevenue = totalRevenue;
            this.averageOrdersPerMonth = averageOrdersPerMonth;
        }
    }


    public static class BehaviorPattern {
        private String patternType; // "Peak Ordering Time", "Preferred Order Type", "Favorite Category"
        private String description;
        private Map<String, Object> data;
        private BigDecimal significance; // 0-100


        @java.lang.SuppressWarnings("all")
        public static class BehaviorPatternBuilder {
            @java.lang.SuppressWarnings("all")
            private String patternType;
            @java.lang.SuppressWarnings("all")
            private String description;
            @java.lang.SuppressWarnings("all")
            private Map<String, Object> data;
            @java.lang.SuppressWarnings("all")
            private BigDecimal significance;

            @java.lang.SuppressWarnings("all")
            BehaviorPatternBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.BehaviorPattern.BehaviorPatternBuilder patternType(final String patternType) {
                this.patternType = patternType;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.BehaviorPattern.BehaviorPatternBuilder description(final String description) {
                this.description = description;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.BehaviorPattern.BehaviorPatternBuilder data(final Map<String, Object> data) {
                this.data = data;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.BehaviorPattern.BehaviorPatternBuilder significance(final BigDecimal significance) {
                this.significance = significance;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public CustomerBehaviorResponse.BehaviorPattern build() {
                return new CustomerBehaviorResponse.BehaviorPattern(this.patternType, this.description, this.data, this.significance);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "CustomerBehaviorResponse.BehaviorPattern.BehaviorPatternBuilder(patternType=" + this.patternType + ", description=" + this.description + ", data=" + this.data + ", significance=" + this.significance + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static CustomerBehaviorResponse.BehaviorPattern.BehaviorPatternBuilder builder() {
            return new CustomerBehaviorResponse.BehaviorPattern.BehaviorPatternBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getPatternType() {
            return this.patternType;
        }

        @java.lang.SuppressWarnings("all")
        public String getDescription() {
            return this.description;
        }

        @java.lang.SuppressWarnings("all")
        public Map<String, Object> getData() {
            return this.data;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getSignificance() {
            return this.significance;
        }

        @java.lang.SuppressWarnings("all")
        public void setPatternType(final String patternType) {
            this.patternType = patternType;
        }

        @java.lang.SuppressWarnings("all")
        public void setDescription(final String description) {
            this.description = description;
        }

        @java.lang.SuppressWarnings("all")
        public void setData(final Map<String, Object> data) {
            this.data = data;
        }

        @java.lang.SuppressWarnings("all")
        public void setSignificance(final BigDecimal significance) {
            this.significance = significance;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof CustomerBehaviorResponse.BehaviorPattern)) return false;
            final CustomerBehaviorResponse.BehaviorPattern other = (CustomerBehaviorResponse.BehaviorPattern) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$patternType = this.getPatternType();
            final java.lang.Object other$patternType = other.getPatternType();
            if (this$patternType == null ? other$patternType != null : !this$patternType.equals(other$patternType)) return false;
            final java.lang.Object this$description = this.getDescription();
            final java.lang.Object other$description = other.getDescription();
            if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
            final java.lang.Object this$data = this.getData();
            final java.lang.Object other$data = other.getData();
            if (this$data == null ? other$data != null : !this$data.equals(other$data)) return false;
            final java.lang.Object this$significance = this.getSignificance();
            final java.lang.Object other$significance = other.getSignificance();
            if (this$significance == null ? other$significance != null : !this$significance.equals(other$significance)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof CustomerBehaviorResponse.BehaviorPattern;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $patternType = this.getPatternType();
            result = result * PRIME + ($patternType == null ? 43 : $patternType.hashCode());
            final java.lang.Object $description = this.getDescription();
            result = result * PRIME + ($description == null ? 43 : $description.hashCode());
            final java.lang.Object $data = this.getData();
            result = result * PRIME + ($data == null ? 43 : $data.hashCode());
            final java.lang.Object $significance = this.getSignificance();
            result = result * PRIME + ($significance == null ? 43 : $significance.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "CustomerBehaviorResponse.BehaviorPattern(patternType=" + this.getPatternType() + ", description=" + this.getDescription() + ", data=" + this.getData() + ", significance=" + this.getSignificance() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public BehaviorPattern() {
        }

        @java.lang.SuppressWarnings("all")
        public BehaviorPattern(final String patternType, final String description, final Map<String, Object> data, final BigDecimal significance) {
            this.patternType = patternType;
            this.description = description;
            this.data = data;
            this.significance = significance;
        }
    }


    @java.lang.SuppressWarnings("all")
    public static class CustomerBehaviorResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private int totalCustomers;
        @java.lang.SuppressWarnings("all")
        private int activeCustomers;
        @java.lang.SuppressWarnings("all")
        private int newCustomers;
        @java.lang.SuppressWarnings("all")
        private BigDecimal averageLifetimeValue;
        @java.lang.SuppressWarnings("all")
        private BigDecimal averageOrderFrequency;
        @java.lang.SuppressWarnings("all")
        private List<CustomerSegment> segments;
        @java.lang.SuppressWarnings("all")
        private List<BehaviorPattern> patterns;

        @java.lang.SuppressWarnings("all")
        CustomerBehaviorResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CustomerBehaviorResponse.CustomerBehaviorResponseBuilder totalCustomers(final int totalCustomers) {
            this.totalCustomers = totalCustomers;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CustomerBehaviorResponse.CustomerBehaviorResponseBuilder activeCustomers(final int activeCustomers) {
            this.activeCustomers = activeCustomers;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CustomerBehaviorResponse.CustomerBehaviorResponseBuilder newCustomers(final int newCustomers) {
            this.newCustomers = newCustomers;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CustomerBehaviorResponse.CustomerBehaviorResponseBuilder averageLifetimeValue(final BigDecimal averageLifetimeValue) {
            this.averageLifetimeValue = averageLifetimeValue;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CustomerBehaviorResponse.CustomerBehaviorResponseBuilder averageOrderFrequency(final BigDecimal averageOrderFrequency) {
            this.averageOrderFrequency = averageOrderFrequency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CustomerBehaviorResponse.CustomerBehaviorResponseBuilder segments(final List<CustomerSegment> segments) {
            this.segments = segments;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public CustomerBehaviorResponse.CustomerBehaviorResponseBuilder patterns(final List<BehaviorPattern> patterns) {
            this.patterns = patterns;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public CustomerBehaviorResponse build() {
            return new CustomerBehaviorResponse(this.totalCustomers, this.activeCustomers, this.newCustomers, this.averageLifetimeValue, this.averageOrderFrequency, this.segments, this.patterns);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "CustomerBehaviorResponse.CustomerBehaviorResponseBuilder(totalCustomers=" + this.totalCustomers + ", activeCustomers=" + this.activeCustomers + ", newCustomers=" + this.newCustomers + ", averageLifetimeValue=" + this.averageLifetimeValue + ", averageOrderFrequency=" + this.averageOrderFrequency + ", segments=" + this.segments + ", patterns=" + this.patterns + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static CustomerBehaviorResponse.CustomerBehaviorResponseBuilder builder() {
        return new CustomerBehaviorResponse.CustomerBehaviorResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public int getTotalCustomers() {
        return this.totalCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public int getActiveCustomers() {
        return this.activeCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public int getNewCustomers() {
        return this.newCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getAverageLifetimeValue() {
        return this.averageLifetimeValue;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getAverageOrderFrequency() {
        return this.averageOrderFrequency;
    }

    @java.lang.SuppressWarnings("all")
    public List<CustomerSegment> getSegments() {
        return this.segments;
    }

    @java.lang.SuppressWarnings("all")
    public List<BehaviorPattern> getPatterns() {
        return this.patterns;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalCustomers(final int totalCustomers) {
        this.totalCustomers = totalCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public void setActiveCustomers(final int activeCustomers) {
        this.activeCustomers = activeCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public void setNewCustomers(final int newCustomers) {
        this.newCustomers = newCustomers;
    }

    @java.lang.SuppressWarnings("all")
    public void setAverageLifetimeValue(final BigDecimal averageLifetimeValue) {
        this.averageLifetimeValue = averageLifetimeValue;
    }

    @java.lang.SuppressWarnings("all")
    public void setAverageOrderFrequency(final BigDecimal averageOrderFrequency) {
        this.averageOrderFrequency = averageOrderFrequency;
    }

    @java.lang.SuppressWarnings("all")
    public void setSegments(final List<CustomerSegment> segments) {
        this.segments = segments;
    }

    @java.lang.SuppressWarnings("all")
    public void setPatterns(final List<BehaviorPattern> patterns) {
        this.patterns = patterns;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CustomerBehaviorResponse)) return false;
        final CustomerBehaviorResponse other = (CustomerBehaviorResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalCustomers() != other.getTotalCustomers()) return false;
        if (this.getActiveCustomers() != other.getActiveCustomers()) return false;
        if (this.getNewCustomers() != other.getNewCustomers()) return false;
        final java.lang.Object this$averageLifetimeValue = this.getAverageLifetimeValue();
        final java.lang.Object other$averageLifetimeValue = other.getAverageLifetimeValue();
        if (this$averageLifetimeValue == null ? other$averageLifetimeValue != null : !this$averageLifetimeValue.equals(other$averageLifetimeValue)) return false;
        final java.lang.Object this$averageOrderFrequency = this.getAverageOrderFrequency();
        final java.lang.Object other$averageOrderFrequency = other.getAverageOrderFrequency();
        if (this$averageOrderFrequency == null ? other$averageOrderFrequency != null : !this$averageOrderFrequency.equals(other$averageOrderFrequency)) return false;
        final java.lang.Object this$segments = this.getSegments();
        final java.lang.Object other$segments = other.getSegments();
        if (this$segments == null ? other$segments != null : !this$segments.equals(other$segments)) return false;
        final java.lang.Object this$patterns = this.getPatterns();
        final java.lang.Object other$patterns = other.getPatterns();
        if (this$patterns == null ? other$patterns != null : !this$patterns.equals(other$patterns)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CustomerBehaviorResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getTotalCustomers();
        result = result * PRIME + this.getActiveCustomers();
        result = result * PRIME + this.getNewCustomers();
        final java.lang.Object $averageLifetimeValue = this.getAverageLifetimeValue();
        result = result * PRIME + ($averageLifetimeValue == null ? 43 : $averageLifetimeValue.hashCode());
        final java.lang.Object $averageOrderFrequency = this.getAverageOrderFrequency();
        result = result * PRIME + ($averageOrderFrequency == null ? 43 : $averageOrderFrequency.hashCode());
        final java.lang.Object $segments = this.getSegments();
        result = result * PRIME + ($segments == null ? 43 : $segments.hashCode());
        final java.lang.Object $patterns = this.getPatterns();
        result = result * PRIME + ($patterns == null ? 43 : $patterns.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "CustomerBehaviorResponse(totalCustomers=" + this.getTotalCustomers() + ", activeCustomers=" + this.getActiveCustomers() + ", newCustomers=" + this.getNewCustomers() + ", averageLifetimeValue=" + this.getAverageLifetimeValue() + ", averageOrderFrequency=" + this.getAverageOrderFrequency() + ", segments=" + this.getSegments() + ", patterns=" + this.getPatterns() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public CustomerBehaviorResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public CustomerBehaviorResponse(final int totalCustomers, final int activeCustomers, final int newCustomers, final BigDecimal averageLifetimeValue, final BigDecimal averageOrderFrequency, final List<CustomerSegment> segments, final List<BehaviorPattern> patterns) {
        this.totalCustomers = totalCustomers;
        this.activeCustomers = activeCustomers;
        this.newCustomers = newCustomers;
        this.averageLifetimeValue = averageLifetimeValue;
        this.averageOrderFrequency = averageOrderFrequency;
        this.segments = segments;
        this.patterns = patterns;
    }
}
