// Generated by delombok at Wed Nov 26 14:14:05 IST 2025
package com.MaSoVa.analytics.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

public class DemandForecastResponse {
    private String forecastPeriod; // "WEEKLY", "MONTHLY"
    private List<ItemDemandForecast> itemForecasts;
    private List<CategoryDemandForecast> categoryForecasts;
    private LocalDate forecastGeneratedAt;


    public static class ItemDemandForecast {
        private String itemId;
        private String itemName;
        private String category;
        private int forecastedQuantity;
        private BigDecimal forecastedRevenue;
        private int historicalAverageQuantity;
        private BigDecimal growthTrend; // Percentage
        private String recommendation; // "Stock Up", "Normal", "Reduce Stock"
        private List<DailyForecast> dailyBreakdown;


        @java.lang.SuppressWarnings("all")
        public static class ItemDemandForecastBuilder {
            @java.lang.SuppressWarnings("all")
            private String itemId;
            @java.lang.SuppressWarnings("all")
            private String itemName;
            @java.lang.SuppressWarnings("all")
            private String category;
            @java.lang.SuppressWarnings("all")
            private int forecastedQuantity;
            @java.lang.SuppressWarnings("all")
            private BigDecimal forecastedRevenue;
            @java.lang.SuppressWarnings("all")
            private int historicalAverageQuantity;
            @java.lang.SuppressWarnings("all")
            private BigDecimal growthTrend;
            @java.lang.SuppressWarnings("all")
            private String recommendation;
            @java.lang.SuppressWarnings("all")
            private List<DailyForecast> dailyBreakdown;

            @java.lang.SuppressWarnings("all")
            ItemDemandForecastBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder itemId(final String itemId) {
                this.itemId = itemId;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder itemName(final String itemName) {
                this.itemName = itemName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder category(final String category) {
                this.category = category;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder forecastedQuantity(final int forecastedQuantity) {
                this.forecastedQuantity = forecastedQuantity;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder forecastedRevenue(final BigDecimal forecastedRevenue) {
                this.forecastedRevenue = forecastedRevenue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder historicalAverageQuantity(final int historicalAverageQuantity) {
                this.historicalAverageQuantity = historicalAverageQuantity;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder growthTrend(final BigDecimal growthTrend) {
                this.growthTrend = growthTrend;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder recommendation(final String recommendation) {
                this.recommendation = recommendation;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder dailyBreakdown(final List<DailyForecast> dailyBreakdown) {
                this.dailyBreakdown = dailyBreakdown;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.ItemDemandForecast build() {
                return new DemandForecastResponse.ItemDemandForecast(this.itemId, this.itemName, this.category, this.forecastedQuantity, this.forecastedRevenue, this.historicalAverageQuantity, this.growthTrend, this.recommendation, this.dailyBreakdown);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder(itemId=" + this.itemId + ", itemName=" + this.itemName + ", category=" + this.category + ", forecastedQuantity=" + this.forecastedQuantity + ", forecastedRevenue=" + this.forecastedRevenue + ", historicalAverageQuantity=" + this.historicalAverageQuantity + ", growthTrend=" + this.growthTrend + ", recommendation=" + this.recommendation + ", dailyBreakdown=" + this.dailyBreakdown + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder builder() {
            return new DemandForecastResponse.ItemDemandForecast.ItemDemandForecastBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getItemId() {
            return this.itemId;
        }

        @java.lang.SuppressWarnings("all")
        public String getItemName() {
            return this.itemName;
        }

        @java.lang.SuppressWarnings("all")
        public String getCategory() {
            return this.category;
        }

        @java.lang.SuppressWarnings("all")
        public int getForecastedQuantity() {
            return this.forecastedQuantity;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getForecastedRevenue() {
            return this.forecastedRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public int getHistoricalAverageQuantity() {
            return this.historicalAverageQuantity;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getGrowthTrend() {
            return this.growthTrend;
        }

        @java.lang.SuppressWarnings("all")
        public String getRecommendation() {
            return this.recommendation;
        }

        @java.lang.SuppressWarnings("all")
        public List<DailyForecast> getDailyBreakdown() {
            return this.dailyBreakdown;
        }

        @java.lang.SuppressWarnings("all")
        public void setItemId(final String itemId) {
            this.itemId = itemId;
        }

        @java.lang.SuppressWarnings("all")
        public void setItemName(final String itemName) {
            this.itemName = itemName;
        }

        @java.lang.SuppressWarnings("all")
        public void setCategory(final String category) {
            this.category = category;
        }

        @java.lang.SuppressWarnings("all")
        public void setForecastedQuantity(final int forecastedQuantity) {
            this.forecastedQuantity = forecastedQuantity;
        }

        @java.lang.SuppressWarnings("all")
        public void setForecastedRevenue(final BigDecimal forecastedRevenue) {
            this.forecastedRevenue = forecastedRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public void setHistoricalAverageQuantity(final int historicalAverageQuantity) {
            this.historicalAverageQuantity = historicalAverageQuantity;
        }

        @java.lang.SuppressWarnings("all")
        public void setGrowthTrend(final BigDecimal growthTrend) {
            this.growthTrend = growthTrend;
        }

        @java.lang.SuppressWarnings("all")
        public void setRecommendation(final String recommendation) {
            this.recommendation = recommendation;
        }

        @java.lang.SuppressWarnings("all")
        public void setDailyBreakdown(final List<DailyForecast> dailyBreakdown) {
            this.dailyBreakdown = dailyBreakdown;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof DemandForecastResponse.ItemDemandForecast)) return false;
            final DemandForecastResponse.ItemDemandForecast other = (DemandForecastResponse.ItemDemandForecast) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getForecastedQuantity() != other.getForecastedQuantity()) return false;
            if (this.getHistoricalAverageQuantity() != other.getHistoricalAverageQuantity()) return false;
            final java.lang.Object this$itemId = this.getItemId();
            final java.lang.Object other$itemId = other.getItemId();
            if (this$itemId == null ? other$itemId != null : !this$itemId.equals(other$itemId)) return false;
            final java.lang.Object this$itemName = this.getItemName();
            final java.lang.Object other$itemName = other.getItemName();
            if (this$itemName == null ? other$itemName != null : !this$itemName.equals(other$itemName)) return false;
            final java.lang.Object this$category = this.getCategory();
            final java.lang.Object other$category = other.getCategory();
            if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
            final java.lang.Object this$forecastedRevenue = this.getForecastedRevenue();
            final java.lang.Object other$forecastedRevenue = other.getForecastedRevenue();
            if (this$forecastedRevenue == null ? other$forecastedRevenue != null : !this$forecastedRevenue.equals(other$forecastedRevenue)) return false;
            final java.lang.Object this$growthTrend = this.getGrowthTrend();
            final java.lang.Object other$growthTrend = other.getGrowthTrend();
            if (this$growthTrend == null ? other$growthTrend != null : !this$growthTrend.equals(other$growthTrend)) return false;
            final java.lang.Object this$recommendation = this.getRecommendation();
            final java.lang.Object other$recommendation = other.getRecommendation();
            if (this$recommendation == null ? other$recommendation != null : !this$recommendation.equals(other$recommendation)) return false;
            final java.lang.Object this$dailyBreakdown = this.getDailyBreakdown();
            final java.lang.Object other$dailyBreakdown = other.getDailyBreakdown();
            if (this$dailyBreakdown == null ? other$dailyBreakdown != null : !this$dailyBreakdown.equals(other$dailyBreakdown)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof DemandForecastResponse.ItemDemandForecast;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getForecastedQuantity();
            result = result * PRIME + this.getHistoricalAverageQuantity();
            final java.lang.Object $itemId = this.getItemId();
            result = result * PRIME + ($itemId == null ? 43 : $itemId.hashCode());
            final java.lang.Object $itemName = this.getItemName();
            result = result * PRIME + ($itemName == null ? 43 : $itemName.hashCode());
            final java.lang.Object $category = this.getCategory();
            result = result * PRIME + ($category == null ? 43 : $category.hashCode());
            final java.lang.Object $forecastedRevenue = this.getForecastedRevenue();
            result = result * PRIME + ($forecastedRevenue == null ? 43 : $forecastedRevenue.hashCode());
            final java.lang.Object $growthTrend = this.getGrowthTrend();
            result = result * PRIME + ($growthTrend == null ? 43 : $growthTrend.hashCode());
            final java.lang.Object $recommendation = this.getRecommendation();
            result = result * PRIME + ($recommendation == null ? 43 : $recommendation.hashCode());
            final java.lang.Object $dailyBreakdown = this.getDailyBreakdown();
            result = result * PRIME + ($dailyBreakdown == null ? 43 : $dailyBreakdown.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "DemandForecastResponse.ItemDemandForecast(itemId=" + this.getItemId() + ", itemName=" + this.getItemName() + ", category=" + this.getCategory() + ", forecastedQuantity=" + this.getForecastedQuantity() + ", forecastedRevenue=" + this.getForecastedRevenue() + ", historicalAverageQuantity=" + this.getHistoricalAverageQuantity() + ", growthTrend=" + this.getGrowthTrend() + ", recommendation=" + this.getRecommendation() + ", dailyBreakdown=" + this.getDailyBreakdown() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public ItemDemandForecast() {
        }

        @java.lang.SuppressWarnings("all")
        public ItemDemandForecast(final String itemId, final String itemName, final String category, final int forecastedQuantity, final BigDecimal forecastedRevenue, final int historicalAverageQuantity, final BigDecimal growthTrend, final String recommendation, final List<DailyForecast> dailyBreakdown) {
            this.itemId = itemId;
            this.itemName = itemName;
            this.category = category;
            this.forecastedQuantity = forecastedQuantity;
            this.forecastedRevenue = forecastedRevenue;
            this.historicalAverageQuantity = historicalAverageQuantity;
            this.growthTrend = growthTrend;
            this.recommendation = recommendation;
            this.dailyBreakdown = dailyBreakdown;
        }
    }


    public static class CategoryDemandForecast {
        private String category;
        private int forecastedQuantity;
        private BigDecimal forecastedRevenue;
        private BigDecimal percentChange;
        private String trend; // "UP", "DOWN", "STABLE"


        @java.lang.SuppressWarnings("all")
        public static class CategoryDemandForecastBuilder {
            @java.lang.SuppressWarnings("all")
            private String category;
            @java.lang.SuppressWarnings("all")
            private int forecastedQuantity;
            @java.lang.SuppressWarnings("all")
            private BigDecimal forecastedRevenue;
            @java.lang.SuppressWarnings("all")
            private BigDecimal percentChange;
            @java.lang.SuppressWarnings("all")
            private String trend;

            @java.lang.SuppressWarnings("all")
            CategoryDemandForecastBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.CategoryDemandForecast.CategoryDemandForecastBuilder category(final String category) {
                this.category = category;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.CategoryDemandForecast.CategoryDemandForecastBuilder forecastedQuantity(final int forecastedQuantity) {
                this.forecastedQuantity = forecastedQuantity;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.CategoryDemandForecast.CategoryDemandForecastBuilder forecastedRevenue(final BigDecimal forecastedRevenue) {
                this.forecastedRevenue = forecastedRevenue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.CategoryDemandForecast.CategoryDemandForecastBuilder percentChange(final BigDecimal percentChange) {
                this.percentChange = percentChange;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.CategoryDemandForecast.CategoryDemandForecastBuilder trend(final String trend) {
                this.trend = trend;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.CategoryDemandForecast build() {
                return new DemandForecastResponse.CategoryDemandForecast(this.category, this.forecastedQuantity, this.forecastedRevenue, this.percentChange, this.trend);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "DemandForecastResponse.CategoryDemandForecast.CategoryDemandForecastBuilder(category=" + this.category + ", forecastedQuantity=" + this.forecastedQuantity + ", forecastedRevenue=" + this.forecastedRevenue + ", percentChange=" + this.percentChange + ", trend=" + this.trend + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static DemandForecastResponse.CategoryDemandForecast.CategoryDemandForecastBuilder builder() {
            return new DemandForecastResponse.CategoryDemandForecast.CategoryDemandForecastBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getCategory() {
            return this.category;
        }

        @java.lang.SuppressWarnings("all")
        public int getForecastedQuantity() {
            return this.forecastedQuantity;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getForecastedRevenue() {
            return this.forecastedRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getPercentChange() {
            return this.percentChange;
        }

        @java.lang.SuppressWarnings("all")
        public String getTrend() {
            return this.trend;
        }

        @java.lang.SuppressWarnings("all")
        public void setCategory(final String category) {
            this.category = category;
        }

        @java.lang.SuppressWarnings("all")
        public void setForecastedQuantity(final int forecastedQuantity) {
            this.forecastedQuantity = forecastedQuantity;
        }

        @java.lang.SuppressWarnings("all")
        public void setForecastedRevenue(final BigDecimal forecastedRevenue) {
            this.forecastedRevenue = forecastedRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public void setPercentChange(final BigDecimal percentChange) {
            this.percentChange = percentChange;
        }

        @java.lang.SuppressWarnings("all")
        public void setTrend(final String trend) {
            this.trend = trend;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof DemandForecastResponse.CategoryDemandForecast)) return false;
            final DemandForecastResponse.CategoryDemandForecast other = (DemandForecastResponse.CategoryDemandForecast) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getForecastedQuantity() != other.getForecastedQuantity()) return false;
            final java.lang.Object this$category = this.getCategory();
            final java.lang.Object other$category = other.getCategory();
            if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
            final java.lang.Object this$forecastedRevenue = this.getForecastedRevenue();
            final java.lang.Object other$forecastedRevenue = other.getForecastedRevenue();
            if (this$forecastedRevenue == null ? other$forecastedRevenue != null : !this$forecastedRevenue.equals(other$forecastedRevenue)) return false;
            final java.lang.Object this$percentChange = this.getPercentChange();
            final java.lang.Object other$percentChange = other.getPercentChange();
            if (this$percentChange == null ? other$percentChange != null : !this$percentChange.equals(other$percentChange)) return false;
            final java.lang.Object this$trend = this.getTrend();
            final java.lang.Object other$trend = other.getTrend();
            if (this$trend == null ? other$trend != null : !this$trend.equals(other$trend)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof DemandForecastResponse.CategoryDemandForecast;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getForecastedQuantity();
            final java.lang.Object $category = this.getCategory();
            result = result * PRIME + ($category == null ? 43 : $category.hashCode());
            final java.lang.Object $forecastedRevenue = this.getForecastedRevenue();
            result = result * PRIME + ($forecastedRevenue == null ? 43 : $forecastedRevenue.hashCode());
            final java.lang.Object $percentChange = this.getPercentChange();
            result = result * PRIME + ($percentChange == null ? 43 : $percentChange.hashCode());
            final java.lang.Object $trend = this.getTrend();
            result = result * PRIME + ($trend == null ? 43 : $trend.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "DemandForecastResponse.CategoryDemandForecast(category=" + this.getCategory() + ", forecastedQuantity=" + this.getForecastedQuantity() + ", forecastedRevenue=" + this.getForecastedRevenue() + ", percentChange=" + this.getPercentChange() + ", trend=" + this.getTrend() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public CategoryDemandForecast() {
        }

        @java.lang.SuppressWarnings("all")
        public CategoryDemandForecast(final String category, final int forecastedQuantity, final BigDecimal forecastedRevenue, final BigDecimal percentChange, final String trend) {
            this.category = category;
            this.forecastedQuantity = forecastedQuantity;
            this.forecastedRevenue = forecastedRevenue;
            this.percentChange = percentChange;
            this.trend = trend;
        }
    }


    public static class DailyForecast {
        private LocalDate date;
        private int quantity;
        private BigDecimal confidence; // 0-100


        @java.lang.SuppressWarnings("all")
        public static class DailyForecastBuilder {
            @java.lang.SuppressWarnings("all")
            private LocalDate date;
            @java.lang.SuppressWarnings("all")
            private int quantity;
            @java.lang.SuppressWarnings("all")
            private BigDecimal confidence;

            @java.lang.SuppressWarnings("all")
            DailyForecastBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.DailyForecast.DailyForecastBuilder date(final LocalDate date) {
                this.date = date;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.DailyForecast.DailyForecastBuilder quantity(final int quantity) {
                this.quantity = quantity;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.DailyForecast.DailyForecastBuilder confidence(final BigDecimal confidence) {
                this.confidence = confidence;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public DemandForecastResponse.DailyForecast build() {
                return new DemandForecastResponse.DailyForecast(this.date, this.quantity, this.confidence);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "DemandForecastResponse.DailyForecast.DailyForecastBuilder(date=" + this.date + ", quantity=" + this.quantity + ", confidence=" + this.confidence + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static DemandForecastResponse.DailyForecast.DailyForecastBuilder builder() {
            return new DemandForecastResponse.DailyForecast.DailyForecastBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public LocalDate getDate() {
            return this.date;
        }

        @java.lang.SuppressWarnings("all")
        public int getQuantity() {
            return this.quantity;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getConfidence() {
            return this.confidence;
        }

        @java.lang.SuppressWarnings("all")
        public void setDate(final LocalDate date) {
            this.date = date;
        }

        @java.lang.SuppressWarnings("all")
        public void setQuantity(final int quantity) {
            this.quantity = quantity;
        }

        @java.lang.SuppressWarnings("all")
        public void setConfidence(final BigDecimal confidence) {
            this.confidence = confidence;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof DemandForecastResponse.DailyForecast)) return false;
            final DemandForecastResponse.DailyForecast other = (DemandForecastResponse.DailyForecast) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getQuantity() != other.getQuantity()) return false;
            final java.lang.Object this$date = this.getDate();
            final java.lang.Object other$date = other.getDate();
            if (this$date == null ? other$date != null : !this$date.equals(other$date)) return false;
            final java.lang.Object this$confidence = this.getConfidence();
            final java.lang.Object other$confidence = other.getConfidence();
            if (this$confidence == null ? other$confidence != null : !this$confidence.equals(other$confidence)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof DemandForecastResponse.DailyForecast;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getQuantity();
            final java.lang.Object $date = this.getDate();
            result = result * PRIME + ($date == null ? 43 : $date.hashCode());
            final java.lang.Object $confidence = this.getConfidence();
            result = result * PRIME + ($confidence == null ? 43 : $confidence.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "DemandForecastResponse.DailyForecast(date=" + this.getDate() + ", quantity=" + this.getQuantity() + ", confidence=" + this.getConfidence() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public DailyForecast() {
        }

        @java.lang.SuppressWarnings("all")
        public DailyForecast(final LocalDate date, final int quantity, final BigDecimal confidence) {
            this.date = date;
            this.quantity = quantity;
            this.confidence = confidence;
        }
    }


    @java.lang.SuppressWarnings("all")
    public static class DemandForecastResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private String forecastPeriod;
        @java.lang.SuppressWarnings("all")
        private List<ItemDemandForecast> itemForecasts;
        @java.lang.SuppressWarnings("all")
        private List<CategoryDemandForecast> categoryForecasts;
        @java.lang.SuppressWarnings("all")
        private LocalDate forecastGeneratedAt;

        @java.lang.SuppressWarnings("all")
        DemandForecastResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DemandForecastResponse.DemandForecastResponseBuilder forecastPeriod(final String forecastPeriod) {
            this.forecastPeriod = forecastPeriod;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DemandForecastResponse.DemandForecastResponseBuilder itemForecasts(final List<ItemDemandForecast> itemForecasts) {
            this.itemForecasts = itemForecasts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DemandForecastResponse.DemandForecastResponseBuilder categoryForecasts(final List<CategoryDemandForecast> categoryForecasts) {
            this.categoryForecasts = categoryForecasts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DemandForecastResponse.DemandForecastResponseBuilder forecastGeneratedAt(final LocalDate forecastGeneratedAt) {
            this.forecastGeneratedAt = forecastGeneratedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public DemandForecastResponse build() {
            return new DemandForecastResponse(this.forecastPeriod, this.itemForecasts, this.categoryForecasts, this.forecastGeneratedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "DemandForecastResponse.DemandForecastResponseBuilder(forecastPeriod=" + this.forecastPeriod + ", itemForecasts=" + this.itemForecasts + ", categoryForecasts=" + this.categoryForecasts + ", forecastGeneratedAt=" + this.forecastGeneratedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static DemandForecastResponse.DemandForecastResponseBuilder builder() {
        return new DemandForecastResponse.DemandForecastResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getForecastPeriod() {
        return this.forecastPeriod;
    }

    @java.lang.SuppressWarnings("all")
    public List<ItemDemandForecast> getItemForecasts() {
        return this.itemForecasts;
    }

    @java.lang.SuppressWarnings("all")
    public List<CategoryDemandForecast> getCategoryForecasts() {
        return this.categoryForecasts;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getForecastGeneratedAt() {
        return this.forecastGeneratedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setForecastPeriod(final String forecastPeriod) {
        this.forecastPeriod = forecastPeriod;
    }

    @java.lang.SuppressWarnings("all")
    public void setItemForecasts(final List<ItemDemandForecast> itemForecasts) {
        this.itemForecasts = itemForecasts;
    }

    @java.lang.SuppressWarnings("all")
    public void setCategoryForecasts(final List<CategoryDemandForecast> categoryForecasts) {
        this.categoryForecasts = categoryForecasts;
    }

    @java.lang.SuppressWarnings("all")
    public void setForecastGeneratedAt(final LocalDate forecastGeneratedAt) {
        this.forecastGeneratedAt = forecastGeneratedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DemandForecastResponse)) return false;
        final DemandForecastResponse other = (DemandForecastResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$forecastPeriod = this.getForecastPeriod();
        final java.lang.Object other$forecastPeriod = other.getForecastPeriod();
        if (this$forecastPeriod == null ? other$forecastPeriod != null : !this$forecastPeriod.equals(other$forecastPeriod)) return false;
        final java.lang.Object this$itemForecasts = this.getItemForecasts();
        final java.lang.Object other$itemForecasts = other.getItemForecasts();
        if (this$itemForecasts == null ? other$itemForecasts != null : !this$itemForecasts.equals(other$itemForecasts)) return false;
        final java.lang.Object this$categoryForecasts = this.getCategoryForecasts();
        final java.lang.Object other$categoryForecasts = other.getCategoryForecasts();
        if (this$categoryForecasts == null ? other$categoryForecasts != null : !this$categoryForecasts.equals(other$categoryForecasts)) return false;
        final java.lang.Object this$forecastGeneratedAt = this.getForecastGeneratedAt();
        final java.lang.Object other$forecastGeneratedAt = other.getForecastGeneratedAt();
        if (this$forecastGeneratedAt == null ? other$forecastGeneratedAt != null : !this$forecastGeneratedAt.equals(other$forecastGeneratedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DemandForecastResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $forecastPeriod = this.getForecastPeriod();
        result = result * PRIME + ($forecastPeriod == null ? 43 : $forecastPeriod.hashCode());
        final java.lang.Object $itemForecasts = this.getItemForecasts();
        result = result * PRIME + ($itemForecasts == null ? 43 : $itemForecasts.hashCode());
        final java.lang.Object $categoryForecasts = this.getCategoryForecasts();
        result = result * PRIME + ($categoryForecasts == null ? 43 : $categoryForecasts.hashCode());
        final java.lang.Object $forecastGeneratedAt = this.getForecastGeneratedAt();
        result = result * PRIME + ($forecastGeneratedAt == null ? 43 : $forecastGeneratedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "DemandForecastResponse(forecastPeriod=" + this.getForecastPeriod() + ", itemForecasts=" + this.getItemForecasts() + ", categoryForecasts=" + this.getCategoryForecasts() + ", forecastGeneratedAt=" + this.getForecastGeneratedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public DemandForecastResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public DemandForecastResponse(final String forecastPeriod, final List<ItemDemandForecast> itemForecasts, final List<CategoryDemandForecast> categoryForecasts, final LocalDate forecastGeneratedAt) {
        this.forecastPeriod = forecastPeriod;
        this.itemForecasts = itemForecasts;
        this.categoryForecasts = categoryForecasts;
        this.forecastGeneratedAt = forecastGeneratedAt;
    }
}
