// Generated by delombok at Wed Nov 26 14:14:06 IST 2025
package com.MaSoVa.analytics.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;

public class ExecutiveSummaryResponse {
    private String reportPeriod; // "WEEK", "MONTH", "QUARTER", "YEAR"
    private LocalDate startDate;
    private LocalDate endDate;
    private FinancialSummary financialSummary;
    private OperationalMetrics operationalMetrics;
    private List<KPITile> kpiTiles;
    private GrowthMetrics growthMetrics;
    private List<TopPerformer> topPerformers;
    private List<ActionableInsight> insights;


    public static class FinancialSummary {
        private BigDecimal totalRevenue; // INR
        private BigDecimal totalCosts; // INR
        private BigDecimal grossProfit; // INR
        private BigDecimal netProfit; // INR
        private BigDecimal grossProfitMargin; // Percentage
        private BigDecimal netProfitMargin; // Percentage
        private BigDecimal operatingExpenses; // INR
        private BigDecimal ebitda; // INR
        private BigDecimal roi; // Percentage - Return on Investment
        private Map<String, BigDecimal> revenueByChannel; // "DINE_IN", "DELIVERY", "PICKUP"


        @java.lang.SuppressWarnings("all")
        public static class FinancialSummaryBuilder {
            @java.lang.SuppressWarnings("all")
            private BigDecimal totalRevenue;
            @java.lang.SuppressWarnings("all")
            private BigDecimal totalCosts;
            @java.lang.SuppressWarnings("all")
            private BigDecimal grossProfit;
            @java.lang.SuppressWarnings("all")
            private BigDecimal netProfit;
            @java.lang.SuppressWarnings("all")
            private BigDecimal grossProfitMargin;
            @java.lang.SuppressWarnings("all")
            private BigDecimal netProfitMargin;
            @java.lang.SuppressWarnings("all")
            private BigDecimal operatingExpenses;
            @java.lang.SuppressWarnings("all")
            private BigDecimal ebitda;
            @java.lang.SuppressWarnings("all")
            private BigDecimal roi;
            @java.lang.SuppressWarnings("all")
            private Map<String, BigDecimal> revenueByChannel;

            @java.lang.SuppressWarnings("all")
            FinancialSummaryBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder totalRevenue(final BigDecimal totalRevenue) {
                this.totalRevenue = totalRevenue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder totalCosts(final BigDecimal totalCosts) {
                this.totalCosts = totalCosts;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder grossProfit(final BigDecimal grossProfit) {
                this.grossProfit = grossProfit;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder netProfit(final BigDecimal netProfit) {
                this.netProfit = netProfit;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder grossProfitMargin(final BigDecimal grossProfitMargin) {
                this.grossProfitMargin = grossProfitMargin;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder netProfitMargin(final BigDecimal netProfitMargin) {
                this.netProfitMargin = netProfitMargin;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder operatingExpenses(final BigDecimal operatingExpenses) {
                this.operatingExpenses = operatingExpenses;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder ebitda(final BigDecimal ebitda) {
                this.ebitda = ebitda;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder roi(final BigDecimal roi) {
                this.roi = roi;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder revenueByChannel(final Map<String, BigDecimal> revenueByChannel) {
                this.revenueByChannel = revenueByChannel;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.FinancialSummary build() {
                return new ExecutiveSummaryResponse.FinancialSummary(this.totalRevenue, this.totalCosts, this.grossProfit, this.netProfit, this.grossProfitMargin, this.netProfitMargin, this.operatingExpenses, this.ebitda, this.roi, this.revenueByChannel);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder(totalRevenue=" + this.totalRevenue + ", totalCosts=" + this.totalCosts + ", grossProfit=" + this.grossProfit + ", netProfit=" + this.netProfit + ", grossProfitMargin=" + this.grossProfitMargin + ", netProfitMargin=" + this.netProfitMargin + ", operatingExpenses=" + this.operatingExpenses + ", ebitda=" + this.ebitda + ", roi=" + this.roi + ", revenueByChannel=" + this.revenueByChannel + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder builder() {
            return new ExecutiveSummaryResponse.FinancialSummary.FinancialSummaryBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getTotalRevenue() {
            return this.totalRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getTotalCosts() {
            return this.totalCosts;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getGrossProfit() {
            return this.grossProfit;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getNetProfit() {
            return this.netProfit;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getGrossProfitMargin() {
            return this.grossProfitMargin;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getNetProfitMargin() {
            return this.netProfitMargin;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getOperatingExpenses() {
            return this.operatingExpenses;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getEbitda() {
            return this.ebitda;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getRoi() {
            return this.roi;
        }

        @java.lang.SuppressWarnings("all")
        public Map<String, BigDecimal> getRevenueByChannel() {
            return this.revenueByChannel;
        }

        @java.lang.SuppressWarnings("all")
        public void setTotalRevenue(final BigDecimal totalRevenue) {
            this.totalRevenue = totalRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public void setTotalCosts(final BigDecimal totalCosts) {
            this.totalCosts = totalCosts;
        }

        @java.lang.SuppressWarnings("all")
        public void setGrossProfit(final BigDecimal grossProfit) {
            this.grossProfit = grossProfit;
        }

        @java.lang.SuppressWarnings("all")
        public void setNetProfit(final BigDecimal netProfit) {
            this.netProfit = netProfit;
        }

        @java.lang.SuppressWarnings("all")
        public void setGrossProfitMargin(final BigDecimal grossProfitMargin) {
            this.grossProfitMargin = grossProfitMargin;
        }

        @java.lang.SuppressWarnings("all")
        public void setNetProfitMargin(final BigDecimal netProfitMargin) {
            this.netProfitMargin = netProfitMargin;
        }

        @java.lang.SuppressWarnings("all")
        public void setOperatingExpenses(final BigDecimal operatingExpenses) {
            this.operatingExpenses = operatingExpenses;
        }

        @java.lang.SuppressWarnings("all")
        public void setEbitda(final BigDecimal ebitda) {
            this.ebitda = ebitda;
        }

        @java.lang.SuppressWarnings("all")
        public void setRoi(final BigDecimal roi) {
            this.roi = roi;
        }

        @java.lang.SuppressWarnings("all")
        public void setRevenueByChannel(final Map<String, BigDecimal> revenueByChannel) {
            this.revenueByChannel = revenueByChannel;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ExecutiveSummaryResponse.FinancialSummary)) return false;
            final ExecutiveSummaryResponse.FinancialSummary other = (ExecutiveSummaryResponse.FinancialSummary) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$totalRevenue = this.getTotalRevenue();
            final java.lang.Object other$totalRevenue = other.getTotalRevenue();
            if (this$totalRevenue == null ? other$totalRevenue != null : !this$totalRevenue.equals(other$totalRevenue)) return false;
            final java.lang.Object this$totalCosts = this.getTotalCosts();
            final java.lang.Object other$totalCosts = other.getTotalCosts();
            if (this$totalCosts == null ? other$totalCosts != null : !this$totalCosts.equals(other$totalCosts)) return false;
            final java.lang.Object this$grossProfit = this.getGrossProfit();
            final java.lang.Object other$grossProfit = other.getGrossProfit();
            if (this$grossProfit == null ? other$grossProfit != null : !this$grossProfit.equals(other$grossProfit)) return false;
            final java.lang.Object this$netProfit = this.getNetProfit();
            final java.lang.Object other$netProfit = other.getNetProfit();
            if (this$netProfit == null ? other$netProfit != null : !this$netProfit.equals(other$netProfit)) return false;
            final java.lang.Object this$grossProfitMargin = this.getGrossProfitMargin();
            final java.lang.Object other$grossProfitMargin = other.getGrossProfitMargin();
            if (this$grossProfitMargin == null ? other$grossProfitMargin != null : !this$grossProfitMargin.equals(other$grossProfitMargin)) return false;
            final java.lang.Object this$netProfitMargin = this.getNetProfitMargin();
            final java.lang.Object other$netProfitMargin = other.getNetProfitMargin();
            if (this$netProfitMargin == null ? other$netProfitMargin != null : !this$netProfitMargin.equals(other$netProfitMargin)) return false;
            final java.lang.Object this$operatingExpenses = this.getOperatingExpenses();
            final java.lang.Object other$operatingExpenses = other.getOperatingExpenses();
            if (this$operatingExpenses == null ? other$operatingExpenses != null : !this$operatingExpenses.equals(other$operatingExpenses)) return false;
            final java.lang.Object this$ebitda = this.getEbitda();
            final java.lang.Object other$ebitda = other.getEbitda();
            if (this$ebitda == null ? other$ebitda != null : !this$ebitda.equals(other$ebitda)) return false;
            final java.lang.Object this$roi = this.getRoi();
            final java.lang.Object other$roi = other.getRoi();
            if (this$roi == null ? other$roi != null : !this$roi.equals(other$roi)) return false;
            final java.lang.Object this$revenueByChannel = this.getRevenueByChannel();
            final java.lang.Object other$revenueByChannel = other.getRevenueByChannel();
            if (this$revenueByChannel == null ? other$revenueByChannel != null : !this$revenueByChannel.equals(other$revenueByChannel)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ExecutiveSummaryResponse.FinancialSummary;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $totalRevenue = this.getTotalRevenue();
            result = result * PRIME + ($totalRevenue == null ? 43 : $totalRevenue.hashCode());
            final java.lang.Object $totalCosts = this.getTotalCosts();
            result = result * PRIME + ($totalCosts == null ? 43 : $totalCosts.hashCode());
            final java.lang.Object $grossProfit = this.getGrossProfit();
            result = result * PRIME + ($grossProfit == null ? 43 : $grossProfit.hashCode());
            final java.lang.Object $netProfit = this.getNetProfit();
            result = result * PRIME + ($netProfit == null ? 43 : $netProfit.hashCode());
            final java.lang.Object $grossProfitMargin = this.getGrossProfitMargin();
            result = result * PRIME + ($grossProfitMargin == null ? 43 : $grossProfitMargin.hashCode());
            final java.lang.Object $netProfitMargin = this.getNetProfitMargin();
            result = result * PRIME + ($netProfitMargin == null ? 43 : $netProfitMargin.hashCode());
            final java.lang.Object $operatingExpenses = this.getOperatingExpenses();
            result = result * PRIME + ($operatingExpenses == null ? 43 : $operatingExpenses.hashCode());
            final java.lang.Object $ebitda = this.getEbitda();
            result = result * PRIME + ($ebitda == null ? 43 : $ebitda.hashCode());
            final java.lang.Object $roi = this.getRoi();
            result = result * PRIME + ($roi == null ? 43 : $roi.hashCode());
            final java.lang.Object $revenueByChannel = this.getRevenueByChannel();
            result = result * PRIME + ($revenueByChannel == null ? 43 : $revenueByChannel.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ExecutiveSummaryResponse.FinancialSummary(totalRevenue=" + this.getTotalRevenue() + ", totalCosts=" + this.getTotalCosts() + ", grossProfit=" + this.getGrossProfit() + ", netProfit=" + this.getNetProfit() + ", grossProfitMargin=" + this.getGrossProfitMargin() + ", netProfitMargin=" + this.getNetProfitMargin() + ", operatingExpenses=" + this.getOperatingExpenses() + ", ebitda=" + this.getEbitda() + ", roi=" + this.getRoi() + ", revenueByChannel=" + this.getRevenueByChannel() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public FinancialSummary() {
        }

        @java.lang.SuppressWarnings("all")
        public FinancialSummary(final BigDecimal totalRevenue, final BigDecimal totalCosts, final BigDecimal grossProfit, final BigDecimal netProfit, final BigDecimal grossProfitMargin, final BigDecimal netProfitMargin, final BigDecimal operatingExpenses, final BigDecimal ebitda, final BigDecimal roi, final Map<String, BigDecimal> revenueByChannel) {
            this.totalRevenue = totalRevenue;
            this.totalCosts = totalCosts;
            this.grossProfit = grossProfit;
            this.netProfit = netProfit;
            this.grossProfitMargin = grossProfitMargin;
            this.netProfitMargin = netProfitMargin;
            this.operatingExpenses = operatingExpenses;
            this.ebitda = ebitda;
            this.roi = roi;
            this.revenueByChannel = revenueByChannel;
        }
    }


    public static class OperationalMetrics {
        private int totalOrders;
        private BigDecimal averageOrderValue; // INR
        private int totalCustomers;
        private int newCustomers;
        private int activeCustomers;
        private BigDecimal customerRetentionRate; // Percentage
        private BigDecimal averageDeliveryTime; // Minutes
        private BigDecimal orderAccuracyRate; // Percentage
        private int totalMenuItems;
        private int totalStaff;


        @java.lang.SuppressWarnings("all")
        public static class OperationalMetricsBuilder {
            @java.lang.SuppressWarnings("all")
            private int totalOrders;
            @java.lang.SuppressWarnings("all")
            private BigDecimal averageOrderValue;
            @java.lang.SuppressWarnings("all")
            private int totalCustomers;
            @java.lang.SuppressWarnings("all")
            private int newCustomers;
            @java.lang.SuppressWarnings("all")
            private int activeCustomers;
            @java.lang.SuppressWarnings("all")
            private BigDecimal customerRetentionRate;
            @java.lang.SuppressWarnings("all")
            private BigDecimal averageDeliveryTime;
            @java.lang.SuppressWarnings("all")
            private BigDecimal orderAccuracyRate;
            @java.lang.SuppressWarnings("all")
            private int totalMenuItems;
            @java.lang.SuppressWarnings("all")
            private int totalStaff;

            @java.lang.SuppressWarnings("all")
            OperationalMetricsBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder totalOrders(final int totalOrders) {
                this.totalOrders = totalOrders;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder averageOrderValue(final BigDecimal averageOrderValue) {
                this.averageOrderValue = averageOrderValue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder totalCustomers(final int totalCustomers) {
                this.totalCustomers = totalCustomers;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder newCustomers(final int newCustomers) {
                this.newCustomers = newCustomers;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder activeCustomers(final int activeCustomers) {
                this.activeCustomers = activeCustomers;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder customerRetentionRate(final BigDecimal customerRetentionRate) {
                this.customerRetentionRate = customerRetentionRate;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder averageDeliveryTime(final BigDecimal averageDeliveryTime) {
                this.averageDeliveryTime = averageDeliveryTime;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder orderAccuracyRate(final BigDecimal orderAccuracyRate) {
                this.orderAccuracyRate = orderAccuracyRate;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder totalMenuItems(final int totalMenuItems) {
                this.totalMenuItems = totalMenuItems;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder totalStaff(final int totalStaff) {
                this.totalStaff = totalStaff;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.OperationalMetrics build() {
                return new ExecutiveSummaryResponse.OperationalMetrics(this.totalOrders, this.averageOrderValue, this.totalCustomers, this.newCustomers, this.activeCustomers, this.customerRetentionRate, this.averageDeliveryTime, this.orderAccuracyRate, this.totalMenuItems, this.totalStaff);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder(totalOrders=" + this.totalOrders + ", averageOrderValue=" + this.averageOrderValue + ", totalCustomers=" + this.totalCustomers + ", newCustomers=" + this.newCustomers + ", activeCustomers=" + this.activeCustomers + ", customerRetentionRate=" + this.customerRetentionRate + ", averageDeliveryTime=" + this.averageDeliveryTime + ", orderAccuracyRate=" + this.orderAccuracyRate + ", totalMenuItems=" + this.totalMenuItems + ", totalStaff=" + this.totalStaff + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder builder() {
            return new ExecutiveSummaryResponse.OperationalMetrics.OperationalMetricsBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public int getTotalOrders() {
            return this.totalOrders;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getAverageOrderValue() {
            return this.averageOrderValue;
        }

        @java.lang.SuppressWarnings("all")
        public int getTotalCustomers() {
            return this.totalCustomers;
        }

        @java.lang.SuppressWarnings("all")
        public int getNewCustomers() {
            return this.newCustomers;
        }

        @java.lang.SuppressWarnings("all")
        public int getActiveCustomers() {
            return this.activeCustomers;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getCustomerRetentionRate() {
            return this.customerRetentionRate;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getAverageDeliveryTime() {
            return this.averageDeliveryTime;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getOrderAccuracyRate() {
            return this.orderAccuracyRate;
        }

        @java.lang.SuppressWarnings("all")
        public int getTotalMenuItems() {
            return this.totalMenuItems;
        }

        @java.lang.SuppressWarnings("all")
        public int getTotalStaff() {
            return this.totalStaff;
        }

        @java.lang.SuppressWarnings("all")
        public void setTotalOrders(final int totalOrders) {
            this.totalOrders = totalOrders;
        }

        @java.lang.SuppressWarnings("all")
        public void setAverageOrderValue(final BigDecimal averageOrderValue) {
            this.averageOrderValue = averageOrderValue;
        }

        @java.lang.SuppressWarnings("all")
        public void setTotalCustomers(final int totalCustomers) {
            this.totalCustomers = totalCustomers;
        }

        @java.lang.SuppressWarnings("all")
        public void setNewCustomers(final int newCustomers) {
            this.newCustomers = newCustomers;
        }

        @java.lang.SuppressWarnings("all")
        public void setActiveCustomers(final int activeCustomers) {
            this.activeCustomers = activeCustomers;
        }

        @java.lang.SuppressWarnings("all")
        public void setCustomerRetentionRate(final BigDecimal customerRetentionRate) {
            this.customerRetentionRate = customerRetentionRate;
        }

        @java.lang.SuppressWarnings("all")
        public void setAverageDeliveryTime(final BigDecimal averageDeliveryTime) {
            this.averageDeliveryTime = averageDeliveryTime;
        }

        @java.lang.SuppressWarnings("all")
        public void setOrderAccuracyRate(final BigDecimal orderAccuracyRate) {
            this.orderAccuracyRate = orderAccuracyRate;
        }

        @java.lang.SuppressWarnings("all")
        public void setTotalMenuItems(final int totalMenuItems) {
            this.totalMenuItems = totalMenuItems;
        }

        @java.lang.SuppressWarnings("all")
        public void setTotalStaff(final int totalStaff) {
            this.totalStaff = totalStaff;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ExecutiveSummaryResponse.OperationalMetrics)) return false;
            final ExecutiveSummaryResponse.OperationalMetrics other = (ExecutiveSummaryResponse.OperationalMetrics) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getTotalOrders() != other.getTotalOrders()) return false;
            if (this.getTotalCustomers() != other.getTotalCustomers()) return false;
            if (this.getNewCustomers() != other.getNewCustomers()) return false;
            if (this.getActiveCustomers() != other.getActiveCustomers()) return false;
            if (this.getTotalMenuItems() != other.getTotalMenuItems()) return false;
            if (this.getTotalStaff() != other.getTotalStaff()) return false;
            final java.lang.Object this$averageOrderValue = this.getAverageOrderValue();
            final java.lang.Object other$averageOrderValue = other.getAverageOrderValue();
            if (this$averageOrderValue == null ? other$averageOrderValue != null : !this$averageOrderValue.equals(other$averageOrderValue)) return false;
            final java.lang.Object this$customerRetentionRate = this.getCustomerRetentionRate();
            final java.lang.Object other$customerRetentionRate = other.getCustomerRetentionRate();
            if (this$customerRetentionRate == null ? other$customerRetentionRate != null : !this$customerRetentionRate.equals(other$customerRetentionRate)) return false;
            final java.lang.Object this$averageDeliveryTime = this.getAverageDeliveryTime();
            final java.lang.Object other$averageDeliveryTime = other.getAverageDeliveryTime();
            if (this$averageDeliveryTime == null ? other$averageDeliveryTime != null : !this$averageDeliveryTime.equals(other$averageDeliveryTime)) return false;
            final java.lang.Object this$orderAccuracyRate = this.getOrderAccuracyRate();
            final java.lang.Object other$orderAccuracyRate = other.getOrderAccuracyRate();
            if (this$orderAccuracyRate == null ? other$orderAccuracyRate != null : !this$orderAccuracyRate.equals(other$orderAccuracyRate)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ExecutiveSummaryResponse.OperationalMetrics;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getTotalOrders();
            result = result * PRIME + this.getTotalCustomers();
            result = result * PRIME + this.getNewCustomers();
            result = result * PRIME + this.getActiveCustomers();
            result = result * PRIME + this.getTotalMenuItems();
            result = result * PRIME + this.getTotalStaff();
            final java.lang.Object $averageOrderValue = this.getAverageOrderValue();
            result = result * PRIME + ($averageOrderValue == null ? 43 : $averageOrderValue.hashCode());
            final java.lang.Object $customerRetentionRate = this.getCustomerRetentionRate();
            result = result * PRIME + ($customerRetentionRate == null ? 43 : $customerRetentionRate.hashCode());
            final java.lang.Object $averageDeliveryTime = this.getAverageDeliveryTime();
            result = result * PRIME + ($averageDeliveryTime == null ? 43 : $averageDeliveryTime.hashCode());
            final java.lang.Object $orderAccuracyRate = this.getOrderAccuracyRate();
            result = result * PRIME + ($orderAccuracyRate == null ? 43 : $orderAccuracyRate.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ExecutiveSummaryResponse.OperationalMetrics(totalOrders=" + this.getTotalOrders() + ", averageOrderValue=" + this.getAverageOrderValue() + ", totalCustomers=" + this.getTotalCustomers() + ", newCustomers=" + this.getNewCustomers() + ", activeCustomers=" + this.getActiveCustomers() + ", customerRetentionRate=" + this.getCustomerRetentionRate() + ", averageDeliveryTime=" + this.getAverageDeliveryTime() + ", orderAccuracyRate=" + this.getOrderAccuracyRate() + ", totalMenuItems=" + this.getTotalMenuItems() + ", totalStaff=" + this.getTotalStaff() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public OperationalMetrics() {
        }

        @java.lang.SuppressWarnings("all")
        public OperationalMetrics(final int totalOrders, final BigDecimal averageOrderValue, final int totalCustomers, final int newCustomers, final int activeCustomers, final BigDecimal customerRetentionRate, final BigDecimal averageDeliveryTime, final BigDecimal orderAccuracyRate, final int totalMenuItems, final int totalStaff) {
            this.totalOrders = totalOrders;
            this.averageOrderValue = averageOrderValue;
            this.totalCustomers = totalCustomers;
            this.newCustomers = newCustomers;
            this.activeCustomers = activeCustomers;
            this.customerRetentionRate = customerRetentionRate;
            this.averageDeliveryTime = averageDeliveryTime;
            this.orderAccuracyRate = orderAccuracyRate;
            this.totalMenuItems = totalMenuItems;
            this.totalStaff = totalStaff;
        }
    }


    public static class KPITile {
        private String kpiName;
        private String category; // "Financial", "Operational", "Customer", "Growth"
        private BigDecimal currentValue;
        private String unit; // "INR", "%", "#", "mins"
        private BigDecimal previousValue;
        private BigDecimal percentChange;
        private String trend; // "UP", "DOWN", "STABLE"
        private String status; // "Excellent", "Good", "Warning", "Critical"
        private BigDecimal target;


        @java.lang.SuppressWarnings("all")
        public static class KPITileBuilder {
            @java.lang.SuppressWarnings("all")
            private String kpiName;
            @java.lang.SuppressWarnings("all")
            private String category;
            @java.lang.SuppressWarnings("all")
            private BigDecimal currentValue;
            @java.lang.SuppressWarnings("all")
            private String unit;
            @java.lang.SuppressWarnings("all")
            private BigDecimal previousValue;
            @java.lang.SuppressWarnings("all")
            private BigDecimal percentChange;
            @java.lang.SuppressWarnings("all")
            private String trend;
            @java.lang.SuppressWarnings("all")
            private String status;
            @java.lang.SuppressWarnings("all")
            private BigDecimal target;

            @java.lang.SuppressWarnings("all")
            KPITileBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.KPITile.KPITileBuilder kpiName(final String kpiName) {
                this.kpiName = kpiName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.KPITile.KPITileBuilder category(final String category) {
                this.category = category;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.KPITile.KPITileBuilder currentValue(final BigDecimal currentValue) {
                this.currentValue = currentValue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.KPITile.KPITileBuilder unit(final String unit) {
                this.unit = unit;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.KPITile.KPITileBuilder previousValue(final BigDecimal previousValue) {
                this.previousValue = previousValue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.KPITile.KPITileBuilder percentChange(final BigDecimal percentChange) {
                this.percentChange = percentChange;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.KPITile.KPITileBuilder trend(final String trend) {
                this.trend = trend;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.KPITile.KPITileBuilder status(final String status) {
                this.status = status;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.KPITile.KPITileBuilder target(final BigDecimal target) {
                this.target = target;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.KPITile build() {
                return new ExecutiveSummaryResponse.KPITile(this.kpiName, this.category, this.currentValue, this.unit, this.previousValue, this.percentChange, this.trend, this.status, this.target);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "ExecutiveSummaryResponse.KPITile.KPITileBuilder(kpiName=" + this.kpiName + ", category=" + this.category + ", currentValue=" + this.currentValue + ", unit=" + this.unit + ", previousValue=" + this.previousValue + ", percentChange=" + this.percentChange + ", trend=" + this.trend + ", status=" + this.status + ", target=" + this.target + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static ExecutiveSummaryResponse.KPITile.KPITileBuilder builder() {
            return new ExecutiveSummaryResponse.KPITile.KPITileBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getKpiName() {
            return this.kpiName;
        }

        @java.lang.SuppressWarnings("all")
        public String getCategory() {
            return this.category;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getCurrentValue() {
            return this.currentValue;
        }

        @java.lang.SuppressWarnings("all")
        public String getUnit() {
            return this.unit;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getPreviousValue() {
            return this.previousValue;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getPercentChange() {
            return this.percentChange;
        }

        @java.lang.SuppressWarnings("all")
        public String getTrend() {
            return this.trend;
        }

        @java.lang.SuppressWarnings("all")
        public String getStatus() {
            return this.status;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getTarget() {
            return this.target;
        }

        @java.lang.SuppressWarnings("all")
        public void setKpiName(final String kpiName) {
            this.kpiName = kpiName;
        }

        @java.lang.SuppressWarnings("all")
        public void setCategory(final String category) {
            this.category = category;
        }

        @java.lang.SuppressWarnings("all")
        public void setCurrentValue(final BigDecimal currentValue) {
            this.currentValue = currentValue;
        }

        @java.lang.SuppressWarnings("all")
        public void setUnit(final String unit) {
            this.unit = unit;
        }

        @java.lang.SuppressWarnings("all")
        public void setPreviousValue(final BigDecimal previousValue) {
            this.previousValue = previousValue;
        }

        @java.lang.SuppressWarnings("all")
        public void setPercentChange(final BigDecimal percentChange) {
            this.percentChange = percentChange;
        }

        @java.lang.SuppressWarnings("all")
        public void setTrend(final String trend) {
            this.trend = trend;
        }

        @java.lang.SuppressWarnings("all")
        public void setStatus(final String status) {
            this.status = status;
        }

        @java.lang.SuppressWarnings("all")
        public void setTarget(final BigDecimal target) {
            this.target = target;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ExecutiveSummaryResponse.KPITile)) return false;
            final ExecutiveSummaryResponse.KPITile other = (ExecutiveSummaryResponse.KPITile) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$kpiName = this.getKpiName();
            final java.lang.Object other$kpiName = other.getKpiName();
            if (this$kpiName == null ? other$kpiName != null : !this$kpiName.equals(other$kpiName)) return false;
            final java.lang.Object this$category = this.getCategory();
            final java.lang.Object other$category = other.getCategory();
            if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
            final java.lang.Object this$currentValue = this.getCurrentValue();
            final java.lang.Object other$currentValue = other.getCurrentValue();
            if (this$currentValue == null ? other$currentValue != null : !this$currentValue.equals(other$currentValue)) return false;
            final java.lang.Object this$unit = this.getUnit();
            final java.lang.Object other$unit = other.getUnit();
            if (this$unit == null ? other$unit != null : !this$unit.equals(other$unit)) return false;
            final java.lang.Object this$previousValue = this.getPreviousValue();
            final java.lang.Object other$previousValue = other.getPreviousValue();
            if (this$previousValue == null ? other$previousValue != null : !this$previousValue.equals(other$previousValue)) return false;
            final java.lang.Object this$percentChange = this.getPercentChange();
            final java.lang.Object other$percentChange = other.getPercentChange();
            if (this$percentChange == null ? other$percentChange != null : !this$percentChange.equals(other$percentChange)) return false;
            final java.lang.Object this$trend = this.getTrend();
            final java.lang.Object other$trend = other.getTrend();
            if (this$trend == null ? other$trend != null : !this$trend.equals(other$trend)) return false;
            final java.lang.Object this$status = this.getStatus();
            final java.lang.Object other$status = other.getStatus();
            if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
            final java.lang.Object this$target = this.getTarget();
            final java.lang.Object other$target = other.getTarget();
            if (this$target == null ? other$target != null : !this$target.equals(other$target)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ExecutiveSummaryResponse.KPITile;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $kpiName = this.getKpiName();
            result = result * PRIME + ($kpiName == null ? 43 : $kpiName.hashCode());
            final java.lang.Object $category = this.getCategory();
            result = result * PRIME + ($category == null ? 43 : $category.hashCode());
            final java.lang.Object $currentValue = this.getCurrentValue();
            result = result * PRIME + ($currentValue == null ? 43 : $currentValue.hashCode());
            final java.lang.Object $unit = this.getUnit();
            result = result * PRIME + ($unit == null ? 43 : $unit.hashCode());
            final java.lang.Object $previousValue = this.getPreviousValue();
            result = result * PRIME + ($previousValue == null ? 43 : $previousValue.hashCode());
            final java.lang.Object $percentChange = this.getPercentChange();
            result = result * PRIME + ($percentChange == null ? 43 : $percentChange.hashCode());
            final java.lang.Object $trend = this.getTrend();
            result = result * PRIME + ($trend == null ? 43 : $trend.hashCode());
            final java.lang.Object $status = this.getStatus();
            result = result * PRIME + ($status == null ? 43 : $status.hashCode());
            final java.lang.Object $target = this.getTarget();
            result = result * PRIME + ($target == null ? 43 : $target.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ExecutiveSummaryResponse.KPITile(kpiName=" + this.getKpiName() + ", category=" + this.getCategory() + ", currentValue=" + this.getCurrentValue() + ", unit=" + this.getUnit() + ", previousValue=" + this.getPreviousValue() + ", percentChange=" + this.getPercentChange() + ", trend=" + this.getTrend() + ", status=" + this.getStatus() + ", target=" + this.getTarget() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public KPITile() {
        }

        @java.lang.SuppressWarnings("all")
        public KPITile(final String kpiName, final String category, final BigDecimal currentValue, final String unit, final BigDecimal previousValue, final BigDecimal percentChange, final String trend, final String status, final BigDecimal target) {
            this.kpiName = kpiName;
            this.category = category;
            this.currentValue = currentValue;
            this.unit = unit;
            this.previousValue = previousValue;
            this.percentChange = percentChange;
            this.trend = trend;
            this.status = status;
            this.target = target;
        }
    }


    public static class GrowthMetrics {
        private BigDecimal revenueGrowthRate; // Percentage
        private BigDecimal customerGrowthRate; // Percentage
        private BigDecimal orderGrowthRate; // Percentage
        private BigDecimal profitGrowthRate; // Percentage
        private BigDecimal marketShareGrowth; // Percentage (if applicable)
        private String projectedAnnualRevenue; // INR - Based on current growth
        private List<GrowthDriver> topDrivers;


        @java.lang.SuppressWarnings("all")
        public static class GrowthMetricsBuilder {
            @java.lang.SuppressWarnings("all")
            private BigDecimal revenueGrowthRate;
            @java.lang.SuppressWarnings("all")
            private BigDecimal customerGrowthRate;
            @java.lang.SuppressWarnings("all")
            private BigDecimal orderGrowthRate;
            @java.lang.SuppressWarnings("all")
            private BigDecimal profitGrowthRate;
            @java.lang.SuppressWarnings("all")
            private BigDecimal marketShareGrowth;
            @java.lang.SuppressWarnings("all")
            private String projectedAnnualRevenue;
            @java.lang.SuppressWarnings("all")
            private List<GrowthDriver> topDrivers;

            @java.lang.SuppressWarnings("all")
            GrowthMetricsBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthMetrics.GrowthMetricsBuilder revenueGrowthRate(final BigDecimal revenueGrowthRate) {
                this.revenueGrowthRate = revenueGrowthRate;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthMetrics.GrowthMetricsBuilder customerGrowthRate(final BigDecimal customerGrowthRate) {
                this.customerGrowthRate = customerGrowthRate;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthMetrics.GrowthMetricsBuilder orderGrowthRate(final BigDecimal orderGrowthRate) {
                this.orderGrowthRate = orderGrowthRate;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthMetrics.GrowthMetricsBuilder profitGrowthRate(final BigDecimal profitGrowthRate) {
                this.profitGrowthRate = profitGrowthRate;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthMetrics.GrowthMetricsBuilder marketShareGrowth(final BigDecimal marketShareGrowth) {
                this.marketShareGrowth = marketShareGrowth;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthMetrics.GrowthMetricsBuilder projectedAnnualRevenue(final String projectedAnnualRevenue) {
                this.projectedAnnualRevenue = projectedAnnualRevenue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthMetrics.GrowthMetricsBuilder topDrivers(final List<GrowthDriver> topDrivers) {
                this.topDrivers = topDrivers;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthMetrics build() {
                return new ExecutiveSummaryResponse.GrowthMetrics(this.revenueGrowthRate, this.customerGrowthRate, this.orderGrowthRate, this.profitGrowthRate, this.marketShareGrowth, this.projectedAnnualRevenue, this.topDrivers);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "ExecutiveSummaryResponse.GrowthMetrics.GrowthMetricsBuilder(revenueGrowthRate=" + this.revenueGrowthRate + ", customerGrowthRate=" + this.customerGrowthRate + ", orderGrowthRate=" + this.orderGrowthRate + ", profitGrowthRate=" + this.profitGrowthRate + ", marketShareGrowth=" + this.marketShareGrowth + ", projectedAnnualRevenue=" + this.projectedAnnualRevenue + ", topDrivers=" + this.topDrivers + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static ExecutiveSummaryResponse.GrowthMetrics.GrowthMetricsBuilder builder() {
            return new ExecutiveSummaryResponse.GrowthMetrics.GrowthMetricsBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getRevenueGrowthRate() {
            return this.revenueGrowthRate;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getCustomerGrowthRate() {
            return this.customerGrowthRate;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getOrderGrowthRate() {
            return this.orderGrowthRate;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getProfitGrowthRate() {
            return this.profitGrowthRate;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getMarketShareGrowth() {
            return this.marketShareGrowth;
        }

        @java.lang.SuppressWarnings("all")
        public String getProjectedAnnualRevenue() {
            return this.projectedAnnualRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public List<GrowthDriver> getTopDrivers() {
            return this.topDrivers;
        }

        @java.lang.SuppressWarnings("all")
        public void setRevenueGrowthRate(final BigDecimal revenueGrowthRate) {
            this.revenueGrowthRate = revenueGrowthRate;
        }

        @java.lang.SuppressWarnings("all")
        public void setCustomerGrowthRate(final BigDecimal customerGrowthRate) {
            this.customerGrowthRate = customerGrowthRate;
        }

        @java.lang.SuppressWarnings("all")
        public void setOrderGrowthRate(final BigDecimal orderGrowthRate) {
            this.orderGrowthRate = orderGrowthRate;
        }

        @java.lang.SuppressWarnings("all")
        public void setProfitGrowthRate(final BigDecimal profitGrowthRate) {
            this.profitGrowthRate = profitGrowthRate;
        }

        @java.lang.SuppressWarnings("all")
        public void setMarketShareGrowth(final BigDecimal marketShareGrowth) {
            this.marketShareGrowth = marketShareGrowth;
        }

        @java.lang.SuppressWarnings("all")
        public void setProjectedAnnualRevenue(final String projectedAnnualRevenue) {
            this.projectedAnnualRevenue = projectedAnnualRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public void setTopDrivers(final List<GrowthDriver> topDrivers) {
            this.topDrivers = topDrivers;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ExecutiveSummaryResponse.GrowthMetrics)) return false;
            final ExecutiveSummaryResponse.GrowthMetrics other = (ExecutiveSummaryResponse.GrowthMetrics) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$revenueGrowthRate = this.getRevenueGrowthRate();
            final java.lang.Object other$revenueGrowthRate = other.getRevenueGrowthRate();
            if (this$revenueGrowthRate == null ? other$revenueGrowthRate != null : !this$revenueGrowthRate.equals(other$revenueGrowthRate)) return false;
            final java.lang.Object this$customerGrowthRate = this.getCustomerGrowthRate();
            final java.lang.Object other$customerGrowthRate = other.getCustomerGrowthRate();
            if (this$customerGrowthRate == null ? other$customerGrowthRate != null : !this$customerGrowthRate.equals(other$customerGrowthRate)) return false;
            final java.lang.Object this$orderGrowthRate = this.getOrderGrowthRate();
            final java.lang.Object other$orderGrowthRate = other.getOrderGrowthRate();
            if (this$orderGrowthRate == null ? other$orderGrowthRate != null : !this$orderGrowthRate.equals(other$orderGrowthRate)) return false;
            final java.lang.Object this$profitGrowthRate = this.getProfitGrowthRate();
            final java.lang.Object other$profitGrowthRate = other.getProfitGrowthRate();
            if (this$profitGrowthRate == null ? other$profitGrowthRate != null : !this$profitGrowthRate.equals(other$profitGrowthRate)) return false;
            final java.lang.Object this$marketShareGrowth = this.getMarketShareGrowth();
            final java.lang.Object other$marketShareGrowth = other.getMarketShareGrowth();
            if (this$marketShareGrowth == null ? other$marketShareGrowth != null : !this$marketShareGrowth.equals(other$marketShareGrowth)) return false;
            final java.lang.Object this$projectedAnnualRevenue = this.getProjectedAnnualRevenue();
            final java.lang.Object other$projectedAnnualRevenue = other.getProjectedAnnualRevenue();
            if (this$projectedAnnualRevenue == null ? other$projectedAnnualRevenue != null : !this$projectedAnnualRevenue.equals(other$projectedAnnualRevenue)) return false;
            final java.lang.Object this$topDrivers = this.getTopDrivers();
            final java.lang.Object other$topDrivers = other.getTopDrivers();
            if (this$topDrivers == null ? other$topDrivers != null : !this$topDrivers.equals(other$topDrivers)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ExecutiveSummaryResponse.GrowthMetrics;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $revenueGrowthRate = this.getRevenueGrowthRate();
            result = result * PRIME + ($revenueGrowthRate == null ? 43 : $revenueGrowthRate.hashCode());
            final java.lang.Object $customerGrowthRate = this.getCustomerGrowthRate();
            result = result * PRIME + ($customerGrowthRate == null ? 43 : $customerGrowthRate.hashCode());
            final java.lang.Object $orderGrowthRate = this.getOrderGrowthRate();
            result = result * PRIME + ($orderGrowthRate == null ? 43 : $orderGrowthRate.hashCode());
            final java.lang.Object $profitGrowthRate = this.getProfitGrowthRate();
            result = result * PRIME + ($profitGrowthRate == null ? 43 : $profitGrowthRate.hashCode());
            final java.lang.Object $marketShareGrowth = this.getMarketShareGrowth();
            result = result * PRIME + ($marketShareGrowth == null ? 43 : $marketShareGrowth.hashCode());
            final java.lang.Object $projectedAnnualRevenue = this.getProjectedAnnualRevenue();
            result = result * PRIME + ($projectedAnnualRevenue == null ? 43 : $projectedAnnualRevenue.hashCode());
            final java.lang.Object $topDrivers = this.getTopDrivers();
            result = result * PRIME + ($topDrivers == null ? 43 : $topDrivers.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ExecutiveSummaryResponse.GrowthMetrics(revenueGrowthRate=" + this.getRevenueGrowthRate() + ", customerGrowthRate=" + this.getCustomerGrowthRate() + ", orderGrowthRate=" + this.getOrderGrowthRate() + ", profitGrowthRate=" + this.getProfitGrowthRate() + ", marketShareGrowth=" + this.getMarketShareGrowth() + ", projectedAnnualRevenue=" + this.getProjectedAnnualRevenue() + ", topDrivers=" + this.getTopDrivers() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public GrowthMetrics() {
        }

        @java.lang.SuppressWarnings("all")
        public GrowthMetrics(final BigDecimal revenueGrowthRate, final BigDecimal customerGrowthRate, final BigDecimal orderGrowthRate, final BigDecimal profitGrowthRate, final BigDecimal marketShareGrowth, final String projectedAnnualRevenue, final List<GrowthDriver> topDrivers) {
            this.revenueGrowthRate = revenueGrowthRate;
            this.customerGrowthRate = customerGrowthRate;
            this.orderGrowthRate = orderGrowthRate;
            this.profitGrowthRate = profitGrowthRate;
            this.marketShareGrowth = marketShareGrowth;
            this.projectedAnnualRevenue = projectedAnnualRevenue;
            this.topDrivers = topDrivers;
        }
    }


    public static class GrowthDriver {
        private String driverName;
        private String description;
        private BigDecimal contribution; // Percentage of total growth


        @java.lang.SuppressWarnings("all")
        public static class GrowthDriverBuilder {
            @java.lang.SuppressWarnings("all")
            private String driverName;
            @java.lang.SuppressWarnings("all")
            private String description;
            @java.lang.SuppressWarnings("all")
            private BigDecimal contribution;

            @java.lang.SuppressWarnings("all")
            GrowthDriverBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthDriver.GrowthDriverBuilder driverName(final String driverName) {
                this.driverName = driverName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthDriver.GrowthDriverBuilder description(final String description) {
                this.description = description;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthDriver.GrowthDriverBuilder contribution(final BigDecimal contribution) {
                this.contribution = contribution;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.GrowthDriver build() {
                return new ExecutiveSummaryResponse.GrowthDriver(this.driverName, this.description, this.contribution);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "ExecutiveSummaryResponse.GrowthDriver.GrowthDriverBuilder(driverName=" + this.driverName + ", description=" + this.description + ", contribution=" + this.contribution + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static ExecutiveSummaryResponse.GrowthDriver.GrowthDriverBuilder builder() {
            return new ExecutiveSummaryResponse.GrowthDriver.GrowthDriverBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getDriverName() {
            return this.driverName;
        }

        @java.lang.SuppressWarnings("all")
        public String getDescription() {
            return this.description;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getContribution() {
            return this.contribution;
        }

        @java.lang.SuppressWarnings("all")
        public void setDriverName(final String driverName) {
            this.driverName = driverName;
        }

        @java.lang.SuppressWarnings("all")
        public void setDescription(final String description) {
            this.description = description;
        }

        @java.lang.SuppressWarnings("all")
        public void setContribution(final BigDecimal contribution) {
            this.contribution = contribution;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ExecutiveSummaryResponse.GrowthDriver)) return false;
            final ExecutiveSummaryResponse.GrowthDriver other = (ExecutiveSummaryResponse.GrowthDriver) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$driverName = this.getDriverName();
            final java.lang.Object other$driverName = other.getDriverName();
            if (this$driverName == null ? other$driverName != null : !this$driverName.equals(other$driverName)) return false;
            final java.lang.Object this$description = this.getDescription();
            final java.lang.Object other$description = other.getDescription();
            if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
            final java.lang.Object this$contribution = this.getContribution();
            final java.lang.Object other$contribution = other.getContribution();
            if (this$contribution == null ? other$contribution != null : !this$contribution.equals(other$contribution)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ExecutiveSummaryResponse.GrowthDriver;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $driverName = this.getDriverName();
            result = result * PRIME + ($driverName == null ? 43 : $driverName.hashCode());
            final java.lang.Object $description = this.getDescription();
            result = result * PRIME + ($description == null ? 43 : $description.hashCode());
            final java.lang.Object $contribution = this.getContribution();
            result = result * PRIME + ($contribution == null ? 43 : $contribution.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ExecutiveSummaryResponse.GrowthDriver(driverName=" + this.getDriverName() + ", description=" + this.getDescription() + ", contribution=" + this.getContribution() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public GrowthDriver() {
        }

        @java.lang.SuppressWarnings("all")
        public GrowthDriver(final String driverName, final String description, final BigDecimal contribution) {
            this.driverName = driverName;
            this.description = description;
            this.contribution = contribution;
        }
    }


    public static class TopPerformer {
        private String category; // "Store", "Staff", "Product", "Customer"
        private String name;
        private String id;
        private BigDecimal value;
        private String metric; // "Sales", "Orders", "Rating"
        private int rank;


        @java.lang.SuppressWarnings("all")
        public static class TopPerformerBuilder {
            @java.lang.SuppressWarnings("all")
            private String category;
            @java.lang.SuppressWarnings("all")
            private String name;
            @java.lang.SuppressWarnings("all")
            private String id;
            @java.lang.SuppressWarnings("all")
            private BigDecimal value;
            @java.lang.SuppressWarnings("all")
            private String metric;
            @java.lang.SuppressWarnings("all")
            private int rank;

            @java.lang.SuppressWarnings("all")
            TopPerformerBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.TopPerformer.TopPerformerBuilder category(final String category) {
                this.category = category;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.TopPerformer.TopPerformerBuilder name(final String name) {
                this.name = name;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.TopPerformer.TopPerformerBuilder id(final String id) {
                this.id = id;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.TopPerformer.TopPerformerBuilder value(final BigDecimal value) {
                this.value = value;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.TopPerformer.TopPerformerBuilder metric(final String metric) {
                this.metric = metric;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.TopPerformer.TopPerformerBuilder rank(final int rank) {
                this.rank = rank;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.TopPerformer build() {
                return new ExecutiveSummaryResponse.TopPerformer(this.category, this.name, this.id, this.value, this.metric, this.rank);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "ExecutiveSummaryResponse.TopPerformer.TopPerformerBuilder(category=" + this.category + ", name=" + this.name + ", id=" + this.id + ", value=" + this.value + ", metric=" + this.metric + ", rank=" + this.rank + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static ExecutiveSummaryResponse.TopPerformer.TopPerformerBuilder builder() {
            return new ExecutiveSummaryResponse.TopPerformer.TopPerformerBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getCategory() {
            return this.category;
        }

        @java.lang.SuppressWarnings("all")
        public String getName() {
            return this.name;
        }

        @java.lang.SuppressWarnings("all")
        public String getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getValue() {
            return this.value;
        }

        @java.lang.SuppressWarnings("all")
        public String getMetric() {
            return this.metric;
        }

        @java.lang.SuppressWarnings("all")
        public int getRank() {
            return this.rank;
        }

        @java.lang.SuppressWarnings("all")
        public void setCategory(final String category) {
            this.category = category;
        }

        @java.lang.SuppressWarnings("all")
        public void setName(final String name) {
            this.name = name;
        }

        @java.lang.SuppressWarnings("all")
        public void setId(final String id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        public void setValue(final BigDecimal value) {
            this.value = value;
        }

        @java.lang.SuppressWarnings("all")
        public void setMetric(final String metric) {
            this.metric = metric;
        }

        @java.lang.SuppressWarnings("all")
        public void setRank(final int rank) {
            this.rank = rank;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ExecutiveSummaryResponse.TopPerformer)) return false;
            final ExecutiveSummaryResponse.TopPerformer other = (ExecutiveSummaryResponse.TopPerformer) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getRank() != other.getRank()) return false;
            final java.lang.Object this$category = this.getCategory();
            final java.lang.Object other$category = other.getCategory();
            if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
            final java.lang.Object this$name = this.getName();
            final java.lang.Object other$name = other.getName();
            if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$value = this.getValue();
            final java.lang.Object other$value = other.getValue();
            if (this$value == null ? other$value != null : !this$value.equals(other$value)) return false;
            final java.lang.Object this$metric = this.getMetric();
            final java.lang.Object other$metric = other.getMetric();
            if (this$metric == null ? other$metric != null : !this$metric.equals(other$metric)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ExecutiveSummaryResponse.TopPerformer;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getRank();
            final java.lang.Object $category = this.getCategory();
            result = result * PRIME + ($category == null ? 43 : $category.hashCode());
            final java.lang.Object $name = this.getName();
            result = result * PRIME + ($name == null ? 43 : $name.hashCode());
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $value = this.getValue();
            result = result * PRIME + ($value == null ? 43 : $value.hashCode());
            final java.lang.Object $metric = this.getMetric();
            result = result * PRIME + ($metric == null ? 43 : $metric.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ExecutiveSummaryResponse.TopPerformer(category=" + this.getCategory() + ", name=" + this.getName() + ", id=" + this.getId() + ", value=" + this.getValue() + ", metric=" + this.getMetric() + ", rank=" + this.getRank() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public TopPerformer() {
        }

        @java.lang.SuppressWarnings("all")
        public TopPerformer(final String category, final String name, final String id, final BigDecimal value, final String metric, final int rank) {
            this.category = category;
            this.name = name;
            this.id = id;
            this.value = value;
            this.metric = metric;
            this.rank = rank;
        }
    }


    public static class ActionableInsight {
        private String priority; // "HIGH", "MEDIUM", "LOW"
        private String category; // "Revenue", "Cost", "Customer", "Operations"
        private String title;
        private String description;
        private String recommendation;
        private BigDecimal potentialImpact; // INR or percentage
        private String impactType; // "Revenue Increase", "Cost Reduction", "Efficiency Gain"


        @java.lang.SuppressWarnings("all")
        public static class ActionableInsightBuilder {
            @java.lang.SuppressWarnings("all")
            private String priority;
            @java.lang.SuppressWarnings("all")
            private String category;
            @java.lang.SuppressWarnings("all")
            private String title;
            @java.lang.SuppressWarnings("all")
            private String description;
            @java.lang.SuppressWarnings("all")
            private String recommendation;
            @java.lang.SuppressWarnings("all")
            private BigDecimal potentialImpact;
            @java.lang.SuppressWarnings("all")
            private String impactType;

            @java.lang.SuppressWarnings("all")
            ActionableInsightBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.ActionableInsight.ActionableInsightBuilder priority(final String priority) {
                this.priority = priority;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.ActionableInsight.ActionableInsightBuilder category(final String category) {
                this.category = category;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.ActionableInsight.ActionableInsightBuilder title(final String title) {
                this.title = title;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.ActionableInsight.ActionableInsightBuilder description(final String description) {
                this.description = description;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.ActionableInsight.ActionableInsightBuilder recommendation(final String recommendation) {
                this.recommendation = recommendation;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.ActionableInsight.ActionableInsightBuilder potentialImpact(final BigDecimal potentialImpact) {
                this.potentialImpact = potentialImpact;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.ActionableInsight.ActionableInsightBuilder impactType(final String impactType) {
                this.impactType = impactType;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public ExecutiveSummaryResponse.ActionableInsight build() {
                return new ExecutiveSummaryResponse.ActionableInsight(this.priority, this.category, this.title, this.description, this.recommendation, this.potentialImpact, this.impactType);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "ExecutiveSummaryResponse.ActionableInsight.ActionableInsightBuilder(priority=" + this.priority + ", category=" + this.category + ", title=" + this.title + ", description=" + this.description + ", recommendation=" + this.recommendation + ", potentialImpact=" + this.potentialImpact + ", impactType=" + this.impactType + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static ExecutiveSummaryResponse.ActionableInsight.ActionableInsightBuilder builder() {
            return new ExecutiveSummaryResponse.ActionableInsight.ActionableInsightBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public String getPriority() {
            return this.priority;
        }

        @java.lang.SuppressWarnings("all")
        public String getCategory() {
            return this.category;
        }

        @java.lang.SuppressWarnings("all")
        public String getTitle() {
            return this.title;
        }

        @java.lang.SuppressWarnings("all")
        public String getDescription() {
            return this.description;
        }

        @java.lang.SuppressWarnings("all")
        public String getRecommendation() {
            return this.recommendation;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getPotentialImpact() {
            return this.potentialImpact;
        }

        @java.lang.SuppressWarnings("all")
        public String getImpactType() {
            return this.impactType;
        }

        @java.lang.SuppressWarnings("all")
        public void setPriority(final String priority) {
            this.priority = priority;
        }

        @java.lang.SuppressWarnings("all")
        public void setCategory(final String category) {
            this.category = category;
        }

        @java.lang.SuppressWarnings("all")
        public void setTitle(final String title) {
            this.title = title;
        }

        @java.lang.SuppressWarnings("all")
        public void setDescription(final String description) {
            this.description = description;
        }

        @java.lang.SuppressWarnings("all")
        public void setRecommendation(final String recommendation) {
            this.recommendation = recommendation;
        }

        @java.lang.SuppressWarnings("all")
        public void setPotentialImpact(final BigDecimal potentialImpact) {
            this.potentialImpact = potentialImpact;
        }

        @java.lang.SuppressWarnings("all")
        public void setImpactType(final String impactType) {
            this.impactType = impactType;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ExecutiveSummaryResponse.ActionableInsight)) return false;
            final ExecutiveSummaryResponse.ActionableInsight other = (ExecutiveSummaryResponse.ActionableInsight) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$priority = this.getPriority();
            final java.lang.Object other$priority = other.getPriority();
            if (this$priority == null ? other$priority != null : !this$priority.equals(other$priority)) return false;
            final java.lang.Object this$category = this.getCategory();
            final java.lang.Object other$category = other.getCategory();
            if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
            final java.lang.Object this$title = this.getTitle();
            final java.lang.Object other$title = other.getTitle();
            if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
            final java.lang.Object this$description = this.getDescription();
            final java.lang.Object other$description = other.getDescription();
            if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
            final java.lang.Object this$recommendation = this.getRecommendation();
            final java.lang.Object other$recommendation = other.getRecommendation();
            if (this$recommendation == null ? other$recommendation != null : !this$recommendation.equals(other$recommendation)) return false;
            final java.lang.Object this$potentialImpact = this.getPotentialImpact();
            final java.lang.Object other$potentialImpact = other.getPotentialImpact();
            if (this$potentialImpact == null ? other$potentialImpact != null : !this$potentialImpact.equals(other$potentialImpact)) return false;
            final java.lang.Object this$impactType = this.getImpactType();
            final java.lang.Object other$impactType = other.getImpactType();
            if (this$impactType == null ? other$impactType != null : !this$impactType.equals(other$impactType)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ExecutiveSummaryResponse.ActionableInsight;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $priority = this.getPriority();
            result = result * PRIME + ($priority == null ? 43 : $priority.hashCode());
            final java.lang.Object $category = this.getCategory();
            result = result * PRIME + ($category == null ? 43 : $category.hashCode());
            final java.lang.Object $title = this.getTitle();
            result = result * PRIME + ($title == null ? 43 : $title.hashCode());
            final java.lang.Object $description = this.getDescription();
            result = result * PRIME + ($description == null ? 43 : $description.hashCode());
            final java.lang.Object $recommendation = this.getRecommendation();
            result = result * PRIME + ($recommendation == null ? 43 : $recommendation.hashCode());
            final java.lang.Object $potentialImpact = this.getPotentialImpact();
            result = result * PRIME + ($potentialImpact == null ? 43 : $potentialImpact.hashCode());
            final java.lang.Object $impactType = this.getImpactType();
            result = result * PRIME + ($impactType == null ? 43 : $impactType.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ExecutiveSummaryResponse.ActionableInsight(priority=" + this.getPriority() + ", category=" + this.getCategory() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", recommendation=" + this.getRecommendation() + ", potentialImpact=" + this.getPotentialImpact() + ", impactType=" + this.getImpactType() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public ActionableInsight() {
        }

        @java.lang.SuppressWarnings("all")
        public ActionableInsight(final String priority, final String category, final String title, final String description, final String recommendation, final BigDecimal potentialImpact, final String impactType) {
            this.priority = priority;
            this.category = category;
            this.title = title;
            this.description = description;
            this.recommendation = recommendation;
            this.potentialImpact = potentialImpact;
            this.impactType = impactType;
        }
    }


    @java.lang.SuppressWarnings("all")
    public static class ExecutiveSummaryResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private String reportPeriod;
        @java.lang.SuppressWarnings("all")
        private LocalDate startDate;
        @java.lang.SuppressWarnings("all")
        private LocalDate endDate;
        @java.lang.SuppressWarnings("all")
        private FinancialSummary financialSummary;
        @java.lang.SuppressWarnings("all")
        private OperationalMetrics operationalMetrics;
        @java.lang.SuppressWarnings("all")
        private List<KPITile> kpiTiles;
        @java.lang.SuppressWarnings("all")
        private GrowthMetrics growthMetrics;
        @java.lang.SuppressWarnings("all")
        private List<TopPerformer> topPerformers;
        @java.lang.SuppressWarnings("all")
        private List<ActionableInsight> insights;

        @java.lang.SuppressWarnings("all")
        ExecutiveSummaryResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder reportPeriod(final String reportPeriod) {
            this.reportPeriod = reportPeriod;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder startDate(final LocalDate startDate) {
            this.startDate = startDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder endDate(final LocalDate endDate) {
            this.endDate = endDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder financialSummary(final FinancialSummary financialSummary) {
            this.financialSummary = financialSummary;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder operationalMetrics(final OperationalMetrics operationalMetrics) {
            this.operationalMetrics = operationalMetrics;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder kpiTiles(final List<KPITile> kpiTiles) {
            this.kpiTiles = kpiTiles;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder growthMetrics(final GrowthMetrics growthMetrics) {
            this.growthMetrics = growthMetrics;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder topPerformers(final List<TopPerformer> topPerformers) {
            this.topPerformers = topPerformers;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder insights(final List<ActionableInsight> insights) {
            this.insights = insights;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public ExecutiveSummaryResponse build() {
            return new ExecutiveSummaryResponse(this.reportPeriod, this.startDate, this.endDate, this.financialSummary, this.operationalMetrics, this.kpiTiles, this.growthMetrics, this.topPerformers, this.insights);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder(reportPeriod=" + this.reportPeriod + ", startDate=" + this.startDate + ", endDate=" + this.endDate + ", financialSummary=" + this.financialSummary + ", operationalMetrics=" + this.operationalMetrics + ", kpiTiles=" + this.kpiTiles + ", growthMetrics=" + this.growthMetrics + ", topPerformers=" + this.topPerformers + ", insights=" + this.insights + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder builder() {
        return new ExecutiveSummaryResponse.ExecutiveSummaryResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getReportPeriod() {
        return this.reportPeriod;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getStartDate() {
        return this.startDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getEndDate() {
        return this.endDate;
    }

    @java.lang.SuppressWarnings("all")
    public FinancialSummary getFinancialSummary() {
        return this.financialSummary;
    }

    @java.lang.SuppressWarnings("all")
    public OperationalMetrics getOperationalMetrics() {
        return this.operationalMetrics;
    }

    @java.lang.SuppressWarnings("all")
    public List<KPITile> getKpiTiles() {
        return this.kpiTiles;
    }

    @java.lang.SuppressWarnings("all")
    public GrowthMetrics getGrowthMetrics() {
        return this.growthMetrics;
    }

    @java.lang.SuppressWarnings("all")
    public List<TopPerformer> getTopPerformers() {
        return this.topPerformers;
    }

    @java.lang.SuppressWarnings("all")
    public List<ActionableInsight> getInsights() {
        return this.insights;
    }

    @java.lang.SuppressWarnings("all")
    public void setReportPeriod(final String reportPeriod) {
        this.reportPeriod = reportPeriod;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartDate(final LocalDate startDate) {
        this.startDate = startDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setEndDate(final LocalDate endDate) {
        this.endDate = endDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setFinancialSummary(final FinancialSummary financialSummary) {
        this.financialSummary = financialSummary;
    }

    @java.lang.SuppressWarnings("all")
    public void setOperationalMetrics(final OperationalMetrics operationalMetrics) {
        this.operationalMetrics = operationalMetrics;
    }

    @java.lang.SuppressWarnings("all")
    public void setKpiTiles(final List<KPITile> kpiTiles) {
        this.kpiTiles = kpiTiles;
    }

    @java.lang.SuppressWarnings("all")
    public void setGrowthMetrics(final GrowthMetrics growthMetrics) {
        this.growthMetrics = growthMetrics;
    }

    @java.lang.SuppressWarnings("all")
    public void setTopPerformers(final List<TopPerformer> topPerformers) {
        this.topPerformers = topPerformers;
    }

    @java.lang.SuppressWarnings("all")
    public void setInsights(final List<ActionableInsight> insights) {
        this.insights = insights;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ExecutiveSummaryResponse)) return false;
        final ExecutiveSummaryResponse other = (ExecutiveSummaryResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$reportPeriod = this.getReportPeriod();
        final java.lang.Object other$reportPeriod = other.getReportPeriod();
        if (this$reportPeriod == null ? other$reportPeriod != null : !this$reportPeriod.equals(other$reportPeriod)) return false;
        final java.lang.Object this$startDate = this.getStartDate();
        final java.lang.Object other$startDate = other.getStartDate();
        if (this$startDate == null ? other$startDate != null : !this$startDate.equals(other$startDate)) return false;
        final java.lang.Object this$endDate = this.getEndDate();
        final java.lang.Object other$endDate = other.getEndDate();
        if (this$endDate == null ? other$endDate != null : !this$endDate.equals(other$endDate)) return false;
        final java.lang.Object this$financialSummary = this.getFinancialSummary();
        final java.lang.Object other$financialSummary = other.getFinancialSummary();
        if (this$financialSummary == null ? other$financialSummary != null : !this$financialSummary.equals(other$financialSummary)) return false;
        final java.lang.Object this$operationalMetrics = this.getOperationalMetrics();
        final java.lang.Object other$operationalMetrics = other.getOperationalMetrics();
        if (this$operationalMetrics == null ? other$operationalMetrics != null : !this$operationalMetrics.equals(other$operationalMetrics)) return false;
        final java.lang.Object this$kpiTiles = this.getKpiTiles();
        final java.lang.Object other$kpiTiles = other.getKpiTiles();
        if (this$kpiTiles == null ? other$kpiTiles != null : !this$kpiTiles.equals(other$kpiTiles)) return false;
        final java.lang.Object this$growthMetrics = this.getGrowthMetrics();
        final java.lang.Object other$growthMetrics = other.getGrowthMetrics();
        if (this$growthMetrics == null ? other$growthMetrics != null : !this$growthMetrics.equals(other$growthMetrics)) return false;
        final java.lang.Object this$topPerformers = this.getTopPerformers();
        final java.lang.Object other$topPerformers = other.getTopPerformers();
        if (this$topPerformers == null ? other$topPerformers != null : !this$topPerformers.equals(other$topPerformers)) return false;
        final java.lang.Object this$insights = this.getInsights();
        final java.lang.Object other$insights = other.getInsights();
        if (this$insights == null ? other$insights != null : !this$insights.equals(other$insights)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ExecutiveSummaryResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $reportPeriod = this.getReportPeriod();
        result = result * PRIME + ($reportPeriod == null ? 43 : $reportPeriod.hashCode());
        final java.lang.Object $startDate = this.getStartDate();
        result = result * PRIME + ($startDate == null ? 43 : $startDate.hashCode());
        final java.lang.Object $endDate = this.getEndDate();
        result = result * PRIME + ($endDate == null ? 43 : $endDate.hashCode());
        final java.lang.Object $financialSummary = this.getFinancialSummary();
        result = result * PRIME + ($financialSummary == null ? 43 : $financialSummary.hashCode());
        final java.lang.Object $operationalMetrics = this.getOperationalMetrics();
        result = result * PRIME + ($operationalMetrics == null ? 43 : $operationalMetrics.hashCode());
        final java.lang.Object $kpiTiles = this.getKpiTiles();
        result = result * PRIME + ($kpiTiles == null ? 43 : $kpiTiles.hashCode());
        final java.lang.Object $growthMetrics = this.getGrowthMetrics();
        result = result * PRIME + ($growthMetrics == null ? 43 : $growthMetrics.hashCode());
        final java.lang.Object $topPerformers = this.getTopPerformers();
        result = result * PRIME + ($topPerformers == null ? 43 : $topPerformers.hashCode());
        final java.lang.Object $insights = this.getInsights();
        result = result * PRIME + ($insights == null ? 43 : $insights.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ExecutiveSummaryResponse(reportPeriod=" + this.getReportPeriod() + ", startDate=" + this.getStartDate() + ", endDate=" + this.getEndDate() + ", financialSummary=" + this.getFinancialSummary() + ", operationalMetrics=" + this.getOperationalMetrics() + ", kpiTiles=" + this.getKpiTiles() + ", growthMetrics=" + this.getGrowthMetrics() + ", topPerformers=" + this.getTopPerformers() + ", insights=" + this.getInsights() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public ExecutiveSummaryResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public ExecutiveSummaryResponse(final String reportPeriod, final LocalDate startDate, final LocalDate endDate, final FinancialSummary financialSummary, final OperationalMetrics operationalMetrics, final List<KPITile> kpiTiles, final GrowthMetrics growthMetrics, final List<TopPerformer> topPerformers, final List<ActionableInsight> insights) {
        this.reportPeriod = reportPeriod;
        this.startDate = startDate;
        this.endDate = endDate;
        this.financialSummary = financialSummary;
        this.operationalMetrics = operationalMetrics;
        this.kpiTiles = kpiTiles;
        this.growthMetrics = growthMetrics;
        this.topPerformers = topPerformers;
        this.insights = insights;
    }
}
