// Generated by delombok at Wed Nov 26 14:14:06 IST 2025
package com.MaSoVa.analytics.dto;

import java.math.BigDecimal;
import java.util.List;

public class TopProductsResponse {
    private List<ProductData> topProducts;
    private String period; // "TODAY", "WEEK", "MONTH"
    private String sortBy; // "QUANTITY" or "REVENUE"


    public static class ProductData {
        private int rank;
        private String itemId;
        private String itemName;
        private String category;
        private int quantitySold;
        private BigDecimal revenue;
        private BigDecimal unitPrice;
        private BigDecimal percentOfTotalRevenue;
        private String trend; // "UP", "DOWN", "STABLE", "NEW"


        @java.lang.SuppressWarnings("all")
        public static class ProductDataBuilder {
            @java.lang.SuppressWarnings("all")
            private int rank;
            @java.lang.SuppressWarnings("all")
            private String itemId;
            @java.lang.SuppressWarnings("all")
            private String itemName;
            @java.lang.SuppressWarnings("all")
            private String category;
            @java.lang.SuppressWarnings("all")
            private int quantitySold;
            @java.lang.SuppressWarnings("all")
            private BigDecimal revenue;
            @java.lang.SuppressWarnings("all")
            private BigDecimal unitPrice;
            @java.lang.SuppressWarnings("all")
            private BigDecimal percentOfTotalRevenue;
            @java.lang.SuppressWarnings("all")
            private String trend;

            @java.lang.SuppressWarnings("all")
            ProductDataBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public TopProductsResponse.ProductData.ProductDataBuilder rank(final int rank) {
                this.rank = rank;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public TopProductsResponse.ProductData.ProductDataBuilder itemId(final String itemId) {
                this.itemId = itemId;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public TopProductsResponse.ProductData.ProductDataBuilder itemName(final String itemName) {
                this.itemName = itemName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public TopProductsResponse.ProductData.ProductDataBuilder category(final String category) {
                this.category = category;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public TopProductsResponse.ProductData.ProductDataBuilder quantitySold(final int quantitySold) {
                this.quantitySold = quantitySold;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public TopProductsResponse.ProductData.ProductDataBuilder revenue(final BigDecimal revenue) {
                this.revenue = revenue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public TopProductsResponse.ProductData.ProductDataBuilder unitPrice(final BigDecimal unitPrice) {
                this.unitPrice = unitPrice;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public TopProductsResponse.ProductData.ProductDataBuilder percentOfTotalRevenue(final BigDecimal percentOfTotalRevenue) {
                this.percentOfTotalRevenue = percentOfTotalRevenue;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            public TopProductsResponse.ProductData.ProductDataBuilder trend(final String trend) {
                this.trend = trend;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            public TopProductsResponse.ProductData build() {
                return new TopProductsResponse.ProductData(this.rank, this.itemId, this.itemName, this.category, this.quantitySold, this.revenue, this.unitPrice, this.percentOfTotalRevenue, this.trend);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            public java.lang.String toString() {
                return "TopProductsResponse.ProductData.ProductDataBuilder(rank=" + this.rank + ", itemId=" + this.itemId + ", itemName=" + this.itemName + ", category=" + this.category + ", quantitySold=" + this.quantitySold + ", revenue=" + this.revenue + ", unitPrice=" + this.unitPrice + ", percentOfTotalRevenue=" + this.percentOfTotalRevenue + ", trend=" + this.trend + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        public static TopProductsResponse.ProductData.ProductDataBuilder builder() {
            return new TopProductsResponse.ProductData.ProductDataBuilder();
        }

        @java.lang.SuppressWarnings("all")
        public int getRank() {
            return this.rank;
        }

        @java.lang.SuppressWarnings("all")
        public String getItemId() {
            return this.itemId;
        }

        @java.lang.SuppressWarnings("all")
        public String getItemName() {
            return this.itemName;
        }

        @java.lang.SuppressWarnings("all")
        public String getCategory() {
            return this.category;
        }

        @java.lang.SuppressWarnings("all")
        public int getQuantitySold() {
            return this.quantitySold;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getRevenue() {
            return this.revenue;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getUnitPrice() {
            return this.unitPrice;
        }

        @java.lang.SuppressWarnings("all")
        public BigDecimal getPercentOfTotalRevenue() {
            return this.percentOfTotalRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public String getTrend() {
            return this.trend;
        }

        @java.lang.SuppressWarnings("all")
        public void setRank(final int rank) {
            this.rank = rank;
        }

        @java.lang.SuppressWarnings("all")
        public void setItemId(final String itemId) {
            this.itemId = itemId;
        }

        @java.lang.SuppressWarnings("all")
        public void setItemName(final String itemName) {
            this.itemName = itemName;
        }

        @java.lang.SuppressWarnings("all")
        public void setCategory(final String category) {
            this.category = category;
        }

        @java.lang.SuppressWarnings("all")
        public void setQuantitySold(final int quantitySold) {
            this.quantitySold = quantitySold;
        }

        @java.lang.SuppressWarnings("all")
        public void setRevenue(final BigDecimal revenue) {
            this.revenue = revenue;
        }

        @java.lang.SuppressWarnings("all")
        public void setUnitPrice(final BigDecimal unitPrice) {
            this.unitPrice = unitPrice;
        }

        @java.lang.SuppressWarnings("all")
        public void setPercentOfTotalRevenue(final BigDecimal percentOfTotalRevenue) {
            this.percentOfTotalRevenue = percentOfTotalRevenue;
        }

        @java.lang.SuppressWarnings("all")
        public void setTrend(final String trend) {
            this.trend = trend;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof TopProductsResponse.ProductData)) return false;
            final TopProductsResponse.ProductData other = (TopProductsResponse.ProductData) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getRank() != other.getRank()) return false;
            if (this.getQuantitySold() != other.getQuantitySold()) return false;
            final java.lang.Object this$itemId = this.getItemId();
            final java.lang.Object other$itemId = other.getItemId();
            if (this$itemId == null ? other$itemId != null : !this$itemId.equals(other$itemId)) return false;
            final java.lang.Object this$itemName = this.getItemName();
            final java.lang.Object other$itemName = other.getItemName();
            if (this$itemName == null ? other$itemName != null : !this$itemName.equals(other$itemName)) return false;
            final java.lang.Object this$category = this.getCategory();
            final java.lang.Object other$category = other.getCategory();
            if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
            final java.lang.Object this$revenue = this.getRevenue();
            final java.lang.Object other$revenue = other.getRevenue();
            if (this$revenue == null ? other$revenue != null : !this$revenue.equals(other$revenue)) return false;
            final java.lang.Object this$unitPrice = this.getUnitPrice();
            final java.lang.Object other$unitPrice = other.getUnitPrice();
            if (this$unitPrice == null ? other$unitPrice != null : !this$unitPrice.equals(other$unitPrice)) return false;
            final java.lang.Object this$percentOfTotalRevenue = this.getPercentOfTotalRevenue();
            final java.lang.Object other$percentOfTotalRevenue = other.getPercentOfTotalRevenue();
            if (this$percentOfTotalRevenue == null ? other$percentOfTotalRevenue != null : !this$percentOfTotalRevenue.equals(other$percentOfTotalRevenue)) return false;
            final java.lang.Object this$trend = this.getTrend();
            final java.lang.Object other$trend = other.getTrend();
            if (this$trend == null ? other$trend != null : !this$trend.equals(other$trend)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof TopProductsResponse.ProductData;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getRank();
            result = result * PRIME + this.getQuantitySold();
            final java.lang.Object $itemId = this.getItemId();
            result = result * PRIME + ($itemId == null ? 43 : $itemId.hashCode());
            final java.lang.Object $itemName = this.getItemName();
            result = result * PRIME + ($itemName == null ? 43 : $itemName.hashCode());
            final java.lang.Object $category = this.getCategory();
            result = result * PRIME + ($category == null ? 43 : $category.hashCode());
            final java.lang.Object $revenue = this.getRevenue();
            result = result * PRIME + ($revenue == null ? 43 : $revenue.hashCode());
            final java.lang.Object $unitPrice = this.getUnitPrice();
            result = result * PRIME + ($unitPrice == null ? 43 : $unitPrice.hashCode());
            final java.lang.Object $percentOfTotalRevenue = this.getPercentOfTotalRevenue();
            result = result * PRIME + ($percentOfTotalRevenue == null ? 43 : $percentOfTotalRevenue.hashCode());
            final java.lang.Object $trend = this.getTrend();
            result = result * PRIME + ($trend == null ? 43 : $trend.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "TopProductsResponse.ProductData(rank=" + this.getRank() + ", itemId=" + this.getItemId() + ", itemName=" + this.getItemName() + ", category=" + this.getCategory() + ", quantitySold=" + this.getQuantitySold() + ", revenue=" + this.getRevenue() + ", unitPrice=" + this.getUnitPrice() + ", percentOfTotalRevenue=" + this.getPercentOfTotalRevenue() + ", trend=" + this.getTrend() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public ProductData() {
        }

        @java.lang.SuppressWarnings("all")
        public ProductData(final int rank, final String itemId, final String itemName, final String category, final int quantitySold, final BigDecimal revenue, final BigDecimal unitPrice, final BigDecimal percentOfTotalRevenue, final String trend) {
            this.rank = rank;
            this.itemId = itemId;
            this.itemName = itemName;
            this.category = category;
            this.quantitySold = quantitySold;
            this.revenue = revenue;
            this.unitPrice = unitPrice;
            this.percentOfTotalRevenue = percentOfTotalRevenue;
            this.trend = trend;
        }
    }


    @java.lang.SuppressWarnings("all")
    public static class TopProductsResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private List<ProductData> topProducts;
        @java.lang.SuppressWarnings("all")
        private String period;
        @java.lang.SuppressWarnings("all")
        private String sortBy;

        @java.lang.SuppressWarnings("all")
        TopProductsResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TopProductsResponse.TopProductsResponseBuilder topProducts(final List<ProductData> topProducts) {
            this.topProducts = topProducts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TopProductsResponse.TopProductsResponseBuilder period(final String period) {
            this.period = period;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TopProductsResponse.TopProductsResponseBuilder sortBy(final String sortBy) {
            this.sortBy = sortBy;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public TopProductsResponse build() {
            return new TopProductsResponse(this.topProducts, this.period, this.sortBy);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "TopProductsResponse.TopProductsResponseBuilder(topProducts=" + this.topProducts + ", period=" + this.period + ", sortBy=" + this.sortBy + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static TopProductsResponse.TopProductsResponseBuilder builder() {
        return new TopProductsResponse.TopProductsResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public List<ProductData> getTopProducts() {
        return this.topProducts;
    }

    @java.lang.SuppressWarnings("all")
    public String getPeriod() {
        return this.period;
    }

    @java.lang.SuppressWarnings("all")
    public String getSortBy() {
        return this.sortBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setTopProducts(final List<ProductData> topProducts) {
        this.topProducts = topProducts;
    }

    @java.lang.SuppressWarnings("all")
    public void setPeriod(final String period) {
        this.period = period;
    }

    @java.lang.SuppressWarnings("all")
    public void setSortBy(final String sortBy) {
        this.sortBy = sortBy;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TopProductsResponse)) return false;
        final TopProductsResponse other = (TopProductsResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$topProducts = this.getTopProducts();
        final java.lang.Object other$topProducts = other.getTopProducts();
        if (this$topProducts == null ? other$topProducts != null : !this$topProducts.equals(other$topProducts)) return false;
        final java.lang.Object this$period = this.getPeriod();
        final java.lang.Object other$period = other.getPeriod();
        if (this$period == null ? other$period != null : !this$period.equals(other$period)) return false;
        final java.lang.Object this$sortBy = this.getSortBy();
        final java.lang.Object other$sortBy = other.getSortBy();
        if (this$sortBy == null ? other$sortBy != null : !this$sortBy.equals(other$sortBy)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TopProductsResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $topProducts = this.getTopProducts();
        result = result * PRIME + ($topProducts == null ? 43 : $topProducts.hashCode());
        final java.lang.Object $period = this.getPeriod();
        result = result * PRIME + ($period == null ? 43 : $period.hashCode());
        final java.lang.Object $sortBy = this.getSortBy();
        result = result * PRIME + ($sortBy == null ? 43 : $sortBy.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "TopProductsResponse(topProducts=" + this.getTopProducts() + ", period=" + this.getPeriod() + ", sortBy=" + this.getSortBy() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public TopProductsResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public TopProductsResponse(final List<ProductData> topProducts, final String period, final String sortBy) {
        this.topProducts = topProducts;
        this.period = period;
        this.sortBy = sortBy;
    }
}
